### ISSUE TITLE
StartIsBack Issue + TextGlow

### ISSUE THREAD

**Issue by TheDolphinSlayer** [Maplespe/DWMBlurGlass#1]
Hoping for an update to fix StartIsBack! Also maybe an implementation of glow behind text? Glass8 can hook into the symbols on Windows10 22H2 to provide glow behind the text? 

![fix](https://github.com/Maplespe/DWMBlurGlass/assets/73983610/a3c23b54-d0b7-4bdc-99d9-c126408e7171)

**Comment by Maplespe** [comment]
The text glowing effect is theoretically provided by the theme, besides glass8 itself is not open source software, we can't make it compatible with other systems, it can only be updated by its author.

**Comment by TheDolphinSlayer** [comment]
Sorry, I was trying to show that it was a possible feature to add! I'm grateful for this software already as it is.

Are you also saying that the developer of startisback++ would have to fix the issues with its startmenu?
________________________________

**Comment by Maplespe** [comment]
I'll see what's going on with the start menu issue.
Earlier you mentioned the glass8 problem and I was referring to it.

**Comment by Maplespe** [comment]
Please try this version, compatibility issues with StartIsBack should be resolved.
[Release_x64.zip](https://github.com/Maplespe/DWMBlurGlass/files/13937587/Release_x64.zip)

**Comment by TheDolphinSlayer** [comment]
It appears to be fixed, thank you ^ ^
