### ISSUE TITLE
Caption text glow is cut off at the bottom

### ISSUE THREAD

**Issue by kfh83** [Maplespe/DWMBlurGlass#101]
![image](https://github.com/Maplespe/DWMBlurGlass/assets/85626296/670bfd28-46e3-43f1-8294-70f7cb9d49ba)
As title says. Also, maybe an opportunity to look into implementing a glow method that uses the DWMWindow theme atlas glow class (in the likes of real Windows 7)? (poke @dulappy)

**Comment by angelbruni** [comment]
This issue is more noticeable when maximizing a window.
![image](https://github.com/Maplespe/DWMBlurGlass/assets/48385307/f4f4089e-190d-4cc8-ab2b-a5c7b2f76b9d)

**Comment by CallyHam** [comment]
oh this issue is back again, it already got fixed once before, it also happens on color windows
![image](https://github.com/Maplespe/DWMBlurGlass/assets/87724457/ea9e4e2a-f51f-45da-b4e7-a990f70e661c)

**Comment by Maplespe** [comment]
@kfh83 @angelbruni  I also fixed this in the attachment that fixes issue #109, you can try that attachment.

**Comment by Za9-118** [comment]
How do you even get caption text glow in the first place..?
