### ISSUE TITLE
win11最大化和最小化过程中模糊效果变为透明

### ISSUE THREAD

**Issue by JTFA** [Maplespe/DWMBlurGlass#102]
对于整个窗口都是模糊的应用来说效果比较难受，希望可以解决一下

**Comment by ALTaleX531** [comment]
无法解决，这是特性

**Comment by JTFA** [comment]
> 从 Aero 出现之后这个问题其实微软就一直没解决过，估计没那么好搞

确实，win11自带的Acrylic在动画过程中也是采样之前的模糊效果，也很割裂
感觉要是可以在动画过程中变成纯色说不定也可以，至少最小化和恢复过程中纯色应该能接受

**Comment by ALTaleX531** [comment]
那你们不如把未激活状态的混合色调成不透明的，这样不就是一样的效果么

**Comment by JTFA** [comment]
> 那你们不如把未激活状态的混合色调成不透明的，这样不就是一样的效果么

试了下，未激活设为不透明后，只有最小化动画是不透明的，打开和最大化动画还是会变透明

**Comment by JTFA** [comment]
> 那你们不如把未激活状态的混合色调成不透明的，这样不就是一样的效果么

未激活不透明还是不如透明好看，设成不透明的话就不如用win11系统的亚克力效果了（

**Comment by ALTaleX531** [comment]
我个人不是很介意动画中透明的事情，那你们觉得要不要加个选项让动画期间背景纯色

**Comment by JTFA** [comment]
> 我个人不是很介意动画中透明的事情，那你们觉得要不要加个选项让动画期间背景纯色

我觉得可以加，让用户选择是否纯色

**Comment by ALTaleX531** [comment]
一个坏消息就是没办法检测到窗口是否处于最大化/最小化的动画中，所以目前处于无解的状态

**Comment by JTFA** [comment]
> 一个坏消息就是没办法检测到窗口是否处于最大化/最小化的动画中，所以目前处于无解的状态

好的吧（
