### ISSUE TITLE
屏幕边缘的模糊效果有些异常，会透出一点下面的内容

### ISSUE THREAD

**Issue by JTFA** [Maplespe/DWMBlurGlass#103]
如图所示
![图片](https://github.com/Maplespe/DWMBlurGlass/assets/57850248/9f23b0aa-cc39-4ad0-a62c-18a1533b6cae)

**Comment by Maplespe** [comment]
这是因为模糊度太高的原因，不是bug 你把系统的Acrylic效果的应用放到边缘也是这种效果

**Comment by JTFA** [comment]
> 这是因为模糊度太高的原因，不是bug 你把系统的Acrylic效果的应用放到边缘也是这种效果
我这里系统的Acrylic是正常的啊

![图片](https://github.com/Maplespe/DWMBlurGlass/assets/57850248/054e1abf-d077-4ae6-893a-24e57d7cc14a)

**Comment by Maplespe** [comment]
我更新了一下附件 重新下载看看

**Comment by JTFA** [comment]
> 我更新了一下附件 重新下载看看

比刚才范围小了，但最边上还是有
![图片](https://github.com/Maplespe/DWMBlurGlass/assets/57850248/336a5c92-d005-42de-bd62-a9c6dbd020d1)

**Comment by Maplespe** [comment]
已经没法再调了，高斯模糊算法就是这样的 只有一个SOFT和HEAD 现在已经是HEAD了
