### ISSUE TITLE
2.0.0 works great! but StartIsBack

### ISSUE THREAD

**Issue by TheDolphinSlayer** [Maplespe/DWMBlurGlass#104]
I know this isn't really your problem, its not your program, your program works and does what it's designed to do. 

But before the new update the Reflection image was working with StartIsBack (The Global Blur works amazing still, as it did in the before update). If this can't be fixed, im sure an alternative could be done (like actually baking the glass reflection into the msstyle itself)

**Comment by Maplespe** [comment]
Because of our enhanced detection, applications that have modified the blurring effect themselves will not be processed, this is to prevent unforeseen circumstances from occurring. For example, rendering errors.

**Comment by TheDolphinSlayer** [comment]
That makes perfect sense, I  figured that's what was going on, I seen the topics about snipping tools. Thanks again!
