### ISSUE TITLE
[Question] Startisback support lost?

### ISSUE THREAD

**Issue by TheInsane101** [Maplespe/DWMBlurGlass#105]
I've been playing with the new update and I LOVE IT! It's amazing! Thank you so much for all the hard work!

I noticed that the reflection does not extend to the taskbar and start menu in Startisback, though. With the legacy blur, choosing the "Blur" option in Startisback settings extends that blur, reflections and all, to the taskbar and start menu, but the new options don't do that. This probably also implies that the new blur is not applied to them either. Did the legacy blur use the same blur SIB uses? Is it possible to extend the new blur options to the start menu and taskbar by other means, or will they never work with SIB?

https://github.com/Maplespe/DWMBlurGlass/assets/104862146/68904fc2-a387-4155-a369-f108fb7d4611

**Comment by Maplespe** [comment]
This was in fact an accident, and the effect of the SIB was not supposed to be modified.
This was mentioned in the issue just now #104

**Comment by TheInsane101** [comment]
Oh, I didn't see, sorry. Does this mean that SIB won't ever support it? Are there other ways to get taskbar and start menu compatibility?

**Comment by Maplespe** [comment]
You can choose to continue using the OldBlur method, which can be set on the Advanced page.

**Comment by TheInsane101** [comment]
That's a shame. Guess I'll just try to get used to not having it.

**Comment by Maplespe** [comment]
I think maybe in the future it might be possible to add an optional to override the accentblur effect.

**Comment by TheInsane101** [comment]
Sorry, what are you talking about exactly?

**Comment by Maplespe** [comment]
The blurring effect used by StartIsBack is called AccentBlur.
This is an internal dwm name and we can probably override it just like win11 overrides Mica.

**Comment by Maplespe** [comment]
In other words, we can replace AccentBlur with a custom effect.
This may cause other problems though. So if SIB really doesn't have a solution, we might consider it.

**Comment by ALTaleX531** [comment]
In short: add an option to override the blur effect of StartIsBack

**Comment by TheInsane101** [comment]
Oh, that's awesome! Thanks! I really appreciate your dedication! Do you accept donations?

**Comment by Maplespe** [comment]
> Oh, that's awesome! Thanks! I really appreciate your dedication! Do you accept donations?
You can click the Sponsor button on the project home page if you'd like, thanks.
