### ISSUE TITLE
Aero peak broken after updating to 2.0.0

### ISSUE THREAD

**Issue by ZyrusplaysAnimations** [Maplespe/DWMBlurGlass#107]
Before the 2.0.0 update, aero peak is normal. After I update, the aero peak became broken. Instead of the exact window size, it became a squashed rectangle (It looks like 5x10 rectangle). Restarted explorer.exe even my pc, no luck.

**Comment by ALTaleX531** [comment]
System build number please?

**Comment by ZyrusplaysAnimations** [comment]
Windows 10 22H2

**Comment by ALTaleX531** [comment]
![image](https://github.com/Maplespe/DWMBlurGlass/assets/105535231/11616b2c-da77-42ef-8f0c-97caed8fe5b8)
No, I mean `OS build`.

**Comment by ZyrusplaysAnimations** [comment]
```
Edition	Windows 10 Home Single Language
Version	22H2
Installed on	‎Wed, ‎8/‎25/‎2021
OS build	19045.3996
Experience	Windows Feature Experience Pack 1000.19053.1000.0
```

**Comment by ALTaleX531** [comment]
Can you upload a video about it? In my tests, explorer didn't crash.

**Comment by NotJorrd** [comment]
![image](https://github.com/Maplespe/DWMBlurGlass/assets/156122285/49917c08-c91a-4c97-aaf9-624219f0711b)

**Comment by ALTaleX531** [comment]
As far as I know, this is a bug introduced in Windows 10 since RS5 and there's nothing we can do about it.

**Comment by DanTheGuy720** [comment]
I like that this will be the last defining visual state of Windows 10 when it goes out of support, just buggy UI all around.

**Comment by ZyrusplaysAnimations** [comment]
It look like this when aero peak is activated.

Task Manager:
![image](https://github.com/Maplespe/DWMBlurGlass/assets/70579850/0c34beef-ddb9-4a24-a7ae-4a5f3f5e6f5b)

(File) Explorer (ExplorerBlurMica is enabled.):
(Can't capture, probably because of transparency.)

Aero peak acts normal on Task Manager and Explorer (File explorer) if 1 application is maximized.

I don't know if a windows update causes this issue. I think Windows just updated before I updated DWMGlassBlur to 2.0.0.

**Comment by ALTaleX531** [comment]
Just like what I said, this is a bug introduced in Windows 10 since RS5 and there's nothing we can do about it.

**Comment by ZyrusplaysAnimations** [comment]
Oh ok. Thanks for the info.
