### ISSUE TITLE
Drag Lag/Delay Issue

### ISSUE THREAD

**Issue by CallyHam** [Maplespe/DWMBlurGlass#109]
This issue seems to still persist on 2.0.0, no matter what blur method/radius i choose, in the recording you can see where my mouse actually is vs where the window is, version is 21H2, 19044.3930
doesn't happen on some windows like explorer and firefox but the rest it does

https://github.com/Maplespe/DWMBlurGlass/assets/87724457/dcdf2890-fab0-4e79-a381-c0713bf00c7e

**Comment by Maplespe** [comment]
Make sure you are using CustomBlur and need to reopen the target window after saving.
In my environmental tests it takes at least 20+ windows before the

**Comment by CallyHam** [comment]
![image](https://github.com/Maplespe/DWMBlurGlass/assets/87724457/9348ee17-c6d3-4199-8d02-66926dc702fe)
![image](https://github.com/Maplespe/DWMBlurGlass/assets/87724457/33a0a8b0-90d5-4c8c-be12-1b176e9609b8)
here are all my settings

**Comment by Maplespe** [comment]
Have you also modified uDWM.dll?

**Comment by CallyHam** [comment]
i am using a mod for the buttons but even with it completely removed i still get the same performance

**Comment by Maplespe** [comment]
What about the default theme?

**Comment by CallyHam** [comment]
enabled default windows 10 theme again and its still the same

**Comment by Maplespe** [comment]
Well, thank you, we haven't been able to determine what caused it yet because I can't reproduce it.

**Comment by CallyHam** [comment]
ill try reinstalling it and see if that fixes anything

**Comment by ALTaleX531** [comment]
What other software have you installed?

**Comment by CallyHam** [comment]
the only other software i have that affects dwm in anyway is windhawk and secureuxtheme, but with both of those disabled i'm still getting the same performance

**Comment by CallyHam** [comment]
i installed ltsc 2021 fresh in a vm, installed all the software i use to modify windows and theres no lag (with like a ton of windows open too), so im not sure if its something with nvidia software or its some other completely unrelated software

**Comment by wiktorwiktor12** [comment]
can confirm that it happens to me too, perhaps you are not getting the issue in your tests because of you having better computer specs? I run a i5 4590, gtx 1050

**Comment by CallyHam** [comment]
i've got a ryzen 7 1700x and an rtx 3060 so could be an nvidia thing im not sure

**Comment by CallyHam** [comment]
im now on a completely fresh install on my pc and this issue is still happening for some applications, not as bad but definitely still noticeable, maybe the custom blur still needs some optimizing, i'll test on another gpu and update on how that goes

**Comment by CallyHam** [comment]
nope exactly the same thing

**Comment by Maplespe** [comment]
Have you tried different versions of the driver?

**Comment by CallyHam** [comment]
i'll try that but i experienced the same issue on an entirely different gpu so im not sure that's the problem

**Comment by CallyHam** [comment]
I have tried downgrading to an older driver, using a lower resolution and using a higher scaling setting and all still have the same issue

**Comment by alealexpro100** [comment]
Same issue when using DWMBlurGlass with StartIsBack++ v2.9.19 (with Blur effect enabled for taskbar).

**Comment by AuroraePrime** [comment]
我也有相同的问题 软件使用的也是最新的2.0.0版本

https://github.com/Maplespe/DWMBlurGlass/assets/149229427/b3c77345-9d2d-41b4-8f5c-e563bf3e8e22

**Comment by AuroraePrime** [comment]
> 我也有相同的问题 软件使用的也是最新的2.0.0版本
> 
>  2024-02-07.12-28-09.mp4

处理器：E5-2697v3
显卡：GTX1060 6G
显卡驱动：551.23 Studio驱动
系统：Windows 10 22H2 19045.3930

**Comment by AuroraePrime** [comment]
> 我也有相同的问题 软件使用的也是最新的2.0.0版本
> 
>  2024-02-07.12-28-09.mp4

值得注意的是，在窗口移动时，处理器的单独一个线程占用率为100%，在不使用DWMBlurGlass时不会占用到100%

**Comment by AuroraePrime** [comment]
还有一个发现，打开任务管理器窗口不进入“性能”页面，窗口拖动延迟并不明显，当进入“性能”页面后，延迟就变得明显了

https://github.com/Maplespe/DWMBlurGlass/assets/149229427/9006e645-33c0-47e1-9312-59bd55badb3c

**Comment by windowsxp3790** [comment]
> I have tried downgrading to an older driver, using a lower resolution and using a higher scaling setting and all still have the same issue, is there any kind of debug/log file or anything else i can give that would be helpful here?

How much ram do you have?

**Comment by CallyHam** [comment]
32gb (2x16)

**Comment by Maplespe** [comment]
Try this, it should have fixed the latency issue and also fixed the glowing text cropping issue.
[Release_x64.zip](https://github.com/Maplespe/DWMBlurGlass/files/14190023/Release_x64.zip)

**Comment by AuroraePrime** [comment]
> 试试这个，它应该已经解决了延迟问题，也解决了发光的文本裁剪问题。 [Release_x64.zip](https://github.com/Maplespe/DWMBlurGlass/files/14190023/Release_x64.zip)

完美解决了延迟问题！感谢大佬

**Comment by CallyHam** [comment]
can confirm also this is solved along with the text issue, thanks for the fix!
