### ISSUE TITLE
DWMBlurGlass also modifies similar third-party apps

### ISSUE THREAD

**Issue by Undisputed00x** [Maplespe/DWMBlurGlass#11]
This project is one if not my fav for now because has brought Win10 Blur effect on most UI elements of Win11 by somehow modifying other third party apps which also modify the Windows UI.

To bring as much of Blur effects to my Windows i use which get also affected by DWMBlurGlass: 
[MFE](https://github.com/MicaForEveryone/MicaForEveryone)
[TranslucentFlyouts](https://github.com/ALTaleX531/TranslucentFlyouts)
[TranslucentTB](https://github.com/TranslucentTB/TranslucentTB)
[TranslucentSM](https://github.com/rounk-ctrl/TranslucentSM)

The only thing that is missing to make Windows11 fully with blur effect backdrop are UWP/WinUI elements which until now there in no open source project that accomplishes this. (At least an english one 😁)
![Screenshot 2024-01-17 045947](https://github.com/Maplespe/DWMBlurGlass/assets/80290008/c5df7f4d-2d2e-4913-989d-643502a58d3f)
![Screenshot 2024-01-17 154758](https://github.com/Maplespe/DWMBlurGlass/assets/80290008/688cafd9-ac54-4798-a7e9-a659c4e301d9)
![Screenshot 2024-01-17 155052](https://github.com/Maplespe/DWMBlurGlass/assets/80290008/61bbbec6-d168-492f-afe7-93daf9d71f8b)
![Screenshot 2024-01-17 155354](https://github.com/Maplespe/DWMBlurGlass/assets/80290008/cb3ceabf-0cea-43f3-ac35-66331456e2fd)
![Screenshot 2024-01-17 160202](https://github.com/Maplespe/DWMBlurGlass/assets/80290008/df16ac6b-774f-4f28-9b0f-754063de24f4)
![Screenshot 2024-01-17 155903](https://github.com/Maplespe/DWMBlurGlass/assets/80290008/7d24ee92-e198-46d9-8d86-b9be684f4611)

**Comment by Maplespe** [comment]
I wrote in ReadMe "Please note that the blur radius will affect the global, which also includes locations such as the start menu, notification center, etc.... "
Since this project is based on the underlying DWM implementation, it will affect the global blur effect of the system.

**Comment by Maplespe** [comment]
Regarding the transparency of WinUI/UWP third party apps, this project is not able to realize this type of functionality so in the future we may write a separate standalone project for it.
This project is based on the underlying dwm to realize the effect similar to AeroGlass to provide support for the underlying api, rather than desktop applications that level of operation.

**Comment by Undisputed00x** [comment]
@Maplespe Understood, nice project though, it'be nice to see more similar project in the future that can expand the customization of Windows effects to its entirety
