### ISSUE TITLE
CustomBlur not working on windows 10 22h2

### ISSUE THREAD

**Issue by Atomlxe** [Maplespe/DWMBlurGlass#116]
![image](https://github.com/Maplespe/DWMBlurGlass/assets/100674380/17da7de8-b6fa-452c-9918-462430a7fff1)

no idea what could be causing this, ive tried all the customblur options and none of them work

**Comment by TheDolphinSlayer** [comment]
did you restart firefox after? also not sure if it supports firefox

**Comment by ALTaleX531** [comment]
<img width="343" alt="image" src="https://github.com/Maplespe/DWMBlurGlass/assets/105535231/2fe3a173-b33c-4643-977b-e15d071b35cf">

Dude, make sure your blend color isn't opaque.

**Comment by Atomlxe** [comment]
> did you restart firefox after? also not sure if it supports firefox

im not sure why i didnt try that at first lol, restarting did fix it
and the theme i use for firefox has glass support so it all works well

**Comment by Asad-13** [comment]
> im not sure why i didnt try that at first lol, restarting did fix it and the theme i use for firefox has glass support so it all works well

I'm sorry this is not really "adding" to the bug, but could you please tell me what theme do you use?

**Comment by lucassilvas1** [comment]
> > im not sure why i didnt try that at first lol, restarting did fix it and the theme i use for firefox has glass support so it all works well
> 
> I'm sorry this is not really "adding" to the bug, but could you please tell me what theme do you use?

I'd like to know as well. Been trying to find a way to enable aero on browsers with no luck.
