### ISSUE TITLE
Programs persist to use light settings whilst in dark mode except for explorer

### ISSUE THREAD

**Issue by wiktorwiktor12** [Maplespe/DWMBlurGlass#117]
With Dark mode enabled, explorer uses the Dark mode settings like it should, but other programs persist to use the light mode settings

https://github.com/Maplespe/DWMBlurGlass/assets/68821018/1d5f716b-90ff-44de-891e-196e5b032428

see attached video for a demonstration

**Comment by wiktorwiktor12** [comment]
regardless, great program, enjoying using it a lot regardless of any bugs

**Comment by wiktorwiktor12** [comment]
running windows 10 pro 22h2 os build 19045.3930

**Comment by ALTaleX531** [comment]
The answer is that there are only a handful of apps in Windows 10 that support dark mode, and even without DwmBlurGlass, the titlebar of these apps is still white isn't it.

**Comment by Maplespe** [comment]
This is not a bug, only applications that support DarkMode will have Dark colors applied to them.

**Comment by wiktorwiktor12** [comment]
ah i see, understandable
