### ISSUE TITLE
feature request: custom text glow radius

### ISSUE THREAD

**Issue by not-nullptr** [Maplespe/DWMBlurGlass#12]
hello! your efforts are greatly appreciated and the fact that you've eseentially got feature parity with glass8 within a few days is mind blowing. that being said, the ability to tweak the text glow radius would be appreciated :]

**Comment by windowsxp3790** [comment]
> hello! your efforts are greatly appreciated and the fact that you've eseentially got feature parity with glass8 within a few days is mind blowing. that being said, the ability to tweak the text glow radius would be appreciated :]

i second this

**Comment by Maplespe** [comment]
In fact the win10 title bar has a crop area limit which is limited to the text rectangle size.
I'm trying to fix this as best I can, if the radius is too large, the glow effect goes beyond the text rectangle and gets cropped to a rectangular box, which is very ugly. This is not a problem that can be solved by customizing radius. So I'm going to look into optimizing this to get it closer to Win7.
When cropped it looks like this:
![M{_F1NS_I%{Z@C%A Z$Q_43](https://github.com/Maplespe/DWMBlurGlass/assets/43676879/83a441c0-db69-4959-ae9b-381fa044cf5c)

**Comment by not-nullptr** [comment]
> In fact the win10 title bar has a crop area limit which is limited to the text rectangle size. I'm trying to fix this as best I can, if the radius is too large, the glow effect goes beyond the text rectangle and gets cropped to a rectangular box, which is very ugly. This is not a problem that can be solved by customizing radius. So I'm going to look into optimizing this to get it closer to Win7. When cropped it looks like this: ![M{_F1NS_I%{Z@C%A Z$Q_43](https://private-user-images.githubusercontent.com/43676879/297472128-83a441c0-db69-4959-ae9b-381fa044cf5c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU1MTQ1MzQsIm5iZiI6MTcwNTUxNDIzNCwicGF0aCI6Ii80MzY3Njg3OS8yOTc0NzIxMjgtODNhNDQxYzAtZGI2OS00OTU5LWFlOWItMzgxZmEwNDRjZjVjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE3VDE3NTcxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThlNjFmZWRlNDg0MWFjNzA3MmE3YjM2M2I5ZTlhMmQxODc4MDMwNWEwMTQxNjcxMjA1Y2NmMTc1YWI2N2YzYzAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.PwK_8XqciJT5iccVcn_DF1D5WqV7zA1DdtCR8rR0Qhc)

such a shame; microsoft will always find ways to stop customizability. good luck fixing it ^-^

**Comment by Dulappy** [comment]
Hello, I'm the creator of another customization program for Windows 10 called Aero Window Manager (though it's not an actual window manager), which is currently in closed beta. The crop area is caused by some optimizations done to the rendering, and I'm not sure how easily fixable it is; I personally just rewrote the entire text rendering routine to use DirectWrite instead, and even managed to get glow working using some other tweaks, however that caused a multitude of bugs, so I'll have to find a different method, probably using MIL elements if I can get those working properly. Do you have anywhere I can message you directly, @Maplespe?

**Comment by Maplespe** [comment]
@Dulappy Do you have Twitter or Telegram?

**Comment by Maplespe** [comment]
@not-nullptr  You can try this first, I've optimized the rendering and it should look like this:
![1A2{IZO0}KZ{6OTK3_YQC X](https://github.com/Maplespe/DWMBlurGlass/assets/43676879/2663a04c-0acc-426b-a88e-8974148cffc2)
[Release_x64.zip](https://github.com/Maplespe/DWMBlurGlass/files/13979397/Release_x64.zip)

**Comment by not-nullptr** [comment]
> @not-nullptr You can try this first, I've optimized the rendering and it should look like this: ![1A2{IZO0}KZ{6OTK3_YQC X](https://private-user-images.githubusercontent.com/43676879/297816957-2663a04c-0acc-426b-a88e-8974148cffc2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU2MDQzMzcsIm5iZiI6MTcwNTYwNDAzNywicGF0aCI6Ii80MzY3Njg3OS8yOTc4MTY5NTctMjY2M2EwNGMtMGFjYy00MjZiLWE4OGUtODk3NDE0OGNmZmMyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE4VDE4NTM1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTlkMjg5NWIwODk1ZWFjZTk4OTFhY2ViZGFmNzkyNGVhNmIwM2JmOTQxZjcwNzI4YmM5NjVlMjJhYTlmNmQyNmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.a9nbP6Xce0WJ0mq-qc_lmAWAmJMngocbmgpdxs1hvf4) [Release_x64.zip](https://github.com/Maplespe/DWMBlurGlass/files/13979397/Release_x64.zip)

the glow looks great, although the text now seems too far to the right (and maybe a pixel too far down?)

first pic is using dwmblurglass, second is on windows 7:

![image](https://github.com/Maplespe/DWMBlurGlass/assets/62841684/1567ec37-c617-4c41-b645-1dcb0708211e)
![image](https://github.com/Maplespe/DWMBlurGlass/assets/62841684/b4a95977-d1f3-4b07-bde2-f285eaacc296)

**Comment by windowsxp3790** [comment]
> > @not-nullptr You can try this first, I've optimized the rendering and it should look like this: ![1A2{IZO0}KZ{6OTK3_YQC X](https://private-user-images.githubusercontent.com/43676879/297816957-2663a04c-0acc-426b-a88e-8974148cffc2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU2MDQzMzcsIm5iZiI6MTcwNTYwNDAzNywicGF0aCI6Ii80MzY3Njg3OS8yOTc4MTY5NTctMjY2M2EwNGMtMGFjYy00MjZiLWE4OGUtODk3NDE0OGNmZmMyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE4VDE4NTM1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTlkMjg5NWIwODk1ZWFjZTk4OTFhY2ViZGFmNzkyNGVhNmIwM2JmOTQxZjcwNzI4YmM5NjVlMjJhYTlmNmQyNmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.a9nbP6Xce0WJ0mq-qc_lmAWAmJMngocbmgpdxs1hvf4) [Release_x64.zip](https://github.com/Maplespe/DWMBlurGlass/files/13979397/Release_x64.zip)
> 
> the glow looks great, although the text now seems too far to the right (and maybe a pixel too far down?)
> 
> first pic is using dwmblurglass, second is on windows 7:
> 
> ![image](https://private-user-images.githubusercontent.com/62841684/297851650-1567ec37-c617-4c41-b645-1dcb0708211e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU2MDU4NzgsIm5iZiI6MTcwNTYwNTU3OCwicGF0aCI6Ii82Mjg0MTY4NC8yOTc4NTE2NTAtMTU2N2VjMzctYzYxNy00YzQxLWI2NDUtMWRjYjA3MDgyMTFlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE4VDE5MTkzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ2YzY0ZDU3NjBjMWY1YmY1NmYyMjJkN2VmYmI1OGQ5MWUzYTY1ZDQ3ODNiYTI1MDQ3OGI0MWM1MTczOGMwMTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.mqwAGWScIZGaIc4Pj544J-rY4f9y6YXZwezT-9bH5zY) ![image](https://private-user-images.githubusercontent.com/62841684/297852110-b4a95977-d1f3-4b07-bde2-f285eaacc296.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU2MDU4NzgsIm5iZiI6MTcwNTYwNTU3OCwicGF0aCI6Ii82Mjg0MTY4NC8yOTc4NTIxMTAtYjRhOTU5NzctZDFmMy00YjA3LWJkZTItZjI4NWVhYWNjMjk2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE4VDE5MTkzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVkMTc3OGQwYjVmMTFmY2ZmZWM2NDZlNGMzYmMzZDA1OGRmMWRiMjRiZWQ4YmUxM2Y3ZjRmZDMzOTA3Mjc0NWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.nqFGrRP5ZCSau-hPcIkr1zWtDlSkqDLlmQ33j3GIdaY)

Yeah dulappy mentioned to me that was a trade off I think

**Comment by CallyHam** [comment]
the text is also too high on maximized windows
![image](https://github.com/Maplespe/DWMBlurGlass/assets/87724457/52948b68-b0f2-4710-8176-45de873da2e8)

**Comment by Maplespe** [comment]
[Release_x64.zip](https://github.com/Maplespe/DWMBlurGlass/files/13986779/Release_x64.zip)

**Comment by CallyHam** [comment]
now its the correct height in fullscreen but the text cuts off at the bottom, it also cuts off in some other windows too like open/save dialogs and color dialogs 
![image](https://github.com/Maplespe/DWMBlurGlass/assets/87724457/d855e821-a89a-4db9-8e1c-6c12c69a7b52)
![image](https://github.com/Maplespe/DWMBlurGlass/assets/87724457/b921c92c-7af4-484d-b815-02a032a38229)
![image](https://github.com/Maplespe/DWMBlurGlass/assets/87724457/5b2ae1e1-fd0b-4bf5-b242-a30fb09ba74c)

**Comment by Maplespe** [comment]
Currently his rendering should be correct at high DPI, for low DPI further research is needed.

**Comment by CallyHam** [comment]
oh ok 100% dpi would be a good thing to look into since its the default and likely what most people are using

**Comment by Maplespe** [comment]
This has been fixed and I'm posting the attachment to #5  .

**Comment by CallyHam** [comment]
This has fixed the text glow issues i was having, the reflections look normal now but now they only show on whatever monitor is most to the left, in the image you should be able to see where it cuts off. 
![image](https://github.com/Maplespe/DWMBlurGlass/assets/87724457/4d160790-ba12-4dba-b0e8-d42d2f6dc4dc)

**Comment by Maplespe** [comment]
@CallyHam You will need to drag the window fully to the second monitor for this to work, and due to performance optimization I am not going to create oversized bitmaps across 2 monitors. So on a single monitor only the texture of the target monitor will be displayed.
