### ISSUE TITLE
Adjust intensity of the inactive effect on Aero shader

### ISSUE THREAD

**Issue by kfh83** [Maplespe/DWMBlurGlass#120]
I believe as is, the effect is still kinda mild and would be interesting to have it be adjustable in the config.ini or the GUI. Here it is in 7:
![image](https://github.com/Maplespe/DWMBlurGlass/assets/85626296/9d4911e8-cce5-42b1-ae6a-fd0a81c1ec50)
In DWMBlurGlass, i feel it's still kinda weak even if you adjust the colors.

**Comment by not-nullptr** [comment]
agreed. the current aero shader, although brilliant, isn't all too accurate yet when it comes to the accent colours.

**Comment by Maplespe** [comment]
Because win7 glass color can be adjusted in control panel, win7 aero can set saturation and brightness, there is no fixed standard value, different people can have different settings.
Your screenshot of win7 glass should have reduced saturation.

**Comment by Maplespe** [comment]
In fact, this value no longer includes transparency after Win7, they are completely opaque and are now used as a system accent color.
So this request is the same as #86.

**Comment by NotJorrd** [comment]
> Well the request isn't about actually using values from registry. I'm just making a point that the colorization behavior for DWMBlurGlass is different from Windows 7 because DWMBlurGlass' colorization just applies a semitransparent color to the borders, so USING THOSE VALUES from the Windows 7 registry results in something completely different.
> 
> Also forgive me if i'm not coming across clear i am kinda sleepy

I'm understanding completely what you are saying btw, and i agree

**Comment by TheInsane101** [comment]
> agreed. the current aero shader, although brilliant, isn't all too accurate yet when it comes to the accent colours.

And we can also agree that it's still WAY more accurate than glass8! You should be proud of yourselves for achieving this 😊
