### ISSUE TITLE
Titlebar blend color always uses inactive state value

### ISSUE THREAD

**Issue by SunshinePonyUwU** [Maplespe/DWMBlurGlass#121]
Windows 11 21H2 (Build 22000.2538)

https://github.com/Maplespe/DWMBlurGlass/assets/150380769/b602f02b-9320-4cff-98c4-61511c8277e9

**Comment by not-nullptr** [comment]
@Maplespe d48bc8b didn't fix this issue, though it worked in 2.0.0 for me?

**Comment by not-nullptr** [comment]
^ fixed after a restart, although i restarted before so this doesn't seem like an invalid issue? strange
