### ISSUE TITLE
StartisBack no longer compatible with Aero reflections

### ISSUE THREAD

**Issue by emeraldongithub** [Maplespe/DWMBlurGlass#122]
![image](https://github.com/Maplespe/DWMBlurGlass/assets/99167692/31f8e2f9-f506-447e-9b99-db446f8c55c4)

**Comment by ALTaleX531** [comment]
Duplicate of #105

**Comment by windowsxp3790** [comment]
Is there any plans on trying to replicate/get this effect back?

**Comment by Maplespe** [comment]
@windowsxp3790  I think it's explained pretty clearly in #105.
