### ISSUE TITLE
add set blend color from accent color

### ISSUE THREAD

**Issue by alexplaygithub** [Maplespe/DWMBlurGlass#123]
hi can you set the feature that sets the blend color to the accent color
but i want to be automatic, because im going to use it in my windows 7 mod, thank you!

![image](https://github.com/Maplespe/DWMBlurGlass/assets/76817483/807adb88-611f-4b15-b7e8-51605d7f5fde)

**Comment by Maplespe** [comment]
Duplicate of #86.
