### ISSUE TITLE
New DWM Crash that happens sometimes on Connecting from another computer using Microsoft's Remote Desktop program

### ISSUE THREAD

**Issue by LuisYeah1234-hub** [Maplespe/DWMBlurGlass#125]
Dont know if its caused by Windows or either DWMBlurGlass. but i think someone should implement that if dwm.exe crashes dwmblurglass re-sets the theme
A new DWM Crash. caused by KERNELBASE.dll now is here :
![image](https://github.com/Maplespe/DWMBlurGlass/assets/64372171/78faaf37-0ea3-40d6-a4dd-e1dc8e16346f)

**Comment by ALTaleX531** [comment]
I think it is same as #37.

**Comment by LuisYeah1234-hub** [comment]
i guess im closing this for now and hopefully a fix is found. (i would fix it myself if i knew it)
