### ISSUE TITLE
[Not an issue] The new modified XML files didnt get packed into release_x64

### ISSUE THREAD

**Issue by LuisYeah1234-hub** [Maplespe/DWMBlurGlass#127]
This is not a BUG or an ISSUE i've made this issue because github does not contain a chat or comments section to talk with owner
I've translated Advanced tab but the 2.0.1 does not seem to contain the new it-IT advanced tab translation
Which means the new XML made didnt get packed at all. If this could get resolved it would be good
![image](https://github.com/Maplespe/DWMBlurGlass/assets/64372171/d0ba2cfc-68f8-4bad-a2f2-d6cd86a9a1f3)

**Comment by Maplespe** [comment]
Sorry, I forgot, I'll add it later.

**Comment by Maplespe** [comment]
Updated.
