### ISSUE TITLE
feature request: accent color related things

### ISSUE THREAD

**Issue by not-nullptr** [Maplespe/DWMBlurGlass#13]
hello! sorry for all the feature requests; i'm eager to see this project blossom. a cool idea is to have seperate settings for inactive and active border colors. you could also use the system's accent color for this (maybe both, with the system accent as a toggle?)

**Comment by windowsxp3790** [comment]
> hello! sorry for all the feature requests; i'm eager to see this project blossom. a cool idea is to have seperate settings for inactive and active border colors. you could also use the system's accent color for this (maybe both, with the system accent as a toggle?)

Yessssss
Please 🙏

**Comment by windowsxp3790** [comment]
Would love to see this

**Comment by windowsxp3790** [comment]
> Updated.

Can you add an option to follow the system accent color from settings?

**Comment by NotJorrd** [comment]
> > Updated.
> 
> Can you add an option to follow the system accent color from settings?

i would love to see this

**Comment by Maplespe** [comment]
To be honest I'm not going to add it because I don't think it's necessary.
First of all it only has one color It can't be set separately for active and inactive windows.
Secondly, its color is completely opaque, which makes this tool pointless.

**Comment by not-nullptr** [comment]
> To be honest I'm not going to add it because I don't think it's necessary. First of all it only has one color It can't be set separately for active and inactive windows. Secondly, its color is completely opaque, which makes this tool pointless.

agreed, this seems a little excessive. can you not just set it to the same colour in the settings?

**Comment by Maplespe** [comment]
System colors are not transparent, so they are not useful.
