### ISSUE TITLE
Title bar blur for maximized window seems too thick

### ISSUE THREAD

**Issue by SunshinePonyUwU** [Maplespe/DWMBlurGlass#133]
Windows 11 21H2 (Build 22000.2538)
The problem is very obvious when the taskbar is set to transparent and at the top of the screen
![image](https://github.com/Maplespe/DWMBlurGlass/assets/150380769/ea57660f-8c65-4f02-b0dd-3e3fee559d18)
Normally it looks like this
![image](https://github.com/Maplespe/DWMBlurGlass/assets/150380769/b9007c86-b5fb-499f-b9fb-a9bad741b87a)

**Comment by ALTaleX531** [comment]
![image](https://github.com/Maplespe/DWMBlurGlass/assets/105535231/f280cee5-07a1-45cd-897d-1faf7cca42f4)
你似乎使用的不是最新版本

**Comment by SunshinePonyUwU** [comment]
> ![image](https://private-user-images.githubusercontent.com/105535231/303327379-f280cee5-07a1-45cd-897d-1faf7cca42f4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDczOTU5NzMsIm5iZiI6MTcwNzM5NTY3MywicGF0aCI6Ii8xMDU1MzUyMzEvMzAzMzI3Mzc5LWYyODBjZWU1LTA3YTEtNDVjZC04OTdkLTFmYWY3Y2NhNDJmNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIwOFQxMjM0MzNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02MWZjYTUxMTczMDYzMzQ5Y2U2NDY4NzMzNDNkYmQ3NzRkMjZmMTc0N2E3MTdiNzMyMmU1ZDczZGQ4NWJiMjhhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.n6AFGS3umBytxRcLogchfkSrNAbdwTenfbdAiFK9l6o) 你似乎使用的不是最新版本

任务栏为透明时才可以复现，我是使用TranslucentTB时发现的问题
我使用的是release中最新的2.0.1版本

**Comment by ALTaleX531** [comment]
我明白了，这会在下一个版本中修复
