### ISSUE TITLE
windows 7 style buttons are not 1 to 1 to windows 7

### ISSUE THREAD

**Issue by wiktorwiktor12** [Maplespe/DWMBlurGlass#135]
![image](https://github.com/Maplespe/DWMBlurGlass/assets/68821018/a40d2903-fd4d-42f1-967d-f1a109c20f5d)
as shown in the image attached where the bottom buttons are from w7 and the top windows are from windows 10 22h2 running dwmblurglass (green line for alignment), the buttons are not 1 to 1 with windows7

I have made my own modifications to the dll however i do not think this code is the best code to resolve this issue as im pretty sure it will not scale properly with dpi.

![image](https://github.com/Maplespe/DWMBlurGlass/assets/68821018/514843ca-88f0-4ed0-93f3-a3fa7084a0af)
in CustomButton.cpp

opening an issue instead of a pull request because i do not think this is the best way to solve this and will likely not scale with dpi (got no way to test this)

**Comment by wiktorwiktor12** [comment]
these modifications to the dll resolves the issue if it was not clear, but dont think its the best solution

**Comment by wiktorwiktor12** [comment]
stupidly hit close and comment

**Comment by Maplespe** [comment]
The current frame calculation seems to be affected by the theme, we are considering if there is a better solution but not yet.

**Comment by wiktorwiktor12** [comment]
aha ye i see, this is obviously not super high priority since this is a minor thing that i was able to temporarily fix

**Comment by windowsxp3790** [comment]
Bump

**Comment by TorutheRedFox** [comment]
the right side of the close button is also supposed to extend past the right edge of the screen when the window is maximized

**Comment by wiktorwiktor12** [comment]
fixed as of 2.2.0
