### ISSUE TITLE
Aero reflection texture cutoff on multi-monitor setup

### ISSUE THREAD

**Issue by xan1242** [Maplespe/DWMBlurGlass#136]
Hello,

I am using DWMBlurGlass on Win11 22621.1702 (yes I know a bit of an old build).

First, let me show my monitor configuration (because it may be relevant to the bug):

![image](https://github.com/Maplespe/DWMBlurGlass/assets/8014093/ab4ad41c-e413-4991-bbf1-55e5379e0bc0)

Monitor 1 is 3440x1440, monitor 2 is 1920x1080

If I place the explorer window near the right edge of monitor 2, this happens with the Aero reflection texture:

![image](https://github.com/Maplespe/DWMBlurGlass/assets/8014093/b5805fba-1d1b-4700-9b3d-c97391b8c206)

The texture isn't being correctly applied here for some reason.

Enabling/disabling the setting while the window is placed there doesn't affect anything.

Also, placing the window closer to monitor 1 shows this:

![image](https://github.com/Maplespe/DWMBlurGlass/assets/8014093/d9d227b7-8c37-4a33-8351-1a107c60318d)

Dimensions of the Explorer window were 1146x666, if that's of any help

**Comment by Maplespe** [comment]
Oh well, we haven't tested multiple monitors and resolutions like this. It looks like there are still some issues with the image scale calculation.
A temporary workaround is to manually edit the data/AeroPeek.png image and resize it to the appropriate scale and size.

**Comment by NotJorrd** [comment]
even on two 1080p monitors i get this issue on my right monitor

**Comment by jimkoutso2008** [comment]
Same issue here with 2 1080p monitors
![image](https://github.com/Maplespe/DWMBlurGlass/assets/82086687/71e9157b-954d-416c-bdbc-871f5fb563ec)

**Comment by indigofairyx** [comment]
ive been seeing this too. have a 4k primary with a 1080p 2nd moniter.
