### ISSUE TITLE
Huge gap between titlebar icon and text on windows (Right to Left)

### ISSUE THREAD

**Issue by novatiberium** [Maplespe/DWMBlurGlass#138]
![תמונה](https://github.com/Maplespe/DWMBlurGlass/assets/68118732/7d448f22-ce9a-441a-b47b-db56764b153d)

I'm just wondering if anyone has had this issue as well? There is a known issue where on specific apps there's a gap between the titlebar and text on top of application windows.

**Comment by NotJorrd** [comment]
maybe it has something to do with the fact that your layout is BACKWARDS (but i dunno, I've never had this issue)

**Comment by windowsxp3790** [comment]
> maybe it has something to do with the fact that your layout is BACKWARDS (but i dunno, I've never had this issue)

It's Hebrew 💀

**Comment by novatiberium** [comment]
That issue can be fixed for RTL Windows. I think if we add a RTL support and fix the gap that would be better. I'm sure a FEW users I talked to online had this issue (and they are using LTR Windows English)

**Comment by novatiberium** [comment]
Has anyone found a solution to this issue yet?

**Comment by novatiberium** [comment]
I updated the title to reflect that this bug only happens on programs that are (or if the Windows OS is) set to right-to-left languages, issue is likely not replicated when programs (or Windows) are in LTR (Left to right).

**Comment by windowsxp3790** [comment]
> Has anyone found a solution to this issue yet?

No 
Hopefully it gets fixed in 2.0.2

**Comment by novatiberium** [comment]
Alright, 2.1.1 came out and the same issue has persisted, assuming it hasn't been fixed yet.
