### ISSUE TITLE
Tool window frames reflection broken in paint.net

### ISSUE THREAD

**Issue by nopahc4** [Maplespe/DWMBlurGlass#14]
The titlebars of tool window frames in paint.net have broken reflections, this is probably caused by paint.net changing the opacity of these windows. https://cdn.discordapp.com/attachments/999083687775830117/1197834447949660180/fOEEQh0ZHa.gif?ex=65bcb543&is=65aa4043&hm=d5e6bff07a175805d5a294743243db2c0cef356971da8fb3a20aa5f41dfd2fc2&

**Comment by Maplespe** [comment]
Are you using multiple monitors?

**Comment by CallyHam** [comment]
i've been having this issue except on every window and disconnecting my second monitor fixed it, so its a multi monitor thing

**Comment by nopahc4** [comment]
> Are you using multiple monitors?

Only 1

**Comment by nopahc4** [comment]
> i've been having this issue except on every window and disconnecting my second monitor fixed it, so its a multi monitor thing

I'm only using 1

**Comment by Maplespe** [comment]
@nopahc4 Try the new attachment here #5
