### ISSUE TITLE
[Request] Windows Vista titlebar button style (Alternative to Win7 style)

### ISSUE THREAD

**Issue by WF4123** [Maplespe/DWMBlurGlass#142]
I want to make my Windows 10 OS look like Windows Vista very accurate, but I don't want to replace some DWM files in System32, it might getting problem with looping login screen and black screen with cursor, every single time.

Here's what it looks like.
![image](https://github.com/Maplespe/DWMBlurGlass/assets/66336727/a134760c-26bb-442f-9178-27a4aa9479af)

and BTW I'm using Aero10 Vista theme.

**Comment by ItsLezr** [comment]
Have you tried changing the titlebar size to 19/20 with something like Winaero Tweaker?

**Comment by WF4123** [comment]
> Have you tried changing the titlebar size to 19/20 with something like Winaero Tweaker?

this doesn't work, sorry.

**Comment by TheInsane101** [comment]
> > Have you tried changing the titlebar size to 19/20 with something like Winaero Tweaker?
> 
> this doesn't work, sorry.

Have tried it too; can confirm it doesn't size it properly (+ adds fullscreen text cropping issue)

**Comment by WF4123** [comment]
> Have tried it too; can confirm it doesn't size it properly (+ adds fullscreen text cropping issue)
You heard that.
And also this issue was occurred on titlebar text on the top when using Aero10 theme.
![image](https://github.com/Maplespe/DWMBlurGlass/assets/66336727/de9eb8b0-671f-4fdc-a9cb-03697983a72d)

**Comment by TorutheRedFox** [comment]
using a windhawk mod with proper windows 7 caption button metric port yields results that are slightly off from vista, but adjusting the values slightly (and using the 19px titlebar size) gets me 1:1 with vista

**Comment by TorutheRedFox** [comment]
i modified a private windhawk mod

**Comment by WF4123** [comment]
cool

**Comment by Maplespe** [comment]
In fact, you can also modify the DWMBlurGlassExt code on your own, just like #142.

**Comment by aliasmaychange** [comment]
I have a better suggestion, why don't we make **each** size value changeable on a separate "Caption Buttons" tab?

**Comment by ALTaleX531** [comment]
This can be done with AWM or other windhawk mods.
