### ISSUE TITLE
我应该如何下载符号文件

### ISSUE THREAD

**Issue by maidang2233** [Maplespe/DWMBlurGlass#144]
**Describe the bug**
> A clear and concise description of what the bug is:

我尝试了所以的方法都没办法在微软下载符号文件(可能有一些我不知道的方法)

**To Reproduce**
> Steps to reproduce the behavior:

Description ....

**Screenshots**
> If applicable, add screenshots to help explain your problem:

![cfc73f5af49124f11b225df25351bd47](https://github.com/Maplespe/DWMBlurGlass/assets/50991689/eaa8a55a-0575-422a-8547-940c3d598bf4)

**Additional information (please complete the following information):**
 > OS Version : [e.g. Windows 11 23H2.22631.3085]
 > Software Version : [e.g. 2.0.1]

Win_Pro_11_22H2_64ARM_ChnSimp_Pro_Ent_EDU_N_MLF_X23-12755

版本	Windows 11 专业版
版本	22H2
安装日期	‎2022/‎5/‎7
操作系统版本	22621.382
序列号	2528797168
体验	Windows Feature Experience Pack 1000.22632.1000.0

**What other third-party software do you use:**
 > [e.g. windhawk mods xxx]

StartAllBack

None

**Additional context**

**Comment by Maplespe** [comment]
不支持ARM架构，只支持x64架构
