### ISSUE TITLE
shine not working on aero snap

### ISSUE THREAD

**Issue by windowsxp3790** [Maplespe/DWMBlurGlass#148]
ever since 2.0.0 the shine streaks have not been working for me on the aero snap feature 
![peak](https://github.com/Maplespe/DWMBlurGlass/assets/149018134/32d7829f-b770-4d8c-b921-dc5afe6de24f)

**Comment by Maplespe** [comment]
We have never modified or volunteered the shine feature in AeroPeek.
The shine is controlled by your theme, it will only show if your theme has it.
![114518](https://github.com/Maplespe/DWMBlurGlass/assets/43676879/b172d9a9-54fa-430d-9524-c9a8c01a338a)
![114610](https://github.com/Maplespe/DWMBlurGlass/assets/43676879/5804fbef-b66b-473c-b0a4-8450518898e1)

**Comment by windowsxp3790** [comment]
> We have never modified or volunteered the shine feature in AeroPeek. The shine is controlled by your theme, it will only show if your theme has it. ![114518](https://private-user-images.githubusercontent.com/43676879/303967867-b172d9a9-54fa-430d-9524-c9a8c01a338a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc3MTAwNDMsIm5iZiI6MTcwNzcwOTc0MywicGF0aCI6Ii80MzY3Njg3OS8zMDM5Njc4NjctYjE3MmQ5YTktNTRmYS00MzBkLTk1MjQtYzlhOGMwMWEzMzhhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjEyVDAzNDkwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ4ZTczNGU2MzZmZjE3YThlNGVkOThkMTRkMTAwODM3ZDllMGU0M2RlZTRhYmNlOTk3ZjkxNjI4MWIxYjkyNDMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.cvLKFGMNycv9yzfZJwsWHyxa1Zs8deGDcpbh4CtMuts) ![114610](https://private-user-images.githubusercontent.com/43676879/303967873-5804fbef-b66b-473c-b0a4-8450518898e1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc3MTAwNDMsIm5iZiI6MTcwNzcwOTc0MywicGF0aCI6Ii80MzY3Njg3OS8zMDM5Njc4NzMtNTgwNGZiZWYtYjY2Yi00NzNjLWIwYTQtODQ1MDUxODg5OGUxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjEyVDAzNDkwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTcyMTUzNDA5NjQ2OGM3NzA3MjdkZDIzZjBiMThjNDIyNjMyOWI5MDkwYzVkYjM1NzIxMzkwODBhNDk5Zjc5ZTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Yh_-Z0iD7BnctAA5hQ4cPkVm-SSfbdt4zg23Ks3GTEM)

i got my terms mixed up 
i meant to say AeroSnap instead of aeropeak
aeropeak has the proper streaks

**Comment by Maplespe** [comment]
Like mine says, it's controlled by your theme.
![122258](https://github.com/Maplespe/DWMBlurGlass/assets/43676879/a0175d94-dda8-4696-a274-6c502a593261)

**Comment by windowsxp3790** [comment]
> Like mine says, it's controlled by your msstyles. This is true even if you don't use DWMBlurGlass. ![122258](https://private-user-images.githubusercontent.com/43676879/303970556-a0175d94-dda8-4696-a274-6c502a593261.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc3MTUyNTIsIm5iZiI6MTcwNzcxNDk1MiwicGF0aCI6Ii80MzY3Njg3OS8zMDM5NzA1NTYtYTAxNzVkOTQtZGRhOC00Njk2LWEyNzQtNmM1MDJhNTkzMjYxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjEyVDA1MTU1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg1ZWEyYmNmOTUwZjBhYmQ5NzBhMjFlNjU5YTkzZmI2OGIxMzZhZDI1MjMxYWYwNDA1NjExOGZiMGVkZmQ3ZDgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.6UyXUiKztzBJp60UKc_2iAgkQzpOdCz1HmrZteyvnCU)

What msstyles are you using there ?
I'm using aero10 by vaporvance

**Comment by Maplespe** [comment]
I'm using aero10, but I added the glass texture myself.
However, due to the removal of some uxtheme attributes after win7, the texture may be compressed and it's not perfect, maybe there are other ways to achieve it,but it's really not a bug in DWMBlurGlass.

**Comment by windowsxp3790** [comment]
Before 2.0.0 DWMBG used to add the streaks from the aeropeak image to the aero snap feature as well iirc

**Comment by ALTaleX531** [comment]
Just like #105.
BTW, don't use the blank issue next time.

**Comment by windowsxp3790** [comment]
> Just like #105. BTW, don't use the blank issue next time.

Old blur doesn't make them show up either

**Comment by Maplespe** [comment]
You should remember wrongly that we never added reflections for Aero Snap.
The old version is there, you can always download it and test it.
