### ISSUE TITLE
Effects not enabled and program crashes after restart

### ISSUE THREAD

**Issue by okamitime** [Maplespe/DWMBlurGlass#149]
CustomBlur and OldBlur on Windows 10 22H2 work as intended when I login after shutting down and logging off but if I restart the effects don't appear and the program crashes afterwards. DWMAPI doesn't have this issue

**Comment by NotJorrd** [comment]
When I reboot, the effect doesn't apply, no matter how many times I reboot. A temp fix would be to uninstall dwmblurglass, reboot, and then install again.

**Comment by Skyyblaze** [comment]
I just started using DWM Blur Glass and I can confirm the issue, the program isn't applied after a reboot. I have to uninstall and reinstall it for it to work again. A reboot in-between isn't necessary.

**Comment by Maplespe** [comment]
I can confirm that it is indeed a bug and will be fixed in the next release.
Please be patient. It is probabilistic though and doesn't happen to everyone.

**Comment by Skyyblaze** [comment]
> I can confirm that it is indeed a bug and will be fixed in the next release. Please be patient. It is probabilistic though and doesn't happen to everyone.
> 
> Temporarily, you can create a shortcut and append a command line argument to the end of the path: `loaddll`. Running it will immediately load it silently without having to uninstall and reinstall it.

Thank you for your hard work, you make Windows such a joy to use!

And just to confirm, this is how the shortcut should look like, right?

`"C:\Program Files\DWM Blur Glass\DWMBlurGlass.exe" -loaddll`

I'll put it in my auto-start folder.

**Comment by Maplespe** [comment]
@Skyyblaze  No "-".
`"C:\Program Files\DWM Blur Glass\DWMBlurGlass.exe" loaddll`

**Comment by Maplespe** [comment]
@Skyyblaze No "-".
"C:\Program Files\DWM Blur Glass\DWMBlurGlass.exe" loaddll

Also, the program requires UAC permissions, you put it in the auto-start folder it may pop up a window to confirm, this is normal.

Alternatively, you can modify the existing scheduled task "DWMBlurGlass_Extend" to add a little delay in startup.

**Comment by Skyyblaze** [comment]
@Maplespe Ah I got it now, thank you very much!

**Comment by daveo76** [comment]
I'm having that problem. It doesn't auto start up from boot and have to manually run it. 3rd party programs I use are ExplorerPatcher & TranslucentTB. Using Windows 11 Pro 23H2 22631.3155

**Comment by daveo76** [comment]
> @Skyyblaze No "-". "C:\Program Files\DWM Blur Glass\DWMBlurGlass.exe" loaddll
> 
> Also, the program requires UAC permissions, you put it in the auto-start folder it may pop up a window to confirm, this is normal.
> 
> Alternatively, you can modify the existing scheduled task "DWMBlurGlass_Extend" to add a little delay in startup.

How do I do that on Windows 11 Pro to add delay to it. Also does it make it work?

**Comment by daveo76** [comment]
> @Skyyblaze No "-". "C:\Program Files\DWM Blur Glass\DWMBlurGlass.exe" loaddll
> 
> Also, the program requires UAC permissions, you put it in the auto-start folder it may pop up a window to confirm, this is normal.
> 
> Alternatively, you can modify the existing scheduled task "DWMBlurGlass_Extend" to add a little delay in startup.

Thanks. I added 1 minute delay to it and it worked. Using Windows 11 Pro 23H2 22631.3155

**Comment by Starstrike** [comment]
I added this into Task Scheduler to run 1 minute after login. The app itself doesn't recognize that it's "installed" but changing the settings and saving does work. This will certainly do until the app is updated to auto load the dll on start.

**Comment by blikthepro** [comment]
hi, i've been experiencing the same issue. i tried to sidestep the issue using the task scheduler but no dice. i may not be as experienced with windows as i'd hope so i don't know what mistake i've made or if it just won't work. here's the task schedule i've setup for it 
![image](https://github.com/Maplespe/DWMBlurGlass/assets/89069658/baaf1cc5-d5a2-4240-8cf3-1039ca29045a)
![image](https://github.com/Maplespe/DWMBlurGlass/assets/89069658/1cceec1d-24d4-487f-b05e-59dc0b9a0632)
![image](https://github.com/Maplespe/DWMBlurGlass/assets/89069658/2b6be697-c507-4d3c-8788-faf4daacca15)
![image](https://github.com/Maplespe/DWMBlurGlass/assets/89069658/e677cd24-79e9-4294-bbda-7f7398e925b1)
![image](https://github.com/Maplespe/DWMBlurGlass/assets/89069658/8d518419-57c2-40ee-bb6f-34c1d8c7de1b)
if anyone could provide any pointers, thanks in advance

**Comment by blikthepro** [comment]
update on my previous comment: i restarted and it works. the images i posted are the configuration that works. i dont know what i did to fix it
