### ISSUE TITLE
Titlebar Text wrong positioning

### ISSUE THREAD

**Issue by EndlessLuck** [Maplespe/DWMBlurGlass#15]
When resizing the window, the titlebar text changes its position, which it should not do. The window text appears correctly before resizing, as shown in the following image:
![image (8)](https://github.com/Maplespe/DWMBlurGlass/assets/64068157/8173622c-bf9f-4c55-8aa4-38f56aeff0b0)
However, after resizing the window slightly, the text position shifts, as illustrated in the image below:
![image (9)](https://github.com/Maplespe/DWMBlurGlass/assets/64068157/85e4fba3-cf18-47e7-8597-dc7d20764060)
When further resizing the window, the text continues to change its position:
![image (10)](https://github.com/Maplespe/DWMBlurGlass/assets/64068157/5d0faaea-eacd-44b6-96f8-543f155efd68)
Continued resizing eventually leads to the caption text disappearing altogether. It's important to note that this issue is not related to the theme I am using, as I have tested it with both a custom theme and the default Windows 10 theme.

**Comment by Maplespe** [comment]
What system version are you using?
I tested on Windows 10 22H2 (19045.3930) with no problems.
Maybe you need to reopen the window.

**Comment by EndlessLuck** [comment]
I am using Windows 10 21H2 LTSC (19044.3930) and have discovered something else. The issue only occurs when the "extend effects to borders" option is disabled. When this option is enabled, the problem does not manifest.

**Comment by Maplespe** [comment]
Fixed, please re-download the attachment.
