### ISSUE TITLE
Opaque border to titlebar aapearing on v2.0.1

### ISSUE THREAD

**Issue by robbely** [Maplespe/DWMBlurGlass#151]
**Describe the bug**
In 2.0.0 the titlebar is completely translucent, in 2.0.1 there is an opaque border (see screenshots)

**To Reproduce**
Install 2.0.0, upgrade to 2.0.1, keep default settings but add a color to the active window titlebars (not all steps may be necessary but this is what I have tested).

**Screenshots**
![2.0.0](https://github.com/Maplespe/DWMBlurGlass/assets/79659879/16985fdb-3547-4838-8b72-0fa78e47c849)
![2.0.1](https://github.com/Maplespe/DWMBlurGlass/assets/79659879/34c05d1b-5307-47e0-a652-5c31622226b3)

With some colors eg orange, the border is even more pronounced. (I also notice it is present in the screenshots from other users in other issue posts).

**Additional information (please complete the following information):**
Windows 10 22H2.19045.3930, software version 2.0.1

**What other third-party software do you use:**
None - tested on Windows Sandbox to ensure no conflict - issue still persists.

**Comment by ALTaleX531** [comment]
![image](https://github.com/Maplespe/DWMBlurGlass/assets/105535231/d854d811-5de3-4422-877e-41ce861d437a)
Some people want to keep the borders, others like you want to remove them, that's why this option exists.

**Comment by robbely** [comment]
>  Some people want to keep the borders, others like you want to remove them, that's why this option exists.

Ahh, I had seen this option in previous versions and it made the borders thick (possibly a now resolved bug?). It works great now thank you :)

**Comment by ALTaleX531** [comment]
I was thinking of adding a new option to control whether borders are removed or not, but I realized it would be more appropriate to put it on this old option. This is a change introduced since v2.0.1 and only works for CustomBlur, it's not a bug but a switch for compatibility with 3rd party themes.
