### ISSUE TITLE
在Windows 11 23H2.22631.3007上没有产生预想的效果

### ISSUE THREAD

**Issue by SUBearH** [Maplespe/DWMBlurGlass#155]
**Describe the bug**
> A clear and concise description of what the bug is:在Windows 11 23H2.22631.3007上没有产生预想的效果，即使我尝试了更换模糊方法和模糊类型
![image](https://github.com/Maplespe/DWMBlurGlass/assets/65080584/675f01c9-4c14-41bf-9b6d-065a3b13083f)
![image](https://github.com/Maplespe/DWMBlurGlass/assets/65080584/9126c5fa-fc3b-4a42-b835-906b1c3a1c79)

 > OS Version : [e.g. Windows 11 23H2.22631.3007]
 > Software Version : [e.g. 2.0.1]

>出现的另一个情况是我为了排除问题卸载了DWMBlurGlass，再第二次开启软件尝试安装时出现以下错误
![image](https://github.com/Maplespe/DWMBlurGlass/assets/65080584/5e3c59b6-e794-4e37-8f7f-66c4bf6e7402)
而后我尝试关闭软件再次打开，它恢复了正常并且直接显示已安装，即使依旧没有任何效果

**Comment by Maplespe** [comment]
显然和其他软件有冲突，或者被阻止了，你需要自行排查一下。另外确定你安装了符号，你可以重启一下电脑试试。

**Comment by SUBearH** [comment]
> 显然和其他软件有冲突，或者被阻止了，你需要自行排查一下。另外确定你安装了符号，你可以重启一下电脑试试。

符号一直有效，重启后恢复了正常，出现了正常的效果，并且更改配置也能正常应用。

另外期待作者安排上窗口圆角和按程序/窗口自定模糊参数的功能！
