### ISSUE TITLE
选择CustomBlur->mica时的奇怪条纹

### ISSUE THREAD

**Issue by digiant** [Maplespe/DWMBlurGlass#158]
开发者你好，
选择使用dwmapi mica和customblur mica的效果有很大不同，customblur的mica有奇怪的条纹，不知是否正常。
同时启用了startallback, ExplorerBurMica(effect=4)，系统windows dev 23620，显卡是nvidia 4070s。
<img width="1185" alt="dwmapi_micaalt" src="https://github.com/Maplespe/DWMBlurGlass/assets/11805566/470e0f02-6d72-419a-99b2-b00b5f459371">
<img width="1178" alt="customblur_mica" src="https://github.com/Maplespe/DWMBlurGlass/assets/11805566/2e548df2-a4e1-4d08-9b01-6fad23bd90dd">

**Comment by Maplespe** [comment]
不要勾选"启用Aero反射效果"
