### ISSUE TITLE
Issues rules (please check before filing an issue)

### ISSUE THREAD

**Issue by Maplespe** [Maplespe/DWMBlurGlass#159]
To save your time and everyone's time, please follow the correct format for your question.

## Bug report and Feature request
**Please choose your issue template correctly and fill it out according to the template format.**
**Any new issue created from a blank issue will not be accepted and will be closed! Especially bug feedback.**

*We can't deal with them without valid information, and it's a waste of time to raise issues that are missing key information.*

## Other issues and discussions
If you have a discussion or question, we suggest you go to **[Discussions](https://github.com/Maplespe/DWMBlurGlass/discussions)** instead of creating a new issue.

**Comment by ALTaleX531** [comment]
> [!NOTE]
> You should not and do not need to open an issue in the following cases:
> 1. You are using a version of Windows that is not available in the general availability channel, you can check if your version of Windows is supported [here (Windows 11)](https://learn.microsoft.com/en-us/windows/release-health/windows11-release-information) or [here (Windows 10)](https://learn.microsoft.com/en-us/windows/release-health/release-information). 
> e.g.
> Windows Server Build 20348
> Windows 11 Build 24200
> **!!! DO NOT REPORT THIS BECAUSE THIS IS NOT A BUG !!!**
> 2. The problem you encountered cannot be solved even after uninstalling DwmBlurGlass and restarting DWM.
> e.g.
> https://github.com/Maplespe/DWMBlurGlass/issues/316
> https://github.com/Maplespe/DWMBlurGlass/issues/277
> **!!! DO NOT REPORT THIS BECAUSE THIS IS NOT A BUG OF DWMBLURGLASS !!!**
> 3. The feature you want cannot be implemented in DWM.
> e.g.
> https://github.com/Maplespe/DWMBlurGlass/issues/250
> 4. Add support for compatibility with wrongly implemented third-party mods or similar tools
> e.g.
> https://github.com/Maplespe/DWMBlurGlass/issues/267
> [WindowBlinds](https://www.stardock.com/products/windowblinds/)
> 5. You just simply want to ask something. 
> e.g.
> https://github.com/Maplespe/DWMBlurGlass/issues/132
> 
> ***We assume that you have carefully read the [README](https://github.com/Maplespe/DWMBlurGlass/blob/master/README.md) and [this comment]().***

> [!WARNING]
> Any issue that does not follow the issue template will be closed without prior notice! 
> We don't have that much time to waste on you!

> [!TIP]
When you're not sure if you should open an issue, you can try to do it in [Discussion](https://github.com/Maplespe/DWMBlurGlass/discussions).
