### ISSUE TITLE
[feature request] an option to revert to pre-1.0.2 blur

### ISSUE THREAD

**Issue by not-nullptr** [Maplespe/DWMBlurGlass#17]
hello! blur seems to be somewhat busted in the latest release, lagging behind. should this be behind an option maybe?

**Comment by Maplespe** [comment]
Restarting the computer or the dwm process will improve the situation.

**Comment by Maplespe** [comment]
Please go to #18 and download the new attachment, it should be improved and consistent with 1.0.1.
