### ISSUE TITLE
Add an option to set colours by HEX RBG Code

### ISSUE THREAD

**Issue by SnowRainySkr** [Maplespe/DWMBlurGlass#173]
希望可以在这个位置直接编辑色号来修改颜色，这样就不用转换色号和十进制RGB，更方便了~~
![image](https://github.com/Maplespe/DWMBlurGlass/assets/153981170/0e52a058-f5a8-4c7c-b518-c29594b1bad6)

**Comment by windowsxp3790** [comment]
Bump
