### ISSUE TITLE
Does this work on Windows 10 1809?

### ISSUE THREAD

**Issue by Mobitelijas** [Maplespe/DWMBlurGlass#174]
Hello.
Does DWMBlurGlass work on Windows 1809?
I'm using LTSC 2019 on a VM. I wanna see if it works?

**Comment by ALTaleX531** [comment]
![image](https://github.com/Maplespe/DWMBlurGlass/assets/105535231/05f2f861-d2d7-4671-9344-dc872d7f2a22)
Please read `readme.md` carefully and follow the issue rules.
