### ISSUE TITLE
Not Working on Windows 11 22H2 22621.3007

### ISSUE THREAD

**Issue by CnAoKip** [Maplespe/DWMBlurGlass#176]
**Describe the bug**
> 已经确定符号有效、没有其他Aero美化类软件同时运行的情况下仍无法正常显示效果。用了-loaddll选项后黑屏，然后出现一个Basic样式窗口，标题含有类似于Style not applied的文字

**To Reproduce**
> 正常运行或者-loaddll选项没有效果。

**Screenshots**

<img width="1280" alt="bug" src="https://github.com/Maplespe/DWMBlurGlass/assets/43806705/ec26627c-45ce-4aab-b475-f14c1f421df8">

**Additional information:**
 > OS Version : Windows 11 22H2 22621.3007
 > Software Version : 2.0.1

**What other third-party software do you use:**
 > 我在使用的第三方美化软件:MacType、NoMeiryoUI

**Comment by Maplespe** [comment]
无法复现 
Windows 11 22H2 22621.1702 专业版 正常
Windows 11 22H2 22621.3007 家庭版 正常

建议稍微更新一下系统

**Comment by CnAoKip** [comment]
> 无法复现 Windows 11 22H2 22621.1702 专业版 正常 Windows 11 22H2 22621.3007 家庭版 正常
> 
> 建议稍微更新一下系统

更新至22H2 22621.3155，重启后仍然无效。

**Comment by Maplespe** [comment]
你是ARM版本的系统吗，还是修改过的OEM系统?

**Comment by CnAoKip** [comment]
> 你是ARM版本的系统吗，还是修改过的OEM系统? 在纯净的版本中测试正常

原装系统。看了下你的DLL确实注入到DWM里去了。
<img width="1280" alt="dwm1" src="https://github.com/Maplespe/DWMBlurGlass/assets/43806705/52ec2143-0ac4-4b2a-ba19-44bce7a3d80c">

我的DWM部分配置是这样的
![image](https://github.com/Maplespe/DWMBlurGlass/assets/43806705/a8171a8d-2349-4f5f-be5d-abd95db2c1a5)

**Comment by CnAoKip** [comment]
> 你是ARM版本的系统吗，还是修改过的OEM系统? 在纯净的版本中测试正常

目前资源管理器无效，其他开始生效了

**Comment by jonm58** [comment]
我想问,你保存配置了吗?

**Comment by CnAoKip** [comment]
> 我想问,你保存配置了吗?

保存了 但是目前还是这样

**Comment by Maplespe** [comment]
勾选"覆盖使用DWMAPI设置的云母效果" 保存设置， 重新打开窗口就能生效

**Comment by CnAoKip** [comment]
> 勾选"覆盖使用DWMAPI设置的云母效果" 保存设置， 重新打开窗口就能生效

重新打开窗口无效，但是刚刚为explorer禁用MacType，重启并添加此程序启动项开始正常工作。应该是软件冲突。
