### ISSUE TITLE
[bug] inactive opacity applies to both inactive and active windows

### ISSUE THREAD

**Issue by not-nullptr** [Maplespe/DWMBlurGlass#18]
hi ! the "title bar blend color (active)" opacity option doesn't do anything. demonstration in the image below; the inactive color has an opacity of 0 and the active color has an opacity of 0.5 (128) but it is still fully transparent on the focused explorer window.
![vmware_p1pKacxJ2W](https://github.com/Maplespe/DWMBlurGlass/assets/62841684/fb238300-ea6d-4e40-95b9-a7c7d5c4e43b)

**Comment by NotJorrd** [comment]
as well as color

**Comment by Maplespe** [comment]
Please try this version, it fixes the problem and should also address the issue with the reflection effect.
Also the dragging speed should be improved in this version and should be consistent with 1.0.1.
[Release_x64.zip](https://github.com/Maplespe/DWMBlurGlass/files/13997320/Release_x64.zip)

**Comment by not-nullptr** [comment]
works perfectly.
