### ISSUE TITLE
Titlebar text glow like Windows 7

### ISSUE THREAD

**Issue by tyr316ter** [Maplespe/DWMBlurGlass#181]
**Describe the solution you'd like**
> Just like the description, I'd like to have the text glow like what Windows 7 did:
![RJ8za](https://github.com/Maplespe/DWMBlurGlass/assets/160259156/416ee9b2-3473-4bdc-b085-586756cf5efd)

**Your reason (tell us why we need it)**
> Just simply that will provide much better visibility for the text if the background has the same colour as the text

**Describe alternatives you've considered**
> And it should be wonderfull if we could modify the titlebar heaviler! I like centered titlebar of Windows 8 and have not found any workaround for this hehe
**Additional context**
Thank you in advance for this wonderful app, such a gem for Aeroglass lover like me since the drop of glass8.eu

**Comment by nopahc4** [comment]
> But text glow already does exist

ong

**Comment by aubymori** [comment]
This does bring up an interesting point; DWMBlurGlass does a "per-letter" glow, where the shape of the glow is affected by the shape of the letters. Windows 7 does not do this, and instead uses a nine-slice image (`TEXTGLOW` part in `DWMWindow` UXTheme class) behind the text that is not affected by the shape of the text.

**Comment by Maplespe** [comment]
DWMBlurGlass has text glow support depending on your theme.
A similar issue is #172.
