### ISSUE TITLE
Blur effect not applied during various app animations

### ISSUE THREAD

**Issue by nopahc4** [Maplespe/DWMBlurGlass#183]
> A clear and concise description of what the bug is:

When launching an app, the blur effect is not applied to the titlebar instantly, it applies after the animation finishes. Same thing happens when maximizing(not really visible on the video), restoring, restoring from taskbar animations. 

> Steps to reproduce the behavior:

Run any app like paint that shows an image that could be used as an example, pose the window (title bar) to launch behind the image, then you can see the blur is not applied immediately, it might look like not an important bug but yeah it's kinda annoying

**Screenshots**

https://github.com/Maplespe/DWMBlurGlass/assets/152728509/eb40c5d3-f125-4a59-a228-c6742aa1127f

Please excuse the image selection, I didn't have anything else on my pc that could show it the same way 

 > OS Version : Windows 10 22H2, 19045.4046
 > Software Version : 2.0.1

**What other third-party software do you use:**
 > [e.g. windhawk mods xxx]

UltraUXThemePatcher
Winaero Tweaker (no tweaks done)
Also using a custom theme which is just a copy of the default aero one but with text glow enabled

**Additional context**
In the vid you can also see a bug, when minimizing/closing the title bar becomes blue/black, I have mentioned this in #106 and it happens when I have show accent color on title bars and borders enabled in settings (without that the borders aren't the way i like them) if you'd like I can make an separate issue about it

**Comment by Maplespe** [comment]
Similar problems and why they occur were explained in #175 and #102.

**Comment by Maplespe** [comment]
Incidentally, this has been a problem with Windows for a long time.
Even windows 7 was transparent during animations, it's just that Windows 10 changed the system animation and duration, causing it to look more obvious.
![131332](https://github.com/Maplespe/DWMBlurGlass/assets/43676879/837ebc6c-206f-452a-bc4d-bd98a29d0897)

**Comment by nopahc4** [comment]
> Incidentally, this has been a problem with Windows for a long time. Even windows 7 was transparent during animations, it's just that Windows 10 changed the system animation and duration, causing it to look more obvious. ![131332](https://private-user-images.githubusercontent.com/43676879/305599266-837ebc6c-206f-452a-bc4d-bd98a29d0897.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgxNzAyNzksIm5iZiI6MTcwODE2OTk3OSwicGF0aCI6Ii80MzY3Njg3OS8zMDU1OTkyNjYtODM3ZWJjNmMtMjA2Zi00NTJhLWJjNGQtYmQ5OGEyOWQwODk3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjE3VDExMzkzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWEwMjY0YmJhMDhjZGVjMDg1NGFkYTliMmJjZjc5NjAxNmY4NDhmZWJkNjI5Y2E0ZjY4ZmRjYjA4NTk5OGRjMjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.B64QetmDDcsk50ye8AK62xKq8aH82en012oc_aeSZyE) ![131535](https://private-user-images.githubusercontent.com/43676879/305599400-32b5fc68-bffd-40fa-9e20-28851cee1c58.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgxNzAyNzksIm5iZiI6MTcwODE2OTk3OSwicGF0aCI6Ii80MzY3Njg3OS8zMDU1OTk0MDAtMzJiNWZjNjgtYmZmZC00MGZhLTllMjAtMjg4NTFjZWUxYzU4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjE3VDExMzkzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA5ZjViMWQ3OGZhMWY0NzNiODRlZDg2NzA2ZDRmOTZjODZiNjIwMzU4ODRjYTQyYzFmOWI5ZjcyNGYwMDliOGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.20fqvSKGVzwwfD9-M9pOziR728V9KHdTSzYT2m21zSc) ![131648](https://private-user-images.githubusercontent.com/43676879/305599405-ebe05eee-b2f7-46af-a678-5673f9c16957.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgxNzAyNzksIm5iZiI6MTcwODE2OTk3OSwicGF0aCI6Ii80MzY3Njg3OS8zMDU1OTk0MDUtZWJlMDVlZWUtYjJmNy00NmFmLWE2NzgtNTY3M2Y5YzE2OTU3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjE3VDExMzkzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI3MDAyZDFlMDQxNGJjNzE2YjI4YzEzNTZjZGIwMDc0MWIxMWVmNmYwZGNiMmEzMWZiMDhiZTI0MTFiMmEzMDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.XmQfgJCyPWqZV1D0X2WLqjjvP6j9XptmMCbuvMVqN4g) ![131717](https://private-user-images.githubusercontent.com/43676879/305599406-a82d488b-9861-4297-81f6-6b663528628b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgxNzAyNzksIm5iZiI6MTcwODE2OTk3OSwicGF0aCI6Ii80MzY3Njg3OS8zMDU1OTk0MDYtYTgyZDQ4OGItOTg2MS00Mjk3LTgxZjYtNmI2NjM1Mjg2MjhiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjE3VDExMzkzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM2ZWUyZjY1Y2QxMzJiODY3YmJjYWNmNTA4NWFlNWE0NmE3ODBjN2Y4NGQ0MmJmY2U3NGE1OTg1MzZlMmNlMzkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.KwrNpryshjC60YNuBFHJ1hi4RPtlVXB4FkVsNUge28A)

oh lmao I never noticed that in 7 but alr thanks
