### ISSUE TITLE
透明效果有时会消失且无法重装

### ISSUE THREAD

**Issue by win2000MEMZ** [Maplespe/DWMBlurGlass#188]
**Describe the bug**
> A clear and concise description of what the bug is:透明效果有时会消失，卸载后重装会报错

Description ....

**To Reproduce**
> Steps to reproduce the behavior:

Description ....

**Screenshots**
> If applicable, add screenshots to help explain your problem:
![屏幕截图 2024-02-19 140010](https://github.com/Maplespe/DWMBlurGlass/assets/110439586/3351038f-b591-405d-b7bd-9795e101f013)

**Additional information (please complete the following information):**
 > OS Version : [e.g. Windows 11 23H2.22631.3155]
 > Software Version : [2.0.1]

**What other third-party software do you use:AutoDarkMode, TranslucentTB
 > [e.g. windhawk mods xxx]

None

**Additional context**

**Comment by win2000MEMZ** [comment]
> **Describe the bug**
> 
> > A clear and concise description of what the bug is:透明效果有时会消失，卸载后重装会报错
> 
> Description ....
> 
> **To Reproduce**
> 
> > Steps to reproduce the behavior:
> 
> Description ....
> 
> **Screenshots**
> 
> > If applicable, add screenshots to help explain your problem:
> > ![屏幕截图 2024-02-19 140010](https://private-user-images.githubusercontent.com/110439586/305812343-3351038f-b591-405d-b7bd-9795e101f013.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgzMjMyNjYsIm5iZiI6MTcwODMyMjk2NiwicGF0aCI6Ii8xMTA0Mzk1ODYvMzA1ODEyMzQzLTMzNTEwMzhmLWI1OTEtNDA1ZC1iN2JkLTk3OTVlMTAxZjAxMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIxOVQwNjA5MjZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01MjU2YmQzOGMzNjk4ZjIzZmE5YTZhMGQ2ZjQ0OGRlNGI5YjdkOGY0YTA2MDFjODBjNjJjZTc4YjYwY2NlOGU0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.qcF7KJk3jTR-ICzWnDV3CRvZxwkUPCz5RDCQsK_LUCk)
> 
> **Additional information (please complete the following information):**
> 
> > OS Version : [e.g. Windows 11 23H2.22631.3155]
> > Software Version : [2.0.1]
> 
> **What other third-party software do you use:AutoDarkMode, TranslucentTB
> 
> > [e.g. windhawk mods xxx]
> 
> None
> 
> **Additional context** Add any other context about the problem here.

**Comment by Maplespe** [comment]
注入操作失败一般是因为被拦截
