### ISSUE TITLE
Rounded Corners (Bug)

### ISSUE THREAD

**Issue by NotJorrd** [Maplespe/DWMBlurGlass#19]
Before updating to today's update, the corners were rounded as normal, but I've noticed that if you increase the opacity the corners are there.

![image](https://github.com/Maplespe/DWMBlurGlass/assets/156122285/ba46abdb-b42f-449c-83e2-7215dcca3aac)

I've also noticed the inactive color changes both active and inactive (opacity as well)

**Comment by Maplespe** [comment]
Please go to #18 to download the attachment, this version of rounded corners should be consistent with 1.0.1.

**Comment by not-nullptr** [comment]
can confirm the posted release restores it to the old functionality (although the old functionality has the same bug)

![image](https://github.com/Maplespe/DWMBlurGlass/assets/62841684/f63aac64-a21f-486a-9771-a216bd0ece35)

**Comment by Maplespe** [comment]
Actually this one is behind the blur layer bug, which has been fixed for the color layer.
The blur layer we can't fix at the moment, including the drag delay, it's all internal to dwm blur.
