### ISSUE TITLE
Photoshop  标题栏出现问题

### ISSUE THREAD

**Issue by Banise** [Maplespe/DWMBlurGlass#196]
![image](https://github.com/Maplespe/DWMBlurGlass/assets/91298198/74a8e8aa-b8a5-4028-a8ed-ca5710c44304)
问题↑像是这样
![image](https://github.com/Maplespe/DWMBlurGlass/assets/91298198/fbbd1b51-c847-4490-8849-a9cb6f10ec95)
windows版本
![image](https://github.com/Maplespe/DWMBlurGlass/assets/91298198/3a2eaa51-ec18-4c7f-81ec-4f79a1c1f4f8)
Photoshop版本

软件版本及设置
![image](https://github.com/Maplespe/DWMBlurGlass/assets/91298198/462f3bcf-bb1d-4492-adb2-ba6f7d642ca1)
![image](https://github.com/Maplespe/DWMBlurGlass/assets/91298198/d46d3102-2385-4700-948f-62a9dc1d8f11)
![image](https://github.com/Maplespe/DWMBlurGlass/assets/91298198/e2871328-8c53-4bb3-bd16-04619b2e6a2d)

其他显示均正常

**Comment by ALTaleX531** [comment]
又是一个不看#159 直接开issue的，我们可能会迟一点再看看这是怎么回事
