### ISSUE TITLE
Since 2.0, effects do not persist after restart

### ISSUE THREAD

**Issue by cooolgamer** [Maplespe/DWMBlurGlass#199]
**Describe the bug**
> A clear and concise description of what the bug is:

After installing it, it works, but when I restart, everything is back to normal, effects are gone

**To Reproduce**
> Steps to reproduce the behavior:

Install it, restart the computer, effects will be gone

**Screenshots**
> If applicable, add screenshots to help explain your problem:

**Additional information (please complete the following information):**
 > OS Version : Windows 10 LTSC 21H2 19044.4046
 > Software Version : 2.0.1

**What other third-party software do you use:**
 > [e.g. windhawk mods xxx]

None

**Additional context**
My main user is not administrator, I use the built-in Administrator account to get admin permissions

**Comment by ALTaleX531** [comment]
View #168 .

**Comment by Umbrella-TEC** [comment]
You need to edit the task in the task scheduler. There you can specify which user to run

**Comment by cooolgamer** [comment]
> You need to edit the task in the task scheduler. There you can specify which user to run

I tried that (see how I did in the attached image) and it still doesn't work because it does that on the Administrator account and my current user doesn't get the patch
![image](https://github.com/Maplespe/DWMBlurGlass/assets/64099608/28643bb9-033e-4ed0-9477-73d7bc194bfc)

**Comment by Maplespe** [comment]
issue duplicate, temporary solution see #149.
