### ISSUE TITLE
Add an option to use Windows 10 Acrylic

### ISSUE THREAD

**Issue by emeraldongithub** [Maplespe/DWMBlurGlass#2]
This program uses ExplorerBlur, which is incredibly slow while dragging windows even with showing contents off, Acrylic on the other hand is much faster.

**Comment by Maplespe** [comment]
In fact, after Windows 10 1809 using Acrylic will result in very severe drag lag being an almost unusable state.

**Comment by windowsxp3790** [comment]
> In fact, after Windows 10 1809 using Acrylic will result in very severe drag lag being an almost unusable state.

is it still possible to implement it as an option?

**Comment by emeraldongithub** [comment]
> In fact, after Windows 10 1809 using Acrylic 

will result in very severe drag lag being an almost unusable state.

Not if you have enable contents while dragging windows off.

ExplorerBlur still lags despite having the feature off.

https://cdn.discordapp.com/attachments/1184664731664003132/1196615134441910312/2024-01-16_08-34-19.mp4?ex=65b845b0&is=65a5d0b0&hm=6094a3e3ca82a1287d94b941abf518e81367c4d2afa707996072db11f14ebb46&

**Comment by emeraldongithub** [comment]
Closed this issue because it already is acrylic apparently and i am just fucking stupid

**Comment by emeraldongithub** [comment]
![IMG_1278](https://github.com/Maplespe/DWMBlurGlass/assets/99167692/299426b7-db16-4c42-84e1-78841d3c44ba)

Nevermind. Reopening this issue.

**Comment by Maplespe** [comment]
We're using regular Blur which under normal circumstances wouldn't be a problem, whereas Acrylic causes much worse lag and is almost unusable.
I don't know why you think Acrylic is better, if you don't believe me I suggest you try a random project that uses SWCA to set up win32Acrylic.

**Comment by emeraldongithub** [comment]
> We're using regular Blur which under normal circumstances wouldn't be a problem, whereas Acrylic causes much worse lag and is almost unusable. I don't know why you think Acrylic is better, if you don't believe me I suggest you try a random project that uses SWCA to set up win32Acrylic.

ExplorerBlur has too much drag lag even if window contents are off. Acrylic does have drag but it can be fixed when turning window contents off, so it is usuable.

**Comment by emeraldongithub** [comment]
The “normal blur” you are talking about is known to have the worst drag lag if you have 5 or more windows open.

**Comment by FireCubeStudios** [comment]
> Acrylic on the other hand is much faster.
A study has confirmed this false. Please never add acrylic to this program or else I will have to stop using it
