### ISSUE TITLE
Entering and exiting fullscreen is laggy

### ISSUE THREAD

**Issue by TheInsane101** [Maplespe/DWMBlurGlass#200]
I noticed that Youtube videos played at full quality play very laggily and jankily, and it took me a bit to figure out that it was DWMBG that caused it. Below is a video of the difference, together with my device's hardware details. Is it possible for DWMBG to be optimised to use less of my device's graphics performance?

https://youtu.be/7-nTQ35_Aqc

![image](https://github.com/Maplespe/DWMBlurGlass/assets/104862146/ffb9e67d-5bd4-442e-9ff6-6daa780e6f8c)

Graphics specs:

![image](https://github.com/Maplespe/DWMBlurGlass/assets/104862146/d08bde64-1d49-4738-8b5c-fe4cc4f0f396)

**Comment by 3060PlayZ-github** [comment]
for me it works fine
