### ISSUE TITLE
软件在每次开机后失效

### ISSUE THREAD

**Issue by nexus181** [Maplespe/DWMBlurGlass#203]
**Describe the bug**
> A clear and concise description of what the bug is:

软件在每次开机后失效，而符号文件仍是下载有效状态，只有删除旧软件，打开新软件下载符号文件才能生效

**To Reproduce**
> Steps to reproduce the behavior:

安装软件设置生效，重启电脑或开机后

**Screenshots**
> If applicable, add screenshots to help explain your problem:

**Additional information (please complete the following information):**
 OS Version :  Windows 11 23H2.22635.2419
 Software Version : 2.0.1

**What other third-party software do you use:**
 > [e.g. windhawk mods xxx]

None

**Additional context**
应用放在非用户目录下，帐户具有管理员级别的权限，并且具有管理员访问权限.

**Comment by Maplespe** [comment]
问题重复，请看#149
