### ISSUE TITLE
Add a function to disable only transparency

### ISSUE THREAD

**Issue by Umbrella-TEC** [Maplespe/DWMBlurGlass#204]
**Describe the solution you'd like**
> Add a function to disable only transparency. Save other effects (text, window buttons, etc.)

**Your reason (tell us why we need it)**
> Without DWMBlurGlass, window control buttons do not look the same as in Windows 7, and there is no way to implement glowing text using themes. Transparency needs to be disabled due to DWM performance issues. High CPU load when multiple windows are stacked on top of each other

**Describe alternatives you've considered**
> There are no alternative solutions. Editing the theme style did not solve the problem

**Additional context**
A proposal to add disabling transparency through a setting in Windows while preserving other window effects.
![2024-02-29 23_24_18-1022  Работает  - Oracle VM VirtualBox](https://github.com/Maplespe/DWMBlurGlass/assets/159888040/7845e456-6820-487c-91b0-a1beccc3124e)

**Comment by Maplespe** [comment]
You should be able to choose the SystemBackdrop blur method, which is an API for win11 and has no effect in win10, but the glowing text should remain.

**Comment by Umbrella-TEC** [comment]
I use Windows 10 22h2

**Comment by Maplespe** [comment]
What I mean by that is that it is a win11 API and will not have any blurring effect when used on win10. That means it's equivalent to turning off blur on win10.

**Comment by Umbrella-TEC** [comment]
I tried SystemBackdrop, unfortunately it doesn’t affect the buttons

**Comment by Umbrella-TEC** [comment]
> you can use a windhawk mod for this, i'll send it to you if ur interested
I'm not currently considering implementing windhawk into my OS.

**Comment by Umbrella-TEC** [comment]
Installing another program for the sake of this is a questionable decision. I try to keep the performance as in Windows 7

**Comment by arukateru** [comment]
> Installing another program for the sake of this is a questionable decision. I try to keep the performance as in Windows 7

Windhawk has basically 0 performance hit, it uses less than 0.01% of the CPU
