### ISSUE TITLE
全屏应用之后出现一种奇怪的半透明外观

### ISSUE THREAD

**Issue by Glow1134** [Maplespe/DWMBlurGlass#207]
**Describe the bug**
> A clear and concise description of what the bug is:

全屏应用之后出现一种奇怪的半透明外观

**To Reproduce**
> Steps to reproduce the behavior:

全屏，目前发现的应用有资源管理器，Chrome，v2rayN

**Screenshots**
> If applicable, add screenshots to help explain your problem:
![image](https://github.com/Maplespe/DWMBlurGlass/assets/109339468/7ca184cb-fd04-4eb3-894c-4d34e9a7433e)

**Additional information (please complete the following information):**
 > OS Version : Windows 11 23H2.22631.3235
 > Software Version : 2.0.1

**What other third-party software do you use:**
 > [e.g. windhawk mods xxx]

None

**Additional context**

**Comment by Maplespe** [comment]
与 #103 重复
