### ISSUE TITLE
Effect doesnt work correctly in some situations

### ISSUE THREAD

**Issue by npc863** [Maplespe/DWMBlurGlass#208]
**Describe the bug**
> A clear and concise description of what the bug is:
It doesnt work correctly, especially when i move the windows to the edge of open in full screen mode, i can see the icon or wallpaper,... behind

**To Reproduce**
> Steps to reproduce the behavior:
i dont know

Description ....

**Screenshots**
> If applicable, add screenshots to help explain your problem:
here is some of my screenshot:
![bug1](https://github.com/Maplespe/DWMBlurGlass/assets/160253879/2ab0b8f8-72b7-48c1-b5e5-5446eb459de7)
![bug2](https://github.com/Maplespe/DWMBlurGlass/assets/160253879/72d0b43f-063c-4d4f-a476-2eae247624f7)
![bug3](https://github.com/Maplespe/DWMBlurGlass/assets/160253879/c745e064-5b5b-4e26-aaa5-f8945e5f7225)
![bug4](https://github.com/Maplespe/DWMBlurGlass/assets/160253879/a075a2ba-8c1f-4835-87a7-1df2ca9b30d7)

**Additional information (please complete the following information):**
my OS: Windows 11 22H2.22621.2861
Software Version : 2.0.1

**What other third-party software do you use:**
 > i use explorerblurmica, explorertool and some 3rd themes downloaded from niivu

None

**Additional context**
Hope you can fix this

**Comment by Maplespe** [comment]
Duplicated from #207 #103
