### ISSUE TITLE
Not work in Windows 11 Workstation Pro 23H2 22635.2486

### ISSUE THREAD

**Issue by selandiaartouch** [Maplespe/DWMBlurGlass#209]
**Describe the bug**
> A clear and concise description of what the bug is:

When following the steps outlined in the video tutorial precisely, the software fails to function on Windows operating systems.

**To Reproduce**
> Steps to reproduce the behavior:

1. Download the files from GitHub.
2. Unzip the files to the "tool" folder on drive D.
3. Download symbol files.
4. In the downloaded symbol files, check effect settings 1, 3, and 5.
5. Choose "aero" in advanced settings.
6. Install the downloaded files.
7. Open File Explorer.
8. Find that there is no effect.

**Screenshots**
> If applicable, add screenshots to help explain your problem:
![屏幕截图 2024-03-07 135037](https://github.com/Maplespe/DWMBlurGlass/assets/131914944/c291d655-5e3b-428d-8e32-8edd1856245b)
![屏幕截图 2024-03-07 135132](https://github.com/Maplespe/DWMBlurGlass/assets/131914944/c67b0976-bd76-444b-8754-421838a6091d)

**Additional information (please complete the following information):**
 OS Version :  Windows 11 23H2.22635.2486
 Software Version : 2.0.1

**What other third-party software do you use:**
 Start11

**Additional context**
Dark mode or light mode has no effect.

**Comment by Maplespe** [comment]
显然你没有仔细看完视频，如果要覆盖云母效果你必须勾选"覆盖DWMAPI设置的云母效果(win11)"

**Comment by selandiaartouch** [comment]
@Maplespe 很显然你没有仔细看我的issue，我勾选过了，也点了保存配置，只是因为它没有生效我就取消了勾选，新截图在这里，我将尝试重启电脑，如果有效果我将会关闭
![屏幕截图 2024-03-07 141335](https://github.com/Maplespe/DWMBlurGlass/assets/131914944/a995ce4a-cd2b-45a5-9922-bf074431745a)

**Comment by Maplespe** [comment]
刚看到你是预览版系统，我在视频简介还有ReadMe写了，不保证预览版有效果，只保证正式版的支持。
但你也可以选择其他的模糊方法试试，比如OldBlur SystemBackdrop。
> Supported as low as Windows 10 2004 and as high as the latest version of Windows 11 (Some blurring methods are not supported in the preview version).

**Comment by selandiaartouch** [comment]
@Maplespe 重启电脑后软件依然没有效果，重新下载安装并配置了一遍start11和你的软件，目前已经正常使用，之前不生效可能是电脑连续运行时间过长导致的累积bug。非常好软件，让我重回Vista
