### ISSUE TITLE
Can't use the app, not even installing

### ISSUE THREAD

**Issue by Olafcio1** [Maplespe/DWMBlurGlass#211]
**Describe the bug**
> A clear and concise description of what the bug is:

The app just doesn't work for me. After downloading the release, and moving the "Release" dir from the zip file into C:\Program Files\DWMBlurGlass directory (which I created), everything's great - until I run the DWMBlurGlass.exe file, and it stops the work.
I mean, the app stops responding. Can't do anything in it - it just.. stops responding. And its 50% transparent.

I've attached the screenshot, of what I am seeing, when I launch the app, in the "Screenshots" section below.

**To Reproduce**
> Steps to reproduce the behavior:

I don't really know. I can provide you the programs I've installed, which change the explorer - I did it in the section below.
**NOTE:** One (or two) times, when I ran DWMBlurGlass.exe, I could click at the checkboxes (and the app seemed to catch the mouse events), but now it just doesn't work. I don't know if the problem is clicking the Install button, or how long is the app run. It's really weird.

Yep, I checked if all the files from the .zip archive are moved into the program path (C:\Program Files\DWMBlurGlass\Release). Pls help me with this bug, cuz I wanna have fancy pc xD

**Screenshots**
> If applicable, add screenshots to help explain your problem:
_The background below the app isn't important, other program on my pc._
![image](https://github.com/Maplespe/DWMBlurGlass/assets/75330538/a4f92cee-6126-491d-9170-50d46764e31b)
![image](https://github.com/Maplespe/DWMBlurGlass/assets/75330538/89aeff04-baf6-44e8-b826-08666959d3aa)

**Additional information (please complete the following information):**
 > OS Version : Windows 10 Pro 22H2 - OS Build 19045.2486 (checked in winver.exe)
 > Software Version : 2.0.1

**What other third-party software do you use:**
Modifying Explorer:
 > Open-Shell Menu v4.4.170
 > TranslucentFlyouts v3.0.0 (installed through translucentflyoutsconfig)
 > Windhawk v1.4.1 (only notepad-dark-mode mod from the official store)
 > TranslucentTB (idk which version, from ms store)

And that's it. **Also, I had ExplorerPatcher installed** long time ago, but uninstalled it then.

Other stuff:
 > Adobe Photoshop 2022, illustrator 2022, after effects 2022, animate 2021
 > windows software development kit (idk what version but its REALLY big, its 2 GB)
 > postgresql 15 (server)
 > 4 different .net SDKs
 > vmware workstation
 > powertoys (preview) x64
 > pichon (icons8)
 > openshot video editor 2.6.1
 > mysql server 8.0
 > voicemod
 > go programming language amd64 go1.18
 > ms azure powershell - april 2018
 > twitch (outdated)
 > lunar client
 > nicepage 4.12.5
 > powershell 7.2.8.0-x64
 > vs code (user)
 > uxp webview support (smth from adobe, i dont really know)
 > eclipse temurin jdk with hotspot 16.0.2+7 (x64) (some java "distribution" lets say)
 > ms onedrive
 > eclipse temurin jdk with hotspot 18.0.2+9 (x64)
 > mcreator 2022.1
 > java(tm) se dev kit 17.0.1 (x64)
 > PMB (sony corpo)
 > ipfs desktop 0.17.0
 > vmware vcenter converter standalone
 > git bash
 > proton vpn
 > ms sql server 2019 localdb
 > feather launcher
 > mysql shell 8.0.30
 > epic online services
 > avoid (discord game)
 > anydo 5.0.12
 > firefox (x64 pl)
 > paint.net (installed with .msi)
 > epic games
 > ms windows desktop runtime 3.1.32 (x64)
 > ms windows desktop runtime 6.0.13 (x86)
 > pickcrafter (discord game)
 > discord rpc maker 2.1.1
 > wireshark 3.6.6 64-bit
 > ms sql server 2019 setup (eng)
 > dll injector 1.2.6
 > python 3.11.7 (64-bit)
 > free download manager
 > eclipse temurin jre with hotspot 17.0.4+8 (x64)
 > github desktop
 > atlauncher
 > audacity 3.0.5
 > python 3.10.4 (64-bit)
 > python 3.7.0 (32-bit)
 > authy desktop
 > discord canary
 > node.js
 > ms azure lbiraries for .net - v2.9
 > discord
 > sublime text
 > iis 10.0 express
 > pivot animator v5 version 5.2.5
 > adobe shockwave player 12.2
 > java 8 update 341 (64-bit)
 > filezilla 3.62.2
 > wsl update
 > universal minecraft editor v1.7.1
 > intel c++ redistributables on intel 64
 > universal minecraft converter v1.5.5
 > ms asp.net core 6.0.13 - shared framework
 > ms visual c++ 2013 x64
 > ms visual c++ 2012 x64
 > ms visual c++ 2015-2022 x64
 > ms visual c++ 2015-2022 x86
 > ms visual c++ 2012 (x86)
 > ms visual c++ 2013 (x86)
 > keepass
 > liquidlauncher
 > ms visual c++ 2010 x64
 > ms visual c++ 2008 x64
 > ms visual c++ 2008 x64
 > ms azure authoring tools v2.9.7
 > modrinth
 > ms visual c++ 2010 x86
 > ms xna framework 4.0 refresh
 > ms visual c++ 2008 x86
 > zoom
 > vbsedit 32-bit
 > vbsedit
 > ms visual c++ 2008 x86
 > ms visual c++ 2008 x86
 > resource hacker v5.1.7
 > ms sql server 2019 t-sql lang serv
 > winaero tweaker
 > wireguard
 > mysql installer - community
 > ms odbc driver 17 for sql serv
 > ms sql server 2012 native client
 > irfanview 4.60 x64
 > ms visual c++ 2005 x64
 > wondershare helper compact 2.6.0
 > openvpn 2.5.7-l602 amd64
 > process hecker 2.39 (r124)
 > ms visual c++ 2005
 > ms system crl types for sql server 2019
 > cmclient launcher v1.8.0
 > msxml 4.0 sp3 parser
 > greenshot 1.2.10.6
 > old classic calc for win11 and win10
 > python launcher
 > minecraft launcher
 > python launcher
 > ms update health tools
 > update for win10 x64 syss (kb50...
 > msgameinput
 > mozilla maintance service
 > ms .net sdk 6.0.300 x64 from vs studio
 > win sdk addon
 > winamp detector plug-in
 > ms visual c++ 2013 x86
 > tp-link wireless adapter wps tool and driver
 > ms visual c++ 2013 x64
 > ms visual c++ 2013 x64
 > heroku
 > vs build tools 2019
 > winamp
 > ubisoft connect
 > steam
 > rainmeter
 > overflow
 > obs
 > npcap
 > nmap
 > ms edge webview2 runtime
 > msedge beta
 > msedge
 > megasync
 > logmein hamachi
 > install creator
 > ms ieak 6
 > chrome
 > effect house (tiktok)
 > adobe genuine services
 > vs community 2022
 > nvidia geforce now 2.0.55.119
 > roblox studio (user)
 > roblox player (user)
 > google drive
 > other chrome apps (from the browser only)
 > winlaunch
 > vivaldi
 > jetbrains toolbox
 > curseforge
 > msedge canary
 > capcut
 > nvidia driver shiiiiiiiiiiiit not wanna type it here cuz i am fucking lazy
 > ms visual studio installer
 > winrar 6.11 x64
 > win 7 games for win10 and win8
 > vlc
 > forager (game)
 > stick fight: the game (game)
 > steam 360 video player
 > brick rigs( game)
 > team fortress 2
 > wallpaper engine
 > stardew valley (game)
 > astronner (game)
 > geometry trash (game)
 > terratech (game)
 > onearmed cook (game)
 > stumble guys (game)
 > tmodloader (game)
 > terraria (game)
 > flowscape (game)
 > ms 365 apps for enterprise - en-us
 > ms visual j# 2.0 package - se (...
 > ms sql server 2019 x64
 > ms azure compute emulator v2.9.7
 > autohotkey 1.1.33.09 (no scripts)

**Additional context**
I don't really know about the problem. I don't have time to test it on a VM, because I am lazy  and have stuff to do. I've provided you all information I can.

oh fuck when i was typing the programs it seems like i didnt type the word "redistributable" at every single fucking library in these visual c++ redistributables sooooo forgive me xd
also if i didnt type it in the list, i use process hacker, so if you want i can check for some shit with it - i mean what is it doing or smth (but i think i can do nothing with that cuz i fucking dont know c or c++ or j# XD)

**EDIT:**
I have also installed TranslucentTB from ms store now - as of 12:15 pm

**Comment by Olafcio1** [comment]
Also if you read this issue till here, pls use more english in this whole project, cuz I am polish and I dont understand your 色如发生软件提供i哦对日军体哦东软集团 chinese language. And thats some random chars from chinese. So please use english.

**Comment by ALTaleX531** [comment]
I think you can use Task Manager to create a memory dump file for the not responding DwmBlurGlass GUI so we can figure out what's going on. These random characters don't seem to make any sense as they are not included in this program as far as I know.

**Comment by Olafcio1** [comment]
> I think you can use Task Manager to create a memory dump file for the not responding DwmBlurGlass GUI so we can figure out what's going on. These random characters don't seem to make any sense as they are not included in this program as far as I know.

By that message I meant that i just dont understand chinese, this random char was a joke just to tell you that a lot of places in dwmblurglass project **on github** you have chinese.

Anyway, ALTaleX531 asked me a hour ago to create a memory dump in task manager. Okay, so task manager lags for me, but i have process hacker so i've created an exe dump - which is probably the same. Here you go:

> _...I had to upload it on google drive because its 223 mb and github doesnt handle such big files._
> https://drive.google.com/file/d/1Qi7SSkJ7P7UcjDMRRzkD8t47X0SzXtSS/view?usp=sharing

**Comment by Olafcio1** [comment]
> I'm guessing you're using an NVIDIA graphics processor, which seems to have something to do with drivers, if so check out #163.

I checked it out, and it also may be because of the fact, that I haven't restarted my system for probably 2 weeks or longer (i am putting it to sleep all the time). If it's a very high chance, I may trying restarting (i have a lot of shit open and not wanna relaunch it every time).
