### ISSUE TITLE
Blend color isn't exactly accurate to Windows 7

### ISSUE THREAD

**Issue by TorutheRedFox** [Maplespe/DWMBlurGlass#212]
**Describe the bug**
> A clear and concise description of what the bug is:

The tint seems to be multiplicative on Windows 7, leaving blacks as black. This is not the case in DWMBlurGlass

**To Reproduce**
> Steps to reproduce the behavior:

Put a window over a black background. The window's frame background should also be black but isn't.

**Comment by TorutheRedFox** [comment]
![image](https://github.com/Maplespe/DWMBlurGlass/assets/15708278/9b3f58f9-4f0e-47e5-b96a-e13454c230cd)

**Comment by TorutheRedFox** [comment]
note: i reduced the opacity from what it should be to reduce the black crushing effect, hence the desaturated color on the white

**Comment by ALTaleX531** [comment]
You should discuss it in #195 instead of creating a new issue. the Aero recipe is indeed not accurate enough, but it is not a bug.
