### ISSUE TITLE
dwm.exe restart breaks transparency

### ISSUE THREAD

**Issue by robbely** [Maplespe/DWMBlurGlass#213]
**Describe the bug**
If dwm.exe crashes ore restarts for any reason, I'm finding that the trasnparency effects stop (as though DWMBlurGlass isn't installed). Clicking "uninstall" then "install" in the app fixes it (till next time).

**To Reproduce**
Some imstallers or graphics apps will do this but you can reproduce by closing dwm.exe within task manager (it automatically restarts, but with the bug).

**Additional information (please complete the following information):**
 > OS Version : Windows 10 22H2 19045.4046
 > Software Version : 2.0.1

**Comment by SKCro** [comment]
This is because DWMBlurGlass doesn't automatically reinject itself whenever DWM is closed and reopened. You must reinstall it manually.
A feature like this has been requested (see #40) but I don't think it's gone anywhere (since DWM crashes are rare now and manually closing DWM is also rare).

**Comment by arukateru** [comment]
You can just edit the scheduled task by adding a trigger for when DWM restarts (event log)

**Comment by robbely** [comment]
> You can just edit the scheduled task by adding a trigger for when DWM restarts (event log)

That worked - thank you. I used event 9027.
