### ISSUE TITLE
Add white glow under the title

### ISSUE THREAD

**Issue by KaiHuaDou** [Maplespe/DWMBlurGlass#215]
To ensure the visibility of the title text, Windows 7 add a small white glow under the title bar.
But I can't see it on the Aero blur mode, it will great if can add it.

**Comment by Maplespe** [comment]
Duplicates with #181, #172.
DWMBlurGlass itself has text glowing support, but it depends on your theme, DWMBlurGlass will enable glowing if your theme properties require it.
