### ISSUE TITLE
Window Border Overly Thick

### ISSUE THREAD

**Issue by D-Maxwell** [Maplespe/DWMBlurGlass#216]
**Describe the bug**
It would seem that some windows' borders are made thicker than they should be (this sometimes includes the bottom border, but not always oddly enough, might be because of something else then), which the blur effect is then applied to, and leads to some subtly odd renders, such as that of this very window.

**To Reproduce**
```ini
[config]
applyglobal=false
extendBorder=true
reflection=false
oldBtnHeight=false
customAmount=true
blurAmount=12.000000
customBlurAmount=12.000000
luminosityOpacity=0.650000
activeTextColor=4278190080
inactiveTextColor=4290032820
activeTextColorDark=4294967295
inactiveTextColorDark=4290032820
activeBlendColor=1694498815
inactiveBlendColor=1694498815
activeBlendColorDark=1677721600
inactiveBlendColorDark=1677721600
blurMethod=1
effectType=0
```

**Screenshots**

![image](https://github.com/Maplespe/DWMBlurGlass/assets/98100481/31c0e698-33ba-4a56-a21b-9aa3dcc20197)
![image](https://github.com/Maplespe/DWMBlurGlass/assets/98100481/1aef3ecf-d579-41fd-96c0-aee4d4cab2b2)

**Additional information (please complete the following information):**
 > OS Version : Windows 10 Pro 22H2 19045.2788
 > Software Version : 1.5.1

**What other third-party software do you use:**
 > DWMBlurGlass
 > MicaForEveryone (unaffected)

**Additional context**
This doesn't seem to be tied to the `Effects extend to borders (win10)` option, as it remains this way regardless of its state.

**Comment by D-Maxwell** [comment]
I may add that this was already an issue in ~0.4.x, which I used to use on this install.

**Comment by Maplespe** [comment]
I think it has something to do with the application you're using, which incorrectly extends the window border or uses DwmExtendFrameIntoClientArea.
Also I'm not sure what the version number you provided refers to, DWMBlurGlass never had such a version number.

**Comment by D-Maxwell** [comment]
> I think it has something to do with the application you're using, which incorrectly extends the window border or uses DwmExtendFrameIntoClientArea. Also I'm not sure what the version number you provided refers to, DWMBlurGlass never had such a version number.

Well I'm not sure how I even acquired that build, but I definitely do recall it stating 0.4.x or 0.5.x.

Perhaps that was glass8 ? I don't recall it looking like that though.
