### ISSUE TITLE
Quickly switching between custom color/blur config pre sets

### ISSUE THREAD

**Issue by windowsxp3790** [Maplespe/DWMBlurGlass#218]
**Describe the solution you'd like**
> A clear and concise description of what you want to happen.
I would like a feature where we can save custom color or blur combinations to quickly switch between via the GUI
**Your reason (tell us why we need it)**
> Briefly describe your reasons for wanting to do this.
For people who like to quickly tweak the look of their desktop with minimal effort and not have to change every single slider or options
**Describe alternatives you've considered**
> A clear and concise description of any alternative solutions or features you've considered.

**Comment by Maplespe** [comment]
Please use the import and export functions on the "Config" page to quickly switch or save configuration files.
