### ISSUE TITLE
Title bar shows default color during close animation

### ISSUE THREAD

**Issue by funn-hue** [Maplespe/DWMBlurGlass#220]
**Describe the bug**
> A clear and concise description of what the bug is:

When closing any app the titlebar defaults to the color set by the OS (white default and purple when I turn on show accent color on titlebar and borders in windows settings).
Just in case I didn't explain properly, the issue is the title bar defaulting to the current title bar color during the close animation, ignoring the settings in the GUI

Only happens with extend effect to borders turned off

**To Reproduce**
> Steps to reproduce the behavior:

Disable extend effect to borders, apply default Windows 10 theme, close  some apps (with DWMBG installed), after like 3 tries check the "show accent color on titlebars and borders" in settings and also check the result.

**Screenshots**
> If applicable, add screenshots to help explain your problem:

extend effect to borders off
![7Q6pdlPTgz](https://github.com/Maplespe/DWMBlurGlass/assets/152728509/e1369068-5f9d-45fe-8666-2a1d9c0dffa6)

extend effect to borders on (normal behavior with this on, but then you lose the default black borders, but i want them so yeah)
![tQuK4XU2Gm](https://github.com/Maplespe/DWMBlurGlass/assets/152728509/f1cf7ec9-9dd8-4165-8acd-5e486da40758)

**Additional information (please complete the following information):**
 > OS Version : Windows 10 22H2 19045.4170
 > Software Version : 2.0.1

**What other third-party software do you use:**
 > [e.g. windhawk mods xxx]

None

**Additional context**
-

**Comment by TorutheRedFox** [comment]
glass texture also just gets fitted to the window's borders instead of doing the parallax thing it's supposed to and the close icon disappears during the animation

**Comment by funn-hue** [comment]
> glass texture also just gets fitted to the window's borders instead of doing the parallax thing it's supposed to and the close icon disappears during the animation

The first issue could be caused by your theme having the "SQUEEGEREFLECTIONMAP" replaced with the glass texture, that's why it's not a really good idea to bake it right into the theme.  Second one is a windows thing (?)
