### ISSUE TITLE
DWMBlurGlass refuses to work after restart

### ISSUE THREAD

**Issue by Kenst1092** [Maplespe/DWMBlurGlass#229]
**Describe the bug**
> A clear and concise description of what the bug is:

DWMBlurGlass, upon either a restart or shutdown, will not function upon bootup. Titlebars and windows remain the same as without DWMBlurGlass running

**To Reproduce**
> Steps to reproduce the behavior:

Install/Run DWMBlurGlass on default settings, restart computer and logon.

**Screenshots**
> If applicable, add screenshots to help explain your problem:

**Additional information (please complete the following information):**
 > OS Version : [e.g. Windows 11 23H2.22631.3085]
 > Software Version : [e.g. 2.0.1]

OS Version: Windows 11 Enterprise 23H2 22631.3296
Software Version: 2.0.1

**What other third-party software do you use:**
 > [e.g. windhawk mods xxx]

Rectify11 v3.1 that uses:

- MicaForEveryone 1.3.0.0
- ExplorerFrame
- SecureUxTheme v2.2.0

TranslucentFlyouts v3.1.1
TranslucentTB v2024.1.0.0
ExplorerPatcher v22621.3296.64.1

**Additional context**
Trying to make DWMBG work through `DWMBlurGlass.exe loaddll` does nothing.

**Comment by Kenst1092** [comment]
Fixed my own problem:

- Add a few seconds' delay to DWMBG in Task Scheduler, and logout-login. Would be a good idea to implement that when installing DWMBG for future reference

**Comment by Skyyblaze** [comment]
The delay fix used to work for me but as of updating to 2.1.1 it doesn't anymore. I added a 30 second delay to the DWMBlurGlass_Extend task:

![grafik](https://github.com/Maplespe/DWMBlurGlass/assets/22203339/f1957f36-f828-457c-b430-676f5021313c)
