### ISSUE TITLE
[feature request] re-implementation of glow-related dwm functions

### ISSUE THREAD

**Issue by not-nullptr** [Maplespe/DWMBlurGlass#23]
hello! just to preface, i do realise that this is entirely out of the scope of this project. with that being said, nobody else has done it and i think the existence of the "windows 7 style buttons" option justifies this issue. with that being said, the re-implementation of button glow on hover/press would be a really cool feature. the first screenshot is on windows 7 sp1 and the second screenshot is windows 10 22h2 using dwmblurglass:

![image](https://github.com/Maplespe/DWMBlurGlass/assets/62841684/eace7464-13e8-49e7-936a-7dbf8facf4f4)
![image](https://github.com/Maplespe/DWMBlurGlass/assets/62841684/77cf3443-099b-4875-95ce-293fbe308686)

i think this falls within the same sort of bounds as #5 because the glow effects are included in the third party theme installed on the computer. thank you for your time ! :]

**Comment by Maplespe** [comment]
Microsoft should have removed the related functionality from dwm, there is no ready way to do it. Re-implementing it could be very difficult.

**Comment by not-nullptr** [comment]
i'm not very experienced with lower level programming so i wouldn't be of much help, but as far as im aware, the effect is really only just reading the glow effect from the atlas (dwm doesnt generate it, its a bitmap) and then displaying it. unless that's difficult to do, the hardest part would probably be the fading behaviour

![image](https://github.com/Maplespe/DWMBlurGlass/assets/62841684/d5f6056e-c8a5-4cf0-abaa-88291bd6c03d)

**Comment by nopahc4** [comment]
> i'm not very experienced with lower level programming so i wouldn't be of much help, but as far as im aware, the effect is really only just reading the glow effect from the atlas (dwm doesnt generate it, its a bitmap) and then displaying it. unless that's difficult to do, the hardest part would probably be the fading behaviour
> 
> ![image](https://private-user-images.githubusercontent.com/62841684/298302900-d5f6056e-c8a5-4cf0-abaa-88291bd6c03d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU4MjQ1NzYsIm5iZiI6MTcwNTgyNDI3NiwicGF0aCI6Ii82Mjg0MTY4NC8yOTgzMDI5MDAtZDVmNjA1NmUtYzhhNS00Y2YwLWFiYWEtODgyOTFiZDZjMDNkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTIxVDA4MDQzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYzMmE2NDM2MDAxN2M1MjY0NGU2NDVkYTAxNGIyZTBjZDIzN2VhZDRlODMxYmZiODcxMTQ3ZDU4NzgzNGNmNmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.LBTbWxgLn3RPu0PoWy7qpwWU5kHmSzBC9FIp9EL4x8o)

correct, it seems to read that from the atlas, i might create a windows 8.1 vm rn and check if it wasnt deleted from dwm, because i know that the 8.1 msstyle still has the class for the close button glow

**Comment by not-nullptr** [comment]
any updates on this? with 2.0.0 bringing the most accurate aero shader (even better than glass8 lol) to windows 10, it'd be a shame to see something like button glow be ignored

**Comment by Maplespe** [comment]
Honestly, in itself, the original purpose of our program was to implement the background effect only, any other features responsible would have been out of our scope of work, and the resizing of win7 buttons was just out of convenience.
Our program is not working exclusively for Win7 effects only, aero is just a part of it, we are also responsible for Acrylic, Mica and other Fluent Design.
We don't have so much energy to maintain so many requests and features, if everyone makes a request we have to fulfill it immediately then I don't think I need to open source myself anymore, we are doing unpaid work and are not obligated to necessarily fulfill certain content.
I hope you don't get the wrong idea, this program was not created to restore all the features of Win7 1:1.
We have done too much work on it, and not replying doesn't mean we haven't thought about it, just not at the right time.
I hope you can understand and stay patient, thanks.

**Comment by not-nullptr** [comment]
leaving an issue stale gives the impression that it hasn't been read. ofc this project isn't for anything more than blur, if u don't want to re-add glow support from the msstyles that's up to you

**Comment by Maplespe** [comment]
What theme are you using? I didn't find a Part or Class for the glow button in win10's msstyle.

**Comment by not-nullptr** [comment]
> What theme are you using? I didn't find a Part or Class for the glow button in win10's msstyle. In win7 msstyle has the class CLOSEBUTTONGLOW(Class:202,Part11). But I don't find that class in win10's msstyle, it seems to have been completely removed from msstyle.

yup, windows 10 had no glow, which is why the support was dropped from dwm

**Comment by nopahc4** [comment]
> > > What theme are you using? I didn't find a Part or Class for the glow button in win10's msstyle. In win7 msstyle has the class CLOSEBUTTONGLOW(Class:202,Part11). But I don't find that class in win10's msstyle, it seems to have been completely removed from msstyle.
> > 
> > 
> > yup, windows 10 had no glow, which is why the support was dropped from dwm
> 
> What about in the windows setup 1st phase? The glow still works on those buttons

what

**Comment by jonm58** [comment]
> > > What theme are you using? I didn't find a Part or Class for the glow button in win10's msstyle. In win7 msstyle has the class CLOSEBUTTONGLOW(Class:202,Part11). But I don't find that class in win10's msstyle, it seems to have been completely removed from msstyle.
> > 
> > 
> > yup, windows 10 had no glow, which is why the support was dropped from dwm
> 
> What about in the windows setup 1st phase? The glow still works on those buttons

?

**Comment by Maplespe** [comment]
I've posted a test version implementing this feature in #282, so you can try it out.

**Comment by not-nullptr** [comment]
WE'RE SO BACK

**Comment by Xamtastic1** [comment]
Are you guys remaking aero glass for windows 11 or something
If so I would do anything to have it
