### ISSUE TITLE
Reflection image moves in opposite direction

### ISSUE THREAD

**Issue by TheInsane101** [Maplespe/DWMBlurGlass#230]
**Describe the bug**

I tried out the experimental 2.1 beta and everything is fine except for the reflection image, which now moves in the x-direction opposite to where you're moving your window.

**How to replicate**

Install the 2.1 beta that has just been released, select CustomBlur, Aero, enable the reflection and then watch the reflection as you move a window along the x-axis.

**Screenshots**

https://github.com/Maplespe/DWMBlurGlass/assets/104862146/f4cebf1c-ad5d-434b-8c06-c0ff95331e2e

**Additional information (please complete the following information):**
 > OS Version : Windows 10 22H2
 > Software Version : 2.1

**What other third-party software do you use:**

None

**Additional context**

**Comment by aubymori** [comment]
> I checked against my Windows 7 install, this seems to be the correct behavior.

No, I don't think it is.

https://github.com/Maplespe/DWMBlurGlass/assets/44238627/46370b4f-83e7-4535-83d4-2d93e5853c3a
