### ISSUE TITLE
ColorBalance (originally PrimaryBalance) completely broken since AcrylicEverywhere (and now on 2.1.0)

### ISSUE THREAD

**Issue by kfh83** [Maplespe/DWMBlurGlass#231]
**Describe the bug**
When i initially PR'd my changes, this is how PrimaryBalance (now ColorBalance) looked:
![image](https://github.com/Maplespe/DWMBlurGlass/assets/85626296/a0b4adf5-0b77-4a3c-a7aa-b7ec08d32dee)
This is 0.08 (the same as the default config on 2.1.0), you can see a slight hint of coloring. When you turn it up to 1.0, the window would be completely opaque:
![image](https://github.com/Maplespe/DWMBlurGlass/assets/85626296/b7bcd8d7-dc8e-4e5e-b39b-ffe9ef71dc3d)
And when inactive, it would be 40% opacity:
![image](https://github.com/Maplespe/DWMBlurGlass/assets/85626296/c19596ed-fcb5-4c85-9e7c-5bcab15d2df3)

However, it seems like with the latest update (and this seems to have been happening since my updates got ported back to AcrylicEverywhere), this effect is completely gone:
![image](https://github.com/Maplespe/DWMBlurGlass/assets/85626296/83db4a3a-c772-485e-b635-b6369b037e1d)
No matter what value you put, this will always be completely transparent.
![image](https://github.com/Maplespe/DWMBlurGlass/assets/85626296/c6dc4ccb-e7a7-4509-81dc-8f0ea33ce26b)

**To Reproduce**

Set any value in config.ini for ColorBalance...

**Screenshots**

All in the bug description

**Additional information (please complete the following information):**
 > OS Version : [e.g. Windows 11 23H2.22631.3085]
 > Software Version : [e.g. 2.0.1]

OS Version: Windows 10 21H2 IoT LTSC (19044.1288)

**What other third-party software do you use:**
 > [e.g. windhawk mods xxx]

AWM, although this bug happens with Windhawk AND AWM disabled.

**Additional context**
This is probably due to CompositeEffect being broken. Consider checking.

**Comment by ALTaleX531** [comment]
Got it. Please forgive me for making such a cheap mistake.

**Comment by lucassilvas1** [comment]
@kfh83 , this is unrelated, but would you mind providing a link to the theme/msstyles you're using? I'm using Aero10, but it seems like it's missing some aero effects

Mine:
![image](https://github.com/Maplespe/DWMBlurGlass/assets/52336985/f9d23e99-61cc-454f-836e-83b7d444d4f5)

Actual W7 Run dialog:
![image](https://github.com/Maplespe/DWMBlurGlass/assets/52336985/8eddbaa9-5520-42df-9187-e0ca3ea290f9)

**Comment by lucassilvas1** [comment]
> Make sure you're using an updated version of Aero10 and use the shiny variant

That was the issue, I didn't know about that's what "shiny" meant, I was using the other variant. Thanks.

**Comment by lucassilvas1** [comment]
> Make sure you're using an updated version of Aero10 and use the shiny variant

Sorry to bother again, do you use any Firefox skin to get Aero on the title bar? I'm using WaveFox and if I use the shiny variant of Aero10, the title bar looks super opaque. Do you have that problem?

It's like that effect on the border extends all the way to the title bar for some reason:
![image](https://github.com/Maplespe/DWMBlurGlass/assets/52336985/067779f9-9130-42e3-b4c9-3e5a70e33dc8)

You can see Notepad looks fine, but Firefox looks hideous.
