### ISSUE TITLE
Support for new Aero options in the GUI

### ISSUE THREAD

**Issue by kfh83** [Maplespe/DWMBlurGlass#234]
**Describe the solution you'd like**
> A clear and concise description of what you want to happen.

With 2.1.0, we've introduced a completely new solution for the Aero backdrop, featuring a lot more variables to control the colorization. However, the GUI has stayed the same and has not accounted for the new changes. The only controls that are available other than the color picker are the opacity changer, which currently (in my opinion) is fairly misnamed as it controls SecondaryBalance (Multiply effect), not the actual opacity of the window.

Thus, i think for the Aero backdrop, the opacity slider should be changed to 4 new sliders, controlling BlurBalance, ColorBalance, reflectionIntensity and SecondaryBalance all separately (the former 3 are only config.ini entries right now):

![image](https://github.com/Maplespe/DWMBlurGlass/assets/85626296/4cbdc6fa-34b3-4113-a60b-e332c1f41448)
(Rough mockup of what the new color picker UI would look like)

You might be asking, why wouldn't this be implemented in the Effect picker, like Acrylic:
![image](https://github.com/Maplespe/DWMBlurGlass/assets/85626296/a23273c7-fc7e-4f6a-b8b0-9a1e961ae6c7)
Well, since the effect varies between inactive and active windows this needs to be in the Color Picker. However, a slider for the Crossfade Animation's duration could be added in a similar fashion.
**Your reason (tell us why we need it)**

> Briefly describe your reasons for wanting to do this.

These settings are either non-adjustable in the UI currently or incorrectly named.

**Describe alternatives you've considered**
> A clear and concise description of any alternative solutions or features you've considered.

Given the lack of access to MiaoUI (and also we probably wouldn't be able to work with it due to the lack of documentation, we've had alternative configurators for my forked DWMBlurGlass build that could properly tweak these settings:

![image](https://github.com/Maplespe/DWMBlurGlass/assets/85626296/81552707-180f-4c24-9acf-acc2640c88af)
_credit to [Mr. Lechkar](https://github.com/CatmanFan) in ClassicServ_

**Comment by TheInsane101** [comment]
You probably already know that Maplespe is the only one who has access to MiaoUI and knows how it works, right? We have to wait for him to finish his work before he can come back here; either that or Altale has to figure out how it works. 

Isn't it possible for people to code their own GUI from scratch that doesn't need MiaoUI? Also, is that "DWMBlurGlass colorization fix config" just a concept or is it being developed?

**Comment by TheInsane101** [comment]
Ooh thanks! Why did you get banned?

**Comment by Maplespe** [comment]
For more information about how to refresh, please see #242, all functions are in the code and have nothing to do with MiaoUI, please read the code carefully.
