### ISSUE TITLE
DWM crashes when a visible window gets killed/crashes

### ISSUE THREAD

**Issue by ImSwordQueen** [Maplespe/DWMBlurGlass#237]
**Describe the bug**
DWM crashes with Exception code: 0xc0000409 when a process that isn't minimized crashes or gets killed by task manager.
Killing processes that are minimized does not crash DWM.

Description ....

**To Reproduce**
1. Open a notepad window
2. Open task manager
3. Keep the notepad window open and not minimized
4. Kill that notepad window thru task manager
5. It should crash DWM

Description ....

**Screenshots**

https://github.com/Maplespe/DWMBlurGlass/assets/52015098/55d6a5e8-7190-4dd7-8c85-b38f69e0e403

(I have a task that reloads DWMBG automatically. That didn't effect the results though.)

**Additional information (please complete the following information):**
 > OS Version : Windows 10 LTSC 21H2 19044.4170
 > Software Version : 2.1.0

**What other third-party software do you use:**
[Windhawk] Aerexplorer (the crash happens with it disabled)
[Windhawk] Restore Windows 7 Caption Buttons (the crash happens with it disabled)
Windhawk (Same thing)

**Additional context**
The same crash happens on AcrylicEverywhere with the same error code.

**Comment by ALTaleX531** [comment]
@kfh83 The glass reflects itself. Because the process is killed and the window handle is invalid, the glass reflection is unable to compute the offset and thus throws an exception, and due to the lack of a catch block, the dwm crashes.
