### ISSUE TITLE
BUG: Using Mica on Windows 10 Crashes DWM

### ISSUE THREAD

**Issue by Mukul1127** [Maplespe/DWMBlurGlass#244]
**Describe the bug**
> A clear and concise description of what the bug is:

DWM crashes when trying to use mica effect with custom method on windows 10

**To Reproduce**
> Steps to reproduce the behavior:

1. Install on windows 10.
2. Select mica with custom method.
3. As soon as you click a window other than DWMBlurGlass, dwm crashes.

**Screenshots**
> If applicable, add screenshots to help explain your problem:

N/A

**Additional information (please complete the following information):**
 > OS Version : Windows 10 22H2 19045.4239
 > Software Version : 2.1.1

**What other third-party software do you use:**
 > [e.g. windhawk mods xxx]

Rectify11, though it don't modify dwm.

**Additional context**

Event Log:

Faulting application name: dwm.exe, version: 10.0.19041.3636, time stamp: 0x6e55ef4a
Faulting module name: DWMBlurGlassExt.dll, version: 2.0.1.0, time stamp: 0x6607b09f
Exception code: 0xc0000005
Fault offset: 0x0000000000024ed5
Faulting process id: 0x9c4
Faulting application start time: 0x01da838c815eeeb8
Faulting application path: C:\Windows\System32\dwm.exe
Faulting module path: C:\Program Files\DwmBlurGlass\DWMBlurGlassExt.dll
Report Id: 8e30719e-b18d-43f5-9c5c-b4c4b9bd12bf
Faulting package full name: 

XML:

<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="Application Error" /> 
    <EventID Qualifiers="0">1000</EventID> 
    <Version>0</Version> 
    <Level>2</Level> 
    <Task>100</Task> 
    <Opcode>0</Opcode> 
    <Keywords>0x80000000000000</Keywords> 
    <TimeCreated SystemTime="2024-03-31T16:59:25.6060848Z" /> 
    <EventRecordID>75712</EventRecordID> 
    <Correlation /> 
    <Execution ProcessID="0" ThreadID="0" /> 
    <Channel>Application</Channel> 
    <Computer>Mukul-PC</Computer> 
    <Security /> 
  </System>
  <EventData>
    <Data>dwm.exe</Data> 
    <Data>10.0.19041.3636</Data> 
    <Data>6e55ef4a</Data> 
    <Data>DWMBlurGlassExt.dll</Data> 
    <Data>2.0.1.0</Data> 
    <Data>6607b09f</Data> 
    <Data>c0000005</Data> 
    <Data>0000000000024ed5</Data> 
    <Data>9c4</Data> 
    <Data>01da838c815eeeb8</Data> 
    <Data>C:\Windows\System32\dwm.exe</Data> 
    <Data>C:\Program Files\DwmBlurGlass\DWMBlurGlassExt.dll</Data> 
    <Data>8e30719e-b18d-43f5-9c5c-b4c4b9bd12bf</Data> 
    <Data /> 
    <Data /> 
  </EventData>
</Event>

**Comment by ALTaleX531** [comment]
There's no such thing as mica in Windows 10.

**Comment by Mukul1127** [comment]
Yes, I know but I though the custom effect emulates it instead of actually using windows api

**Comment by ALTaleX531** [comment]
@timea-techgirl Unrelated to this issue, your video card driver was probably upgraded not too long ago.

**Comment by ALTaleX531** [comment]
@timea-techgirl The problem was only caused by upgrading the graphics driver a short while ago, it is a bug in the GUI program and you can continue to use DwmBlurGlass and not need to do anything.

**Comment by ALTaleX531** [comment]
@timea-techgirl That's just because you don't happen to have encountered it, in fact the problem has been around since 1.0.0.

**Comment by T0biasCZe** [comment]
would it be possible to at least add some simple protection to not allow user to select Mica on Windows 10? 
to prevent the DWM from crashing
