### ISSUE TITLE
Trying to make a Windows mod with DWMBlurGlass, after capturing and deploying the WIM the aero effects won't work.

### ISSUE THREAD

**Issue by MyComputer1** [Maplespe/DWMBlurGlass#247]
**Describe the bug**
> A clear and concise description of what the bug is:

When attempting to make a Windows mod featuring aero titlebars, after adding the app and then capturing then deploying the WIM (in audit mode) the effects won't work.

**To Reproduce**
> Steps to reproduce the behavior:

Install Windows 10/11, enter audit mode, install DWMBlurGlass, generalize the image, capture the WIM, then deploy it.

**Screenshots**
> If applicable, add screenshots to help explain your problem:

**Additional information (please complete the following information):**
 > OS Version : Windows 10 v23H2
 > Software Version : 2.0.1

**What other third-party software do you use:**
 > [e.g. windhawk mods xxx]

None

**Additional context**
It can be helpful for Windows modders trying to make mods featuring Aero titlebars like those from Windows Vista and 7.

**Comment by ALTaleX531** [comment]
Doesn't seem to be related to dwmblurglass.
