### ISSUE TITLE
Make all frames thick

### ISSUE THREAD

**Issue by arukateru** [Maplespe/DWMBlurGlass#248]
**Describe the solution you'd like**
Implement the thick frames to be applied to the window in the case that the frames are thin. Example: silverlight configuration page. It cannot be done simply by adding the WS_THICKFRAME style, this makes every window resizable and whether the application has existing thick frames needs to be taken into account. And a window can have a thick frame without the WS_THICKFRAME style. The border needs to be put on the outside of the application, not on the inside like applying the WS_THICKFRAME automatically would do. The window size cannot be increased either, because if the program already has a thickframe, then it looks very bad

**Your reason (tell us why we need it)**
To apply the real Windows 7 behavior
Avoiding things like this:
![image](https://github.com/Maplespe/DWMBlurGlass/assets/84914212/1b2c1913-2c95-47fd-b924-33adef187109)

**Describe alternatives you've considered**
Trying to write my own DLL for it but I cant find a way to persistently find whether the window has a thick frame (not WS_THICKFRAME, i mean thick frame. A window can have a thick frame without having WS_THICKFRAME style.

**Additional context**

**Comment by windowsxp3790** [comment]
Not really in the scope of the project in my opinion

**Comment by ALTaleX531** [comment]
Feature already requested in #147.
