### ISSUE TITLE
Titlebar text shifts downward during minimize and close animation.

### ISSUE THREAD

**Issue by Ten2O** [Maplespe/DWMBlurGlass#25]
The titlebar text shifts downward during minimize animation and close animation. This is on latest version.

https://github.com/Maplespe/DWMBlurGlass/assets/63513830/10473a79-b4fc-416d-8f14-97542eae5ebe

https://github.com/Maplespe/DWMBlurGlass/assets/63513830/64c75111-ab8a-4b71-a1fa-c7596bb9f9d5

**Comment by Maplespe** [comment]
You appear to be using other third-party software or modifying system settings.
Under normal use the animation is only 0.5 seconds Even when I slow it down 5x with CE mods I only see 1 frame of falling (and that's still the default system behavior), it doesn't keep falling.
It's not even noticeable under normal use.

**Comment by nopahc4** [comment]
> You appear to be using other third-party software or modifying system settings. Under normal use the animation is only 0.5 seconds Even when I slow it down 5x with CE mods I only see 1 frame of falling (and that's still the default system behavior), it doesn't keep falling. It's not even noticeable under normal use.

it kinda is noticeable under normal usage ngl, but it doesn't really matter that much so you don't need to patch immediately. take your time

**Comment by Ten2O** [comment]
> You appear to be using other third-party software or modifying system settings. Under normal use the animation is only 0.5 seconds Even when I slow it down 5x with CE mods I only see 1 frame of falling (and that's still the default system behavior), it doesn't keep falling. It's not even noticeable under normal use.

I am not using third party software. Windows has a native feature that you can enable that slows the animation down when holding shift.

**Comment by Maplespe** [comment]
Resolved in the new version.
