### ISSUE TITLE
Google Chrome Titlebar

### ISSUE THREAD

**Issue by timea-techgirl** [Maplespe/DWMBlurGlass#250]
**Describe the solution you'd like**
> Glass effect on Google Chrome's titlebar

**Your reason (tell us why we need it)**
> People mostly use browsers on their computer, it's the most used app. So, it would be great to see glass effect in the browser titlebar, especially Google Chrome

**Describe alternatives you've considered**
> There was a flag, `--disable-windows-10-custom-titlebar` in the past.
It stopped working a few months ago. Now, there is support for Windows 11 Mica titlebar but it doesn't work on Windows 10
> There was a patcher known as AG4FFCR ver.0.0.0.11 which patched Chrome and Firefox's titlebars.
[AG4FFCR ver.0.0.0.11.zip](https://github.com/Maplespe/DWMBlurGlass/files/14865574/AG4FFCR.ver.0.0.0.11.zip)

**Comment by ALTaleX531** [comment]
This can't be implemented in the dwm side.

**Comment by arukateru** [comment]
> **Describe the solution you'd like**
> 
> > Glass effect on Google Chrome's titlebar
> 
> **Your reason (tell us why we need it)**
> 
> > People mostly use browsers on their computer, it's the most used app. So, it would be great to see glass effect in the browser titlebar, especially Google Chrome
> 
> **Describe alternatives you've considered**
> 
> > There was a flag, `--disable-windows-10-custom-titlebar` in the past.
> > It stopped working a few months ago. Now, there is support for Windows 11 Mica titlebar but it doesn't work on Windows 10
> > There was a patcher known as AG4FFCR ver.0.0.0.11 which patched Chrome and Firefox's titlebars.
> > [AG4FFCR ver.0.0.0.11.zip](https://github.com/Maplespe/DWMBlurGlass/files/14865574/AG4FFCR.ver.0.0.0.11.zip)

Any version for Edge ? Can I modify the script inside for chrome for edge ?

**Comment by not-nullptr** [comment]
this issue is entirely unrelated to dwmblurglass

**Comment by lucassilvas1** [comment]
Nice @timea-techgirl , do you know if there's a way to achieve this on Firefox? Without involving something like Echelon that is, just vanilla Firefox but with Aero.

**Comment by jonm58** [comment]
> Nice @timea-techgirl , do you know if there's a way to achieve this on Firefox? Without involving something like Echelon that is, just vanilla Firefox but with Aero.

https://github.com/Eclipse-Community/r3dfox

**Comment by lucassilvas1** [comment]
Is it supposed to work out of the box @jonm58 ? I couldn't find anything on how to enable Aero.
![image](https://github.com/Maplespe/DWMBlurGlass/assets/52336985/235206af-a00e-4de2-b669-34cbe0f10edf)

**Comment by jonm58** [comment]
> Is it supposed to work out of the box @jonm58 ? I couldn't find anything on how to enable Aero. ![image](https://private-user-images.githubusercontent.com/52336985/320175022-235206af-a00e-4de2-b669-34cbe0f10edf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIzNzU4MzUsIm5iZiI6MTcxMjM3NTUzNSwicGF0aCI6Ii81MjMzNjk4NS8zMjAxNzUwMjItMjM1MjA2YWYtYTAwZS00ZGUyLWI2NjktMzRjYmUwZjEwZWRmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA2VDAzNTIxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk5ZTczYWU0Zjk2OGNlMzk2NmJmYjk4YjU4ZjIzNzEwOGJkZDg3NDk4YzljNDQ0NTMwNjJkYzg5YTlkMzMyOWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.SRqbXrxzSme_8n8OiUzio17P4du2Nv-iInZ-hYd9pm0)

Use 115esr CSS Themes or spooft win7
![image](https://github.com/Maplespe/DWMBlurGlass/assets/73036321/6983251b-d845-4d6c-ba1c-66f2159c13b9)
How to spooft win7:
![image](https://github.com/Maplespe/DWMBlurGlass/assets/73036321/2cf3d875-3102-43f4-816a-1289030fd888)

**Comment by lucassilvas1** [comment]
I followed [this](https://old.reddit.com/r/firefox/comments/6vwb2t/why_does_firefox_not_use_the_native_titlebar_on/dr70r5c/) and got it to work. Thanks @jonm58 .

**Comment by Skyyblaze** [comment]
@lucassilvas1 @jonm58 It's funny to see what I wrote ages ago on Reddit being referenced here, the world is small. Meanwhile I found a way to do this without having to mess with the firefox.exe:

Save the manifest as a text-file and name it firefox.exe.manifest and place it next to the actual firefox.exe. Then follow these instructions: https://github.com/superzanti/high_dpi_external_manifest_files

and Firefox should adhere to the external manifest the next time it's started.

**Comment by Ben2557** [comment]
> Found a way to achieve it on Windows 10...
> 
> ![image](https://private-user-images.githubusercontent.com/7058205/319855753-f35444f4-ddc5-4488-8787-d1f52cb1d794.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcxODE5ODgsIm5iZiI6MTcxNzE4MTY4OCwicGF0aCI6Ii83MDU4MjA1LzMxOTg1NTc1My1mMzU0NDRmNC1kZGM1LTQ0ODgtODc4Ny1kMWY1MmNiMWQ3OTQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUzMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MzFUMTg1NDQ4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YzVkNGYzODI2ZGUxMTg5ZTU3NWMyY2JkODJjNmM5NGMzODE2ZjI5M2YyY2YyMTY0NTY0ZjczZDZlOTUxMjZlYyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.0khabpTA_FhkOeqmNaWBm7VgpPAn-j6OoQbHeN7NevU)
> 
> * Install Application Verifier
> * Add chrome into it and untick all options
> * In Compatibility > HighVersionLie, enter the build number as `10.0.22631`
> * Save and exit
> * Open chrome://flags
> * Enable Windows 11 Mica titlebar
> * Restart chrome and you have the beautiful glass effect
> * If you have any themes enabled, disable it in Chrome settings > Appearance or the titlebar effect will not be seen
> 
> This may work on Edge, I haven't tested.

Hello,
I'm on Windows 10 May update and I can't get it to work.
![image](https://github.com/Maplespe/DWMBlurGlass/assets/91072875/d240303a-31d6-49ab-af32-8673ff26f852)
![image](https://github.com/Maplespe/DWMBlurGlass/assets/91072875/45740919-eaef-475f-8816-f68d5d80eef5)
![image](https://github.com/Maplespe/DWMBlurGlass/assets/91072875/dc6446d2-3c56-4d92-9a60-054bf62e3d67)
![image](https://github.com/Maplespe/DWMBlurGlass/assets/91072875/abef0996-fd7a-405b-9633-1ceca1120b09)

Notice : After saving then went again on properties : 
![image](https://github.com/Maplespe/DWMBlurGlass/assets/91072875/6a9c50e8-6577-428b-865c-0eddbfc640b3)

**Comment by Ben2557** [comment]
> > I'll be glad if you could help !
> 
> Edit accordingly. :)
> 
> ![image](https://private-user-images.githubusercontent.com/7058205/335711081-01d71e7c-2b5a-419a-8ee5-ed3c7e16c16f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcxODU4MzMsIm5iZiI6MTcxNzE4NTUzMywicGF0aCI6Ii83MDU4MjA1LzMzNTcxMTA4MS0wMWQ3MWU3Yy0yYjVhLTQxOWEtOGVlNS1lZDNjN2UxNmMxNmYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUzMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MzFUMTk1ODUzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZTEzMGEzODgxYzQzZWU1MjdkOGYxYzhiYjdjNGVjZWYwZWVhNjc0NjNkNGZkMWQxM2JkYjcwMTczMDVjZWVhOCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.rMoFAkUyVD1n3u-u9DGAkXB2-ZvSDRV5Vu9dFXQvK0k)

I made the change but still no luck...

![image](https://github.com/Maplespe/DWMBlurGlass/assets/91072875/a5cb6a1c-55d1-492c-8680-19521d91228c)

**Comment by lucassilvas1** [comment]
> > I made the change but still no luck...
> 
> Is your chrome 32 or 64 bit? You have to use the same architecture for Application Verifier. Have you disabled themes in chrome? Check if the flag is enabled. Open chrome from start menu. Restart chrome (Make sure to end all chrome processes from task manager)

Not him, but I can't even get Chrome to launch after using Application Verifier unless I undo the changes.
Both apps in question are x64.

**Comment by finestuff** [comment]
> > Not him, but I can't even get Chrome to launch after using Application Verifier unless I undo the changes. Both apps in question are x64.
> 
> I am on chrome 123. Maybe something broke in newer versions.

Maybe there is some other way? Doesn't work for me on Chrome 126

**Comment by funn-hue** [comment]
> > > Not him, but I can't even get Chrome to launch after using Application Verifier unless I undo the changes. Both apps in question are x64.
> > 
> > 
> > I am on chrome 123. Maybe something broke in newer versions.
> 
> Maybe there is some other way? Doesn't work for me on Chrome 126

It works for me, what you gotta do is go to chrome, click your account photo and the pencil next to it. Then you select the color marked as "default color". If it still doesn't work go to windows settings>personalization>colors and turn off show accent color on titlebar and window borders

**Comment by finestuff** [comment]
> > > > Not him, but I can't even get Chrome to launch after using Application Verifier unless I undo the changes. Both apps in question are x64.
> > > 
> > > 
> > > I am on chrome 123. Maybe something broke in newer versions.
> > 
> > 
> > Maybe there is some other way? Doesn't work for me on Chrome 126
> 
> It works for me, what you gotta do is go to chrome, click your account photo and the pencil next to it. Then you select the color marked as "default color". If it still doesn't work go to windows settings>personalization>colors and turn off show accent color on titlebar and window borders

It works! But if I try to install custom tabs, it goes back. How do I get this to work together?

**Comment by funn-hue** [comment]
> > > > > Not him, but I can't even get Chrome to launch after using Application Verifier unless I undo the changes. Both apps in question are x64.
> > > > 
> > > > 
> > > > I am on chrome 123. Maybe something broke in newer versions.
> > > 
> > > 
> > > Maybe there is some other way? Doesn't work for me on Chrome 126
> > 
> > 
> > It works for me, what you gotta do is go to chrome, click your account photo and the pencil next to it. Then you select the color marked as "default color". If it still doesn't work go to windows settings>personalization>colors and turn off show accent color on titlebar and window borders
> 
> It works! But if I try to install custom tabs, it goes back. How do I get this to work together?

probably not fixable

**Comment by lucassilvas1** [comment]
> > > > Not him, but I can't even get Chrome to launch after using Application Verifier unless I undo the changes. Both apps in question are x64.
> > > 
> > > 
> > > I am on chrome 123. Maybe something broke in newer versions.
> > 
> > 
> > Maybe there is some other way? Doesn't work for me on Chrome 126
> 
> It works for me, what you gotta do is go to chrome, click your account photo and the pencil next to it. Then you select the color marked as "default color". If it still doesn't work go to windows settings>personalization>colors and turn off show accent color on titlebar and window borders

I just tried this again when I got the email from GitHub and this time it worked, weird. 
Either way, I'm using Edge these days, do you know how to make it work with Edge? If I follow the same steps with Edge, it launches with a white or black screen (depending on the Application Verifier architecture I pick) and closes after a few seconds. Edge is on the Program Files (x86) folder, but neither the x64 nor the WOW version of Application Verifier seems to work with it. Any ideas?

**Comment by TheHuman20020** [comment]
> > > > Not him, but I can't even get Chrome to launch after using Application Verifier unless I undo the changes. Both apps in question are x64.
> > > 
> > > 
> > > I am on chrome 123. Maybe something broke in newer versions.
> > 
> > 
> > Maybe there is some other way? Doesn't work for me on Chrome 126
> 
> It works for me, what you gotta do is go to chrome, click your account photo and the pencil next to it. Then you select the color marked as "default color". If it still doesn't work go to windows settings>personalization>colors and turn off show accent color on titlebar and window borders

A bit late to this but I can confirm this method still works as of Chrome 128
![image](https://github.com/user-attachments/assets/4017dfb7-3e1d-47e6-88e6-ccfbdd41a669)

tried with Edge as well but when I follow the same procedure, the browser shows a white screen for a few seconds and then crashes, don't know what that's about, but anyways, chrome works perfectly.

**Comment by eaden1234** [comment]
> > > > > Not him, but I can't even get Chrome to launch after using Application Verifier unless I undo the changes. Both apps in question are x64.
> > > > 
> > > > 
> > > > I am on chrome 123. Maybe something broke in newer versions.
> > > 
> > > 
> > > Maybe there is some other way? Doesn't work for me on Chrome 126
> > 
> > 
> > It works for me, what you gotta do is go to chrome, click your account photo and the pencil next to it. Then you select the color marked as "default color". If it still doesn't work go to windows settings>personalization>colors and turn off show accent color on titlebar and window borders
> 
> A bit late to this but I can confirm this method still works as of Chrome 128 ![image](https://github.com/user-attachments/assets/4017dfb7-3e1d-47e6-88e6-ccfbdd41a669)
> 
> tried with Edge as well but when I follow the same procedure, the browser shows a white screen for a few seconds and then crashes, don't know what that's about, but anyways, chrome works perfectly.
> 
> Edit: Also, the reason it didn't work previously was because i had colored titlebars enabled, so disabling them does fix the issue

Not working anymore, since they removed all the flags related to it.

**Comment by timea-techgirl** [comment]
I am on Chrome 135, everything works in this version. I haven't updated yet
