### ISSUE TITLE
在任务栏进行最小化和最大化时，窗口会在设置的模糊颜色背景闪烁，这样破坏了原本的顺滑体验

### ISSUE THREAD

**Issue by JiaRZ** [Maplespe/DWMBlurGlass#251]
**Describe the bug**
> A clear and concise description of what the bug is:
在任务栏进行最小化和最大化时，窗口会在设置的模糊颜色背景闪烁，这样破坏了原本的顺滑体验
Description ....

**To Reproduce**
> Steps to reproduce the behavior:

Description ....

**Screenshots**
> If applicable, add screenshots to help explain your problem:

**Additional information (please complete the following information):**
 > OS Version : [e.g. Windows 11 23H2.22631.3085]
 > Software Version : [e.g. 2.0.1]

**What other third-party software do you use:**
 > [e.g. windhawk mods xxx]

None

**Additional context**

**Comment by Maplespe** [comment]
与#102 类似。
