### ISSUE TITLE
Miscoloured Inactive Tab With New Aero Glass

### ISSUE THREAD

**Issue by mangopow** [Maplespe/DWMBlurGlass#258]
**Describe the bug**
> When using the new aero glass blur effect, clicking off or causing the window to become inactive will make the titlebar over exposed and bright.

**To Reproduce**
> Click to the Advaced tab and change the effect mode to Aero

**Screenshots**
> If applicable, add screenshots to help explain your problem:

**Active:**
![image](https://github.com/Maplespe/DWMBlurGlass/assets/94416902/49eea0d9-3f28-4c92-ae31-715f6741cbdd)

**Inactive:**
![image](https://github.com/Maplespe/DWMBlurGlass/assets/94416902/67130b7f-d03c-4fdc-9166-d9d5a95958d2)

**Additional information:**
 > OS Version : [Windows 10 22H2.19045.4170]
 > Software Version : [2.1.1-2.1.0]

**What other third-party software do you use:**
 > Windhawk Mods: Restore Vista Caption Buttons

**Comment by Maplespe** [comment]
This is the behavior of the Aero effect in Windows 7, any questions?

**Comment by mangopow** [comment]
Would there be any way to replicate the effect used in windows vista?

**Comment by Maplespe** [comment]
This is also true for vista, but if you need to change the detailed saturation, color balance, etc. you need to modify the ini file
The following are the default parameters for the Windows 7 Sky theme:
```ini
[config.aero]
activeColorBalance=0.080000
inactiveColorBalance=0.032000
activeBlurBalance=-0.125000
inactiveBlurBalance=0.365000
```
