### ISSUE TITLE
[Bug] Unable to download symbols in Win11 22631.3447

### ISSUE THREAD

**Issue by LexBoosT** [Maplespe/DWMBlurGlass#259]
Impossible to download symbols in Windows 11 23H2 22631.3447

**Screenshots**
![Capture d'écran 2024-04-09 214046](https://github.com/Maplespe/DWMBlurGlass/assets/44103115/281411de-0a7e-49c7-8d63-2098bca89220)

 > OS Version : Windows 11 23H2.22631.3447
 > Software Version : 2.1.1

**Comment by Zenguycolorado** [comment]
The same for Windows 10, 22H2 Build 19045.4239.

**Comment by dyt5AAUI** [comment]
The same for Windows 10, 21H2 Build 19044.4291.

**Comment by Maplespe** [comment]
See if you can access https://msdl.microsoft.com directly

**Comment by Undisputed00x** [comment]
Had same problem, the next day on first boot managed to successfully download symbols.

**Comment by LexBoosT** [comment]
@Maplespe, when I go to the link it works, I (for the 20th time in the month) restarted the download of the symbols and now it works :). However, I have to stay on version 2.0.1 because with higher versions I lose the blur of Windows windows, I don't know why.

**Comment by LexBoosT** [comment]
Problem fixed i think it's problem with https://msdl.microsoft.com/ but now work. Thanks!

**Comment by Zenguycolorado** [comment]
@LexBoosT You are indeed correct and all is now so far working well again. Thank you.

**Comment by Zenguycolorado** [comment]
@Maplespe This issue is now resolved for me as well. Many thanks and thank you also for all the work you put in to this. It's much appreciated.

**Comment by froggz19** [comment]
same problem on 22631.3520. I guess the symbols are no yet available?
