### ISSUE TITLE
Disable DWMBlurGlass when battery saver is active.

### ISSUE THREAD

**Issue by SandTechStuff** [Maplespe/DWMBlurGlass#261]
**Describe the solution you'd like**
> A clear and concise description of what you want to happen.

Add an option in the config file or gui to automatically disable DWMBlurGlass when battery saver is active, like Windows does with the default transparency effects.

**Your reason (tell us why we need it)**
> Briefly describe your reasons for wanting to do this.

When I enable battery saver, it is to conserve my laptop's battery for as long as possible. DWMBlurGlass is unaffected by battery saver unlike normal transparency effects in windows, leading to increased battery drain.

**Describe alternatives you've considered**
> A clear and concise description of any alternative solutions or features you've considered.

Manually uninstalling DWMBlurGlass whenever I want to conserve battery life.

**Additional context**

I do not know if it is possible for DWMBlurGlass to detect the state of the battery saver toggle, but if it is this would be a nice addition.

**Comment by Maplespe** [comment]
I mentioned this in #152.
