### ISSUE TITLE
Windows have ugly corners if the "decrease titlebar button height" is turned off

### ISSUE THREAD

**Issue by arukateru** [Maplespe/DWMBlurGlass#266]
**To Reproduce**
Use a theme with rounded corners and turn off the decrease titlebar button height option

Description ....
Corners do not get rounded properly if the "decrease titlebar button height" option is turned off
![image](https://github.com/Maplespe/DWMBlurGlass/assets/84914212/1e008107-1191-48e2-977e-83dec25b54d8)

**Additional information (please complete the following information):**
 > OS Version : LTSC 10.0.19041.4291
 > Software Version : 2.0.1

Another small bug/why I am making this issue:
If using the Windhawk mod to properly calculate thick frames with the decrease button height option enables, it causes the button position to be moved too far to the right (picture 1) so I decided to turn it off and use another Windhawk mod only to move the buttons.
On normal windows, it works fine, but not on windows affected by the thick frame mod.
I also wonder if it is possible that DWMBlurGlass can recalculate the thick frames and extend the blur area accordingly, like the [thick frame mod with calculations that is in issue 147](https://github.com/Maplespe/DWMBlurGlass/issues/147#issuecomment-2052520952). When using the mod the blur is not extended like in photo 2. I know it may seem like a trivial thing to implement, but the thin frames look very bad and it shows up a lot in some circumstances (like 40% of windows installers have thin frames).

![image](https://github.com/Maplespe/DWMBlurGlass/assets/84914212/299ae5ce-6749-4e77-9f67-1ae0c79bdd23)
![image](https://github.com/Maplespe/DWMBlurGlass/assets/84914212/540919a7-6693-41cc-b7a8-f67b3d0c6922)

**What other third-party software do you use:**
 > [e.g. windhawk mods xxx]

None

**Additional context**

**Comment by bag-xml** [comment]
youre running software version 2.0.1, whilst the newest available release is 2.1.1, how about you update then re-check
