### ISSUE TITLE
Some files cannot be found

### ISSUE THREAD

**Issue by lijinlong-yevs** [Maplespe/DWMBlurGlass#274]
1.“Mui.h”: No such file or directory;
2.<User/Mui_Engine.h>: No such file or directory;

**Comment by windowsxp3790** [comment]
> 1.“Mui.h”: No such file or directory; 2.<User/Mui_Engine.h>: No such file or directory;

Because the MiaoUI library is private

**Comment by Maplespe** [comment]
Already mentioned in ReadMe.

**Comment by Maplespe** [comment]
We don't provide the UI library (DWMBlurGlass project).
But you can just compile the DWMBlurGlassExt project, that is the core of this project.
If you need to compile the UI project, please manually remove all code and references to Mui and modify it to command line mode.
Other related contents and basics involving C++ application development will not be guided by us.

**Comment by lijinlong-yevs** [comment]
> We don't provide the UI library (DWMBlurGlass project). But you can just compile the DWMBlurGlassExt project, that is the core of this project. If you need to compile the UI project, please manually remove all code and references to Mui and modify it to command line mode. Other related contents and basics involving C++ application development will not be guided by us.

OK,Thanks you very much
