### ISSUE TITLE
GUI runs and doesn't open every login?

### ISSUE THREAD

**Issue by arukateru** [Maplespe/DWMBlurGlass#284]
**Describe the bug**
In this update, for some reason, the GUI program tries to run automatically every startup. But it doesn't open anyways
Description ....

**To Reproduce**
Install latest version

Description ....

**Screenshots**
> If applicable, add screenshots to help explain your problem:

**Additional information (please complete the following information):**
 > OS Version : LTSC 2021
 > Software Version : 2.2.0

**What other third-party software do you use:**
 None

**Additional context**

**Comment by Maplespe** [comment]
You must completely uninstall the old version.
If you have manually created or modified a scheduled task, delete it and reinstall the new version.
The new version has a different command line than the old version.

**Comment by arukateru** [comment]
Thats what I did and it looks like this
![image](https://github.com/Maplespe/DWMBlurGlass/assets/84914212/dca14a5f-da58-4db0-8b53-8ec6c9f61570)

**Comment by Maplespe** [comment]
Right now it's just for RDP, there's no support for multiple users yet.
The GUI now has a resident process in the background that monitors for dwm crashes and reloads it automatically.
