### ISSUE TITLE
Override AccentBlur effect StartAllBack conflict

### ISSUE THREAD

**Issue by froggz19** [Maplespe/DWMBlurGlass#285]
**Description**
 > 'Override AccentBlur effect' option conflicting with StartAllBack immersive menus.

**To Reproduce**
 > Have StartAllBack installed and immersive menus enabled ("ImmersiveMenus"=dword:00000001)
 > Enable 'Override AccentBlur effect' in DWMBlurGlass GUI -> Misc

**Screenshots**
![image](https://github.com/Maplespe/DWMBlurGlass/assets/8935954/dba7ffb9-0001-41ab-8687-58b449e66ecd)
<img width="374" alt="image" src="https://github.com/Maplespe/DWMBlurGlass/assets/8935954/46146bce-fde6-4320-87ef-897bc5f179ef">

**What other third-party software do you use**
 > StartAllBack

**Additional information**
 > OS Version : Windows 11 23H2.22631.3527
 > DWMBlurGlass Version : 2.2.0
 > StartAllBack Version : 3.7.8

What exactly does 'Override AccentBlur effect' option do?

**Comment by funn-hue** [comment]
> What exactly does 'Override AccentBlur effect' option do?

Most likely replaces AccentBlur with it's own stuff

**Comment by Maplespe** [comment]
> > What exactly does 'Override AccentBlur effect' option do?
> 
> Most likely replaces AccentBlur with it's own stuff

The ability to override AccentBlur was mentioned in #105.

**Comment by SandTechStuff** [comment]
Can confirm. Override AccentBlur makes context menus borderline unusable when using StartAllBack. It is a shame since the taskbar and start menu effects Override AccentBlur brings are really nice.

**Comment by DanTheGuy720** [comment]
I wish StartAllBack had an option to disable the blur on legacy context menus to begin with. When I'm using my own msstyle theme I don't want to use their version of the context menus.

**Comment by Maplespe** [comment]
You can turn off the option to restore the classic context menu in StartAllback.
Then add the registry to bring back the classic right-click menu to your system.
Run cmd as administrator
``` cmd
reg add "HKCU\Software\Classes\CLSID\{86ca1aa0-34aa-4e8b-a509-50c905bae2a2}\InprocServer32" /f /ve
taskkill /f /im explorer.exe & explorer.exe
```
Restore changes:
``` cmd
reg delete "HKCU\Software\Classes\CLSID\{86ca1aa0-34aa-4e8b-a509-50c905bae2a2}\InprocServer32" /f /ve
taskkill /f /im explorer.exe & explorer.exe
```
