### ISSUE TITLE
Override accent breaks SIB jump list/taskbar preview corners and colors

### ISSUE THREAD

**Issue by Alcatel7** [Maplespe/DWMBlurGlass#289]
**Describe the bug**
> A clear and concise description of what the bug is:
Override accent breaks SIB jump list/taskbar preview corners and colors

Description ....

**To Reproduce**
Use 2.2.0 and enable override accent.
The corners are broken and the color used is much darker than the glass color.

**Screenshots**
How it looks now:
![image](https://github.com/Maplespe/DWMBlurGlass/assets/84914212/272845db-5112-492f-893a-1df143d38993)

How it should look/looked in last version:
![image](https://github.com/Maplespe/DWMBlurGlass/assets/84914212/a996782c-7c66-4170-9bdf-a0a70e808f8d)

**Additional information (please complete the following information):**
 > OS Version : Windows 10 2021 IoT LTSC
 > Software Version : 2.2.0

**What other third-party software do you use:**
 > windhawk mods

**Additional context**

**Comment by arukateru** [comment]
yes, they have never been overridden. interesting. i wonder what causes the darker colors

**Comment by Maplespe** [comment]
Check the custom color on StartIsBack and set the color to translucent blue (your theme color or DWMBlurGlass color)

**Comment by Maplespe** [comment]
This seems to be some layer blending issue with AeroBackdrop, other effects (Blur, Acrylic) don't seem to have this issue.

**Comment by arukateru** [comment]
The DWMBlurGlass seems to be rendering the color twice in the taskbar. Sometimes, when I restart DWM (maybe 10% of the time), a bug occurs where the colors are 2x as dark as they need to be even on the titlebars

![image](https://github.com/Maplespe/DWMBlurGlass/assets/84914212/2bc8debe-b489-42cf-9486-dfeda549b100)
