### ISSUE TITLE
File Explorer doesn't seem to react to titlebar blend color

### ISSUE THREAD

**Issue by nopahc4** [Maplespe/DWMBlurGlass#29]
I updated to the newest version and noticed the file explorer title bar is not using the titlebar blend color specified and seems to use the accent color for it. Attaching 2 screenshots of the run window and the explorer titlebar

https://cdn.discordapp.com/attachments/999083687775830117/1198542627797213224/image.png?ex=65bf48ce&is=65acd3ce&hm=d93b9e9b0570b1d2a8d540ac047b18e49da03c4086e3c0289bcafaed93190d0e&

https://cdn.discordapp.com/attachments/999083687775830117/1198542636143869972/image.png?ex=65bf48d0&is=65acd3d0&hm=192736f12c96f939370c8571a067fea74770038fb0802447067b1819b31eeadc&

I have "show accent color on title bars" enabled in settings (issue only happens with that) because without that I no longer have colored window borders, and the inactive window frames don't use the correct blend color I specified

**Comment by Maplespe** [comment]
I suggest you uninstall the old version and re-download it now, I updated the attachment at 3:00 and 4:30 local time.
This is not happening on my machine at the moment.

**Comment by nopahc4** [comment]
okay will try

**Comment by nopahc4** [comment]
so i reinstalled, and it still seems to be happening, also noticed it also happens to discord (only active titlebars btw), the inactive title bar color issue is gone and now it uses the one from the blend color. for now i will be using it with the feature disabled

**Comment by nopahc4** [comment]
nevermind, with the setting off  issue still occurs, active titlebars are darker for discord and explorer, where on other apps its fine. inactive colors are ok

**Comment by Maplespe** [comment]
Are you using the dark color mode? , I have found that only the dark color mode has this problem, light color everything is fine.

**Comment by nopahc4** [comment]
> Are you using the dark color mode? , I have found that only the dark color mode has this problem, light color everything is fine.

yes, im using dark color

**Comment by Maplespe** [comment]
[Release_x64.zip](https://github.com/Maplespe/DWMBlurGlass/files/14000659/Release_x64.zip)
Try this.

**Comment by nopahc4** [comment]
> [Release_x64.zip](https://github.com/Maplespe/DWMBlurGlass/files/14000659/Release_x64.zip) Try this.

it's slightly better, less dark but still same thing

**Comment by nopahc4** [comment]
ill attach some pics

https://media.discordapp.net/attachments/999083687775830117/1198558319376338945/image.png?ex=65bf576b&is=65ace26b&hm=ac04caaf32bc40f8ee776e6a091a7e62c4491a1414a1c8357b03fcf5a9289c07&=&format=webp&quality=lossless&width=693&height=28

this one shows the discord titlebar inactive and the run window active (both blend colors have the same values btw so it's using the correct color for inactive titlebars)

https://media.discordapp.net/attachments/999083687775830117/1198558388020326482/image.png?ex=65bf577b&is=65ace27b&hm=0c9e9c0081e5df1afb0c90067a3e76b48f891b2f982ea9ab66023d11cb131148&=&format=webp&quality=lossless&width=693&height=28

this one shows discord titlebar active and run inactive (they should both look the same, but discord has a slightly darker titlebar, same applies to explorer)

**Comment by Maplespe** [comment]
Sorry, win11 had the same problem, the one just now was supposed to fix win11, it should all be fixed this time.
I updated the attachment, just re-download the Release page.

**Comment by nopahc4** [comment]
> Sorry, win11 had the same problem, the one just now was supposed to fix win11, it should all be fixed this time. I updated the attachment, just re-download the Release page.

thank you, it's fixed

**Comment by Cynosphere** [comment]
Still having issues with the unfocused color not applying to Explorer/Electron apps/anything else that uses DWM extended frames on Windows 10 with app mode set to dark, using the latest version from the release page.

**Comment by Maplespe** [comment]
Please provide further information.

**Comment by ALTaleX531** [comment]
![image](https://github.com/Maplespe/DWMBlurGlass/assets/105535231/b545a009-4e29-442e-bcb6-db4ac740b4ec)

**Comment by Cynosphere** [comment]
@ALTaleX531 Your explorer frames are not extended. I will post examples in a few hours.

**Comment by ALTaleX531** [comment]
![image](https://github.com/Maplespe/DWMBlurGlass/assets/105535231/7902edee-5806-4006-94c8-82f9491f2b1c)
The fact that the explorer frames have already been extended, otherwise it couldn't place buttons on the titlebar. Here is another example using OldNewExplorer.

**Comment by Cynosphere** [comment]
Its fine in light mode
![image](https://github.com/Maplespe/DWMBlurGlass/assets/1606710/4c869c95-9569-4b15-bf1f-66fcce178835)
![image](https://github.com/Maplespe/DWMBlurGlass/assets/1606710/b14eb48e-5d3f-4ed4-8680-be09eb1bedb4)

But not in dark mode
![image](https://github.com/Maplespe/DWMBlurGlass/assets/1606710/c1ffece9-3395-4511-8f18-c8e33bbcbea6)
![image](https://github.com/Maplespe/DWMBlurGlass/assets/1606710/8a005320-2c0f-4026-8b44-7e7ed3ed91f0)

Unless its a normal window
![image](https://github.com/Maplespe/DWMBlurGlass/assets/1606710/c752a1ed-66ac-4037-b4e6-c2317c95421c)

And even Electron apps that look like they have normal window borders also don't work
![image](https://github.com/Maplespe/DWMBlurGlass/assets/1606710/e267895e-1329-4779-a932-db6cb5263e9f)
![image](https://github.com/Maplespe/DWMBlurGlass/assets/1606710/8e5cef13-505a-43cd-aee5-c58cad012bf2)

**Comment by Cynosphere** [comment]
Oh, I'm blind and didn't realize theres a separate tab now for dark mode colors. This issue can be closed now then.
