### ISSUE TITLE
StartIsBack++ is no longer showing reflections on the taskbar and start menu when the correct settings are enabled.

### ISSUE THREAD

**Issue by OleExploder** [Maplespe/DWMBlurGlass#291]
Description: Before a certain update on Windows 10 that occurred around a month ago or so, it was possible for reflections to show on the taskbar as long as the aero glass reflections were enabled and as long as blur was enabled in StartIsBack as well. But now that the update happened a month ago, the reflections on the taskbar stopped working.

Screenshots:
![Capture](https://github.com/Maplespe/DWMBlurGlass/assets/113773450/947b19da-effc-4576-aa1a-d535dac0d230)
Before Update (An earlier version was used in this screenshot which may have been 1.0.4 if I can remember correctly but that was the version I used before the update broke the reflections on the taskbar and start menu. When I upgraded to version 2.1.1, things still didn't change.)

![Capture 2](https://github.com/Maplespe/DWMBlurGlass/assets/113773450/db5f6a91-8836-4bbe-b525-54c01ef042b7)
After Update (Version 2.1.1 was used in this screenshot.)

OS Version : Windows 10 22H2 (OS Build 19045.4291)

Software Versions: DWMBlurGlass 2.1.1 & StartIsBack++ 2.9.20

Other software: Windhawk Aerexplorer mod

Other details: Looking through the issues page, I am not sure if this problem has already been fixed or if it happened to anybody else but if possible, please let me know if there is anything that can be done about this problem.

**Comment by Maplespe** [comment]
Use version 2.2.0 and check "Override AccentBlur".

**Comment by OleExploder** [comment]
That worked, thank you very much!

**Comment by TheInsane101** [comment]
> That worked, thank you very much!

Happy to hear that! Could you please close this issue thread now?

**Comment by TheInsane101** [comment]
@Maplespe You seem much more active recently. Are you done with the work that you were busy with in the past few weeks? I didn't expect you to be back so soon already!

**Comment by Maplespe** [comment]
> @Maplespe You seem much more active recently. Are you done with the work that you were busy with in the past few weeks? I didn't expect you to be back so soon already!

It hasn't been that busy lately and you seem to forget that the last 2 days have been days off 😄.

**Comment by TheInsane101** [comment]
> It hasn't been that busy lately and you seem to forget that the last 2 days have been days off 😄.

I'm a third year medical student at university who has to study every day. It's all I know, so it's hard for me to imagine an off-day anymore😅

**Comment by Skyyblaze** [comment]
> > @Maplespe You seem much more active recently. Are you done with the work that you were busy with in the past few weeks? I didn't expect you to be back so soon already!
> 
> It hasn't been that busy lately and you seem to forget that the last 2 days have been days off 😄.

I just want to say thanks for all the hard work and effort you're doing for DWMBlurGlass and all the people!
