### ISSUE TITLE
is not working

### ISSUE THREAD

**Issue by pmerrs7** [Maplespe/DWMBlurGlass#292]
![image](https://github.com/Maplespe/DWMBlurGlass/assets/166287783/2b3f7ebc-f9d5-4e65-9ef9-cd835189ffe3)
using Windows 10 Enterprise 2021 LTSC

**Comment by Maplespe** [comment]
Please follow the template, we don't know your specific system version number.
Also I'm guessing you may not have the download symbol.

**Comment by pmerrs7** [comment]
> Please follow the template, we don't know your specific system version number. Also I'm guessing you may not have the download symbol.

10.0.19044.4291 (Win10 21H2 November 2021 Update)
![image](https://github.com/Maplespe/DWMBlurGlass/assets/166287783/f605b4ac-d9ac-42d9-bb18-3b5d5519232f)

**Comment by Maplespe** [comment]
I'm sure the tool will work with LTSC version 2021.
So you need to rule out some possible reasons of your own, such as whether the files are complete, whether your account has system administrator privileges, and whether your files are placed in a non-user directory (preferably in the root of the system disk or in the Program Files directory)
Please uninstall before moving files.
And whether the anti-virus software is blocking some operations, etc.

**Comment by pmerrs7** [comment]
it worked, i reinstalled it, ty
