### ISSUE TITLE
v2.2.0 crash error

### ISSUE THREAD

**Issue by indigofairyx** [Maplespe/DWMBlurGlass#296]
**Describe the bug**
>v2.2.0 crashing with the following error...
>"Checked that the process is suspected to have crashed abnormally and has stopped autoloading."

Description ....

**To Reproduce**
> Steps to reproduce the behavior:
im not sure how to reproduce this error, or whats causing it, but has happened a few time in the past two days.

Description ....

**Screenshots**
> ![DWMBlurGlass_2024-04-28_09-42-59PM_546x216](https://github.com/Maplespe/DWMBlurGlass/assets/126439010/9860a1f8-8a90-4d04-af09-c9b739d5356b)
>![image](https://github.com/Maplespe/DWMBlurGlass/assets/126439010/940feff8-7855-4537-a627-15873bbb9227)
>![image](https://github.com/Maplespe/DWMBlurGlass/assets/126439010/3ec51b2b-f79a-4310-b9cc-a428169ad3f7)

**Additional information (please complete the following information):**
 > OS Version : Windows 10, V 22H2 [os build 19045.4291]
 > Software Version : 2.2.0

**What other third-party software do you use:**
 > StartIsBack++ 2.9.20

>SecureUx ThemeTool
>1714368491971 > Version v2.2.0
>1714368491973 > Running on 10.0.19045 flavor F
>1714368491975 > MainDialog: is_elevated 0
>1714368491976 > Session user: CLOUDEN Process user: 

>running w7t_108 from https://windows7themenew2.carrd.co

None

**Additional context**

**Comment by digiant** [comment]
我也是这个错误，win11 canary build 26200

**Comment by LexBoosT** [comment]
same error on 26120.461

**Comment by LexBoosT** [comment]
any news for that?

**Comment by Maplespe** [comment]
We don't have any plans to support Insider Preview, it's been said many times. So for Insider Preview, this is not a bug at all and don't report it.

ReadMe Original:
>Compatibility
> Supported as low as Windows 10 2004 and as high as the latest version of Windows 11 (**Some blurring methods are not supported in Windows Insider versions**).

**Comment by windowsxp3790** [comment]
> We don't have any plans to support Insider Preview, it's been said many times. So for Insider Preview, this is not a bug at all and don't report it.
> 
> ReadMe Original:
> 
> > Compatibility
> > Supported as low as Windows 10 2004 and as high as the latest version of Windows 11 (**Some blurring methods are not supported in Windows Insider versions**).

This happens on the stable builds of 19041 too btw

**Comment by Skyyblaze** [comment]
I can confirm it happens on Windows 11 22631.3447 stable too, mostly when something opens a "Save As" Explorer Dialog or similar.

**Comment by windowsxp3790** [comment]
> I can confirm it happens on Windows 11 22631.3447 stable too, mostly when something opens a "Save As" Explorer Dialog or similar.

It happens every 5mins for me regardless of what I do

**Comment by Maplespe** [comment]
Please provide detailed settings or configuration files.
Also please try to disable all windhawk mods, to make sure it's not caused by their conflicts.

I've been using it on my main machine for 2 weeks now and haven't had a single crash.
I don't use any 3rd party mods.
Windows 11 Pro 23H2 22631.3447

**Comment by Skyyblaze** [comment]
> Please provide detailed settings or configuration files. As well, is any beta version being used instead of the Release release 2.2.0? Also please try to disable all windhawk mods, to make sure it's not caused by their conflicts.
> 
> I've been using it on my main machine for 2 weeks now and haven't had a single crash. I don't use any 3rd party mods. Windows 11 Pro 23H2 22631.3447

I'm running 2.2.0 Stable, Windhawk isn't installed on this machine, otherwise I have StartAllBack running for the Taskbar and restoring Explorer to the Windows 7 version. Then ExplorerPatcher just to reactivate the Windows 10 Start Menu and finally ExplorerBlurMica and ExplorerTool, both which you created, I love those tools.

This is my config file:

`[config]
applyglobal=true
extendBorder=false
reflection=true
oldBtnHeight=true
customAmount=true
crossFade=true
useAccentColor=false
blurAmount=20.000000
customBlurAmount=20.000000
luminosityOpacity=0.650000
activeTextColor=4278190080
inactiveTextColor=4290032820
activeTextColorDark=4294967295
inactiveTextColorDark=4290032820
activeBlendColor=1694035447
inactiveBlendColor=1694498815
activeBlendColorDark=1677721600
inactiveBlendColorDark=1677721600
glassIntensity=1.000000
aeroColorBalance=0.300000
aeroAfterglowBalance=0.430000
aeroBlurBalance=0.490000
blurMethod=0
effectType=3
crossfadeTime=160
overrideAccent=false`

And finally I'm using this theme: https://www.deviantart.com/niivu/art/cakeOS-2-0-for-Windows-11-22H2-953541433 with SecureUX

**Comment by windowsxp3790** [comment]
> Please provide detailed settings or configuration files. As well, is any beta version being used instead of the Release release 2.2.0? Also please try to disable all windhawk mods, to make sure it's not caused by their conflicts.
> 
> I've been using it on my main machine for 2 weeks now and haven't had a single crash. I don't use any 3rd party mods. Windows 11 Pro 23H2 22631.3447

I'm using 2.2.0 release build from the regular branch
Windows 10 IoT enterprise ltsc 2021 (19044.4291)

Settings

General:
Extend effects into borders
Enable aero reflection

Advanced:
Blur method: custom 
Effect type: Aero
Blur radius: 3
ColorBalance: 0.08
BlurBalance: 0.49
AfterglowBalance: 0.43

Use accent color to override color settings RGB
Override AccentBlur effect

I've disabled all windhawk mods and it crashes dwm and disables the reinject every 5-10mins of regular use

**Comment by Kerans-Lihen** [comment]
同样的错误，放生在 1000.19060.1000.0

**Comment by wjh1507** [comment]
我也有这个问题 win11 23h2 22631.4602

**Comment by kalichen2021** [comment]
So, why it tagged by "Closed", maybe it had been solved? 
If so, I am grateful someone can tell me the solution

**Comment by kalichen2021** [comment]
There is the error log:
DLOGFILE00010000DUMPU'          
Dump stack initialized at UTC: 2025/02/09 05:53:23, local time: 2025/02/09 13:53:23.
#BugCheckCode 0x000000000000014F
#BugCheckP1 0x0000000000000004
#BugCheckP2 0x0000000000000002
#BugCheckP3 0xFFFFF80263952730
#BugCheckP4 0xFFFFCE87FE61F960
Progress 0x00000042
Elapsed BugCheck duration 00001386ms
Starting get secondary dump callbacks size.
Progress 0x00000052
Finish get secondary dump callbacks size.
Dump Type: 6, Total Dump Size: 2238769109, Secondary Dump Size: 5617621.
Starting write of dump header.
Finish write of dump header.
Starting write of kernel bitmap dump header.
Finish write of bitmap dump header.
Starting write of memory dump data.
Elapsed BugCheck duration 00001420ms
Dumping physical memory to disk:  0% 
Dumping physical memory to disk:  5% 
Dumping physical memory to disk:  10% 
Dumping physical memory to disk:  15% 
Dumping physical memory to disk:  20% 
Dumping physical memory to disk:  25% 
Dumping physical memory to disk:  30% 
Dumping physical memory to disk:  35% 
Dumping physical memory to disk:  40% 
Dumping physical memory to disk:  45% 
Dumping physical memory to disk:  50% 
Dumping physical memory to disk:  55% 
Dumping physical memory to disk:  60% 
Dumping physical memory to disk:  65% 
Dumping physical memory to disk:  70% 
Dumping physical memory to disk:  75% 
Dumping physical memory to disk:  80% 
Dumping physical memory to disk:  85% 
Dumping physical memory to disk:  90% 
Dumping physical memory to disk:  95% 
Dumping physical memory to disk:  100% 
Finish write of bitmap dump data. Total pages:544760 Pages written:544760
Progress 0x00000043
Elapsed BugCheck duration 00013345ms
Starting invoking secondary dump callbacks.
Calling Intel Wireless WiFi Link Adapter secondary callback.
Return from Intel Wireless WiFi Link Adapter secondary callback.
Writing Intel Wireless WiFi Link Adapter secondary callback data.
Writing Intel Wireless WiFi Link Adapter secondary callback data done.
Calling wdiwifi secondary callback.
Return from wdiwifi secondary callback.
Writing wdiwifi secondary callback data.
Writing wdiwifi secondary callback data done.
Calling wdiwifi secondary callback.
Return from wdiwifi secondary callback.
Writing wdiwifi secondary callback data.
Writing wdiwifi secondary callback data done.
Calling igdkmdn64.sys secondary callback.
Return from igdkmdn64.sys secondary callback.
Writing igdkmdn64.sys secondary callback data.
Writing igdkmdn64.sys secondary callback data done.
Calling CRASHDUMP secondary callback.
Return from CRASHDUMP secondary callback.
Writing CRASHDUMP secondary callback data.
Writing CRASHDUMP secondary callback data done.
Calling ibtdrv secondary callback.
Return from ibtdrv secondary callback.
Writing ibtdrv secondary callback data.
Writing ibtdrv secondary callback data done.
Calling Usb4DeviceRouter secondary callback.
Return from Usb4DeviceRouter secondary callback.
Writing Usb4DeviceRouter secondary callback data.
Writing Usb4DeviceRouter secondary callback data done.
Calling Usb4DeviceRouter secondary callback.
Return from Usb4DeviceRouter secondary callback.
Writing Usb4DeviceRouter secondary callback data.
Writing Usb4DeviceRouter secondary callback data done.
Calling Usb4DeviceRouter secondary callback.
Return from Usb4DeviceRouter secondary callback.
Writing Usb4DeviceRouter secondary callback data.
Writing Usb4DeviceRouter secondary callback data done.
Calling Usb4DeviceRouter secondary callback.
Return from Usb4DeviceRouter secondary callback.
Writing Usb4DeviceRouter secondary callback data.
Writing Usb4DeviceRouter secondary callback data done.
Calling Usb4DeviceRouter secondary callback.
Return from Usb4DeviceRouter secondary callback.
Writing Usb4DeviceRouter secondary callback data.
Writing Usb4DeviceRouter secondary callback data done.
Calling Usb4DeviceRouter secondary callback.
Return from Usb4DeviceRouter secondary callback.
Writing Usb4DeviceRouter secondary callback data.
Writing Usb4DeviceRouter secondary callback data done.
Calling HbEvtpSystemDiagLogCrashdump secondary callback.
Return from HbEvtpSystemDiagLogCrashdump secondary callback.
Writing HbEvtpSystemDiagLogCrashdump secondary callback data.
Writing HbEvtpSystemDiagLogCrashdump secondary callback data done.
Calling nvpcf secondary callback.
Return from nvpcf secondary callback.
Writing nvpcf secondary callback data.
Writing nvpcf secondary callback data done.
Calling wdiwifi secondary callback.
Return from wdiwifi secondary callback.
Writing wdiwifi secondary callback data.
Writing wdiwifi secondary callback data done.
Calling Usb4HostRouter secondary callback.
Return from Usb4HostRouter secondary callback.
Writing Usb4HostRouter secondary callback data.
Writing Usb4HostRouter secondary callback data done.
Calling Usb4HostRouter secondary callback.
Return from Usb4HostRouter secondary callback.
Writing Usb4HostRouter secondary callback data.
Writing Usb4HostRouter secondary callback data done.
Calling Usb4HostRouter secondary callback.
Return from Usb4HostRouter secondary callback.
Writing Usb4HostRouter secondary callback data.
Writing Usb4HostRouter secondary callback data done.
Calling Usb4HostRouter secondary callback.
Return from Usb4HostRouter secondary callback.
Writing Usb4HostRouter secondary callback data.
Writing Usb4HostRouter secondary callback data done.
Calling Usb4HostRouter secondary callback.
Return from Usb4HostRouter secondary callback.
Writing Usb4HostRouter secondary callback data.
Writing Usb4HostRouter secondary callback data done.
Calling Usb4HostRouter secondary callback.
Return from Usb4HostRouter secondary callback.
Writing Usb4HostRouter secondary callback data.
Writing Usb4HostRouter secondary callback data done.
Calling Usb4HostRouter secondary callback.
Return from Usb4HostRouter secondary callback.
Writing Usb4HostRouter secondary callback data.
Writing Usb4HostRouter secondary callback data done.
Calling Usb4HostRouter secondary callback.
Return from Usb4HostRouter secondary callback.
Writing Usb4HostRouter secondary callback data.
Writing Usb4HostRouter secondary callback data done.
Calling Usb4HostRouter secondary callback.
Return from Usb4HostRouter secondary callback.
Writing Usb4HostRouter secondary callback data.
Writing Usb4HostRouter secondary callback data done.
Calling nvlddmkm.sys secondary callback.
Return from nvlddmkm.sys secondary callback.
Writing nvlddmkm.sys secondary callback data.
Writing nvlddmkm.sys secondary callback data done.
Calling IoBugCheckDriverData secondary callback.
Return from IoBugCheckDriverData secondary callback.
Writing IoBugCheckDriverData secondary callback data.
Writing IoBugCheckDriverData secondary callback data done.
Calling PortDriverStandard secondary callback.
Return from PortDriverStandard secondary callback.
Writing PortDriverStandard secondary callback data.
Writing PortDriverStandard secondary callback data done.
Calling \Device\DxgKrnl secondary callback.
Return from \Device\DxgKrnl secondary callback.
Writing \Device\DxgKrnl secondary callback data.
Writing \Device\DxgKrnl secondary callback data done.
Calling Wdf01000 secondary callback.
Return from Wdf01000 secondary callback.
Writing Wdf01000 secondary callback data.
Writing Wdf01000 secondary callback data done.
Calling blackbox - CI secondary callback.
Return from blackbox - CI secondary callback.
Writing blackbox - CI secondary callback data.
Writing blackbox - CI secondary callback data done.
Calling blackbox - Winlogon secondary callback.
Return from blackbox - Winlogon secondary callback.
Writing blackbox - Winlogon secondary callback data.
Writing blackbox - Winlogon secondary callback data done.
Calling blackbox - NTFS secondary callback.
Return from blackbox - NTFS secondary callback.
Writing blackbox - NTFS secondary callback data.
Writing blackbox - NTFS secondary callback data done.
Calling blackbox - PNP secondary callback.
Return from blackbox - PNP secondary callback.
Writing blackbox - PNP secondary callback data.
Writing blackbox - PNP secondary callback data done.
Calling blackbox - BSD secondary callback.
Return from blackbox - BSD secondary callback.
Writing blackbox - BSD secondary callback data.
Writing blackbox - BSD secondary callback data done.
Calling SecureKernelFailureLog secondary callback.
Return from SecureKernelFailureLog secondary callback.
Writing SecureKernelFailureLog secondary callback data.
Writing SecureKernelFailureLog secondary callback data done.
Calling SecureKernelCrashdumpArea secondary callback.
Return from SecureKernelCrashdumpArea secondary callback.
Writing SecureKernelCrashdumpArea secondary callback data.
Writing SecureKernelCrashdumpArea secondary callback data done.
Calling secondary multi-part dump callbacks.
Starting TRIAGEDUMPDATA multi-part secondary callback.
Finish TRIAGEDUMPDATA multi-part secondary callback.
Starting SMBiosData multi-part secondary callback.
Finish SMBiosData multi-part secondary callback.
Starting SMBiosRegistry multi-part secondary callback.
Finish SMBiosRegistry multi-part secondary callback.
Starting SMBiosRegisters multi-part secondary callback.
Finish SMBiosRegisters multi-part secondary callback.
Starting SMBiosDataACPI multi-part secondary callback.
Finish SMBiosDataACPI multi-part secondary callback.
Starting PCI multi-part secondary callback.
Finish PCI multi-part secondary callback.
Starting Etw multi-part secondary callback.
Finish Etw multi-part secondary callback.
Finish calling secondary multi-part dump callbacks.
Progress 0x00000045
Finish invoking secondary dump callbacks.
Starting invoking dump complete callbacks; Type: 0x04.
Finished invoking dump complete callbacks; Type: 0x04.
Progress 0x00000046
Dump ended at UTC: 2025/02/09 05:53:23, local time: 2025/02/09 13:53:23.
Elapsed BugCheck duration 00014410ms
Progress 0x00000053
Dump completed successfully.

When I open a file with uncentain type, the OS will popups a column(pics below) to select an app to open it, when DWM has collapsed...

![Image](https://github.com/user-attachments/assets/1db3c9ea-08e7-4c6f-a24e-733e79a789e1)

**Comment by gabrielizalo** [comment]
I have the same problem. How it was fixed. Thanks!
