### ISSUE TITLE
Aero Inactive Titlebar Color

### ISSUE THREAD

**Issue by NotJorrd** [Maplespe/DWMBlurGlass#298]
**Describe the bug**
Clicking off of a window doesn't update the titlebar to it's normal "inactive" color/effect.

**To Reproduce**
Clicking off of a window.

**Screenshots**

![image](https://github.com/Maplespe/DWMBlurGlass/assets/156122285/e34a6ab3-c799-4299-a8b6-11ac4327208e)

**Additional information:**
OS Version : Windows 10 21H2 IoT (OS Build 19044.4291)
Software Version : 2.2.0

**What other third-party software do you use:**
Windhawk Mods:
- Aerexplorer
- Restore Windows 7 Caption Buttons
- Acrylic Effect Radius Changer
- Aero Flyout Fix
- Aero Tray
- Legacy File Copy
- Force thick frames
- Eradicate Immersive Menus
- Remove UWP titlebars
- Old This PC Commands
- Win32 Tray Clock Experience
- Windows 7 Alt+Tab Loader
- Windows 7 Clock Spacing

**Additional context**
Not sure if this happens for everyone, but I've noticed it a lot lately
I have "Use Accent color to override color settings RGB" enabled, but that doesn't seem to be the reason why

**Comment by Maplespe** [comment]
I think there should be a conflict with one of your Windhawk mods, I suggest you deactivate all mods and try again.

**Comment by NotJorrd** [comment]
> I think there should be a conflict with one of your Windhawk mods, I suggest you deactivate all mods and try again.

Restore Windows 7 Caption Buttons conflicts with it. I just tested it

**Comment by Maplespe** [comment]
There was a similar problem before because this Windhawk mod broke the CTopLevelWindow::TreatAsActiveWindow function.
#130

**Comment by Maplespe** [comment]
That thread has a better solution and sample mod code.
BTW the DWMBlurGlass title bar button functionality in version 2.2.0 is accurate and I don't see the need for another mod.
Also DWMBlurGlass has the ability to change the global blur level without the "Acrylic Effect Radius Changer" mod.
These duplicate functions only reduce stability.

**Comment by arukateru** [comment]
> That thread has a better solution and sample mod code. BTW the DWMBlurGlass title bar button functionality in version 2.2.0 is accurate and I don't see the need for another mod(See #282). Also DWMBlurGlass has the ability to change the global blur level without the "Acrylic Effect Radius Changer" mod. These duplicate functions only reduce stability.

If there is the option to fix the text positioning, and the inactive button opacity, then the seven titlebar options will be truly complete.

**Comment by arukateru** [comment]
I meant in dwmblurglass. It would be best compatibility to not use any windhawk mod for DWM, i guess. Currently, this mod also seems to cause occasional glitches with text button glow. I am trying to modify this mod to only modify the text positioning and not the button positions, but I'm not a good programmer and always something breaks
