### ISSUE TITLE
Accent Colorization doesn't work properly until settings or color update

### ISSUE THREAD

**Issue by Mrk20200** [Maplespe/DWMBlurGlass#299]
**Describe the bug**
Reinjecting DWMBlurGlass (by reinstalling from the GUI, restarting the computer, or restarting DWM) with the "Use Accent color to override color settings RGB" option enabled doesn't color the titlebars properly (uses blue instead of current accent color)

**To Reproduce**

0. (optional) Restore DWMBlurGlass to the default settings
1. Enable "Use Accent color to override color settings RGB" under the Advanced tab
2. Restart DWM from Task Manager or reinstall DWMBlurGlass
3. Observe the incorrect titlebar colors
4. Do either of the following to fix the titlebar color:
a. Change any other setting in the GUI and click the save icon
b. Change the accent color

**Screenshots**
Before settings change: (DWM was restarted after I saved the settings)
![blueTitlebar](https://github.com/Maplespe/DWMBlurGlass/assets/157867907/55fdbe3c-5314-456a-bc51-43364e34ce6c)

After settings change:
![coloredTitlebar](https://github.com/Maplespe/DWMBlurGlass/assets/157867907/67377753-cf9d-4cd6-9937-454bee5cfc67)

**Additional information**
OS Version : Windows 10 22H2.19045.4170
Software Version : 2.2.0

**What other third-party software do you use:**
None (tested on a basic Windows 10 setup)

**Comment by NotJorrd** [comment]
Can confirm

**Comment by nabrious0** [comment]
Can confirm this too! It happens when rebooting aswell.

**Comment by SteelDMN** [comment]
Hi, I still experience this issue on W11 24H2 and DWMBG 2.3.1.
Could you please tell us workaround, where does this sowtware put accent color to redefine titlebar color?
We probably just could edit a registry key to get rid of rogue color everytime dwm restarts

<img width="905" height="564" alt="Image" src="https://github.com/user-attachments/assets/a35a2d03-3bd0-4379-bd24-585c7989f6ec" />
