### ISSUE TITLE
[EnhanceMent] Support Win11 Legacy Photo Viewer

### ISSUE THREAD

**Issue by LoveJessyChen** [Maplespe/DWMBlurGlass#3]
to Support Win11 Legacy Photo Viewer please, 
Now,  Win11 Legacy Image Viewer shows as a white window ,
I hope that it can add an option to enable Aero Glass to Win11 Legacy Photo Viewer

**Comment by emeraldongithub** [comment]
![image](https://github.com/Maplespe/DWMBlurGlass/assets/99167692/994adb28-d8bf-4231-a7e7-bf696ffab7bc)
If you are talking about the Windows 7 Photo Viewer, it is supported.

**Comment by LoveJessyChen** [comment]
@emeraldongithub
But In win11 22621.963, This win7 photo viewer doesn't have Aero UI and shows white windows frame.

**Comment by dangochu** [comment]
you can use micaforeveryone to enable mica effect
