### ISSUE TITLE
Windows explorer not fully glass, only title bars effected.

### ISSUE THREAD

**Issue by Leokalan8** [Maplespe/DWMBlurGlass#303]
**Bug Description**
> Glass effect does not effect main explorer windows. Titlebars only affected.

**To Reproduce**
> Happens apon using DWM regularly.

**Screenshots**
> ![image](https://github.com/Maplespe/DWMBlurGlass/assets/45269826/1f7540d0-6229-4521-96bf-abfb08ddc8ec)

**Additional information**
 > OS Version: Windows 11 23H2.22631.3447
 > Software Version: 2.2.0

**Other Third-Party Software Used**
 > Rectify11

**Additional context**
> Brand new Windows 11 install with Rectify11, and explorer window does not appear transparent, only the title bar does.
I have tried updating graphics drivers, changing my power plan, but to no effect.
I also have a laptop on the exact same version with the exact same setup (Fresh with Rectify11) except it works as intended with no issues.

**Comment by Maplespe** [comment]
DWMBlurGlass is only for the title bar, for Explorer window transparency please use ExplorerBlurMica.
