### ISSUE TITLE
Open-Shell Blur Conflict

### ISSUE THREAD

**Issue by NotJorrd** [Maplespe/DWMBlurGlass#304]
**Describe the bug**
When "Override AccentBlur effect" is enabled in DWMBlurGlass, the start menu has a random chance of looking like either one of the images below when opened.

![image](https://github.com/Maplespe/DWMBlurGlass/assets/156122285/ec0f8546-160c-404d-8245-3dece0871141)
![image](https://github.com/Maplespe/DWMBlurGlass/assets/156122285/c3132a07-e3ff-4976-ab91-2a437f8cb820)

**To Reproduce**
Enable "Override AccentBlur effect", then open your open shell start menu over and over.

**Additional information**
OS Version Windows 10 21H2
Software Version : 2.2.0

It might be a 3rd party issue, but I dunno

**Comment by DanTheGuy720** [comment]
I think this happens in multiple scenarios for me too. I use StartAllBack and sometimes the system tray overflow menu will have no blur, same with the legacy context menus (since SAB likes to add blur behind them by default), and sometimes the Start menu.
