### ISSUE TITLE
dpi scaling causing button drifts

### ISSUE THREAD

**Issue by indigofairyx** [Maplespe/DWMBlurGlass#305]
**Describe the bug**
> changing the Scaling Dpi thru windows settings is casing the buttons to drift. [see screen shots below]
>
>i didnt notice this for a while until i plugged in a 2nd monitor.
>
>monitor 1- is 48in 4k tv [usually my only monitor cause its too big!] **i have the dpi scaling set to 125%**
>
>monitor 2- i added back my old 1080p monitor with its standard resolution and 100% dpi scaling and that's when i noticed the buttons shift in\away from the edge of title bar.

**To Reproduce**

>Change\Increase the Dpi Scaling from windows 10 settings, System > Display > Scale and layout

**Screenshots**
> ![button scaling WinaeroTweaker_2024-05-02_08-14-26PM_1024x666](https://github.com/Maplespe/DWMBlurGlass/assets/126439010/565c95fb-e334-4b9f-b2b5-9b968cffa634)

**Additional information (please complete the following information):**
 > OS Version : Windows 10, V 22H2 (build 19045.4291
 > Software Version : 2.0.1
>>[still on 2.0.1 the new version is over the top with 45% gpu usage! **thou this bug does behave the same on v2.2.0**

**What other third-party software do you use:**
 > stardock shadow FX 
> StartisBack++

**Additional context**
PS... i'm not complaining, LOVE having AERO again! ❤️  just posting about this so youre aware.

**Comment by Maplespe** [comment]
It is automatically calculated based on the theme and border metrics.
If it doesn't apply to your theme or modified metrics, you need to specify it yourself.
See #282, Customizing the titlelebtnOffsetX value.

**Comment by Skyyblaze** [comment]
I'm not sure if it's related but I'm using the Glow Buttons test-branch and I sometimes have my buttons wander all over the title-bar. Sometimes the close button is on the middle of the titlebar and the maximize button on the left for example. I'll provide screenshots when it happens again.

**Comment by TheInsane101** [comment]
> I'm not sure if it's related but I'm using the Glow Buttons test-branch and I sometimes have my buttons wander all over the title-bar. Sometimes the close button is on the middle of the titlebar and the maximize button on the left for example. I'll provide screenshots when it happens again.

Happens to me too, but that's expected with test branches.

**Comment by Skyyblaze** [comment]
> > I'm not sure if it's related but I'm using the Glow Buttons test-branch and I sometimes have my buttons wander all over the title-bar. Sometimes the close button is on the middle of the titlebar and the maximize button on the left for example. I'll provide screenshots when it happens again.
> 
> Happens to me too, but that's expected with test branches.

Alright good to know, I just wanted to put it out there.

**Comment by Skyyblaze** [comment]
Is there a list with all the test-branches? I lost the download to the initial Glowing Buttons branch and I can't find it again.
