### ISSUE TITLE
Changing hex value in the box in the GUI doesn't apply

### ISSUE THREAD

**Issue by TheInsane101** [Maplespe/DWMBlurGlass#307]
**Describe the bug**
> A clear and concise description of what the bug is:

When changing the value inside the text box where you can change the active and inactive colour values for the windows in the GUI, when you click "confirm," you see the correct colour in the preview box briefly, but it then reverts the colour and only applies the change to the opacity. This means that the hex box is broken and you can't change colours through it.

**To Reproduce**
> Steps to reproduce the behavior:

1. Open either the active or inactive titlebar blend colour
2. Change the value in the hex code box.
3. Click confirm and watch as the preview colour changes just before the window disappears, but then look at the colour boxes and see that they haven't changed. 
4. Open the titlebar blend colour window again and note that only the opacity changed. 

**Screenshots**
> If applicable, add screenshots to help explain your problem:

https://github.com/Maplespe/DWMBlurGlass/assets/104862146/77608df7-aaf2-40c4-a762-e972210aacb1

**Additional information (please complete the following information):**
 > OS Version : [e.g. Windows 11 23H2.22631.3085]
 > Software Version : [e.g. 2.0.1]

Windows 10 22H2
DWMBlurGlass 2.2

**What other third-party software do you use:**
 > [e.g. windhawk mods xxx]

Startisback++ 2.9.20, Windhawk mods: Aero Tray, Aero Flyout Fix, Taskbar Scroll Actions, Win32 Tray Clock Experience, Windows 7 Clock Spacing

**Additional context**

**Comment by VerMishelb** [comment]
There is a way to work around it: after putting the HEX value, click on empty space, then click at the Blue, Green, Red fields on the right **in that order**. Then you can confirm and the colour will be saved.

**Comment by TheInsane101** [comment]
Oh that worked! Thank you!
