### ISSUE TITLE
Support for Theme Atlas

### ISSUE THREAD

**Issue by Hadden89** [Maplespe/DWMBlurGlass#308]
**Describe the solution you'd like**
> It was a great feature present in glass8 which allowed to change the titlebar buttons without relying on an external theme.

**Your reason (tell us why we need it)**
> This allowed to harmonize the appearance of the buttons within different apps (for example explorer or others)

![cc118ce5-d3b7-4c5c-9f74-2c17847fae7e-image](https://github.com/Maplespe/DWMBlurGlass/assets/18642541/5911d11d-c3eb-4a52-ba44-003b658a9a52)

**Describe alternatives you've considered**
> I played with settings but didn't manage to have a consistent layout, with an atlas file it might be possible (win8 atlas below as reference):

![win8rp](https://github.com/Maplespe/DWMBlurGlass/assets/18642541/6e97424e-5282-4d5f-b279-7658ce1d6fa6)

Thanks for the tool, though =)

**Comment by TheInsane101** [comment]
I think you mean glass8, not aero8, as the name of the preview Aero program.

**Comment by Hadden89** [comment]
yeah, correct. Fixed that. Tnx.

**Comment by Maplespe** [comment]
We do not intend to provide this feature The purpose of this project is not to emulate glass8.
I suggest you to use [OpenGlass ](https://github.com/ALTaleX531/OpenGlass)It is an alternative to glass8 and has almost all the features of glass8.
