### ISSUE TITLE
Deformed titlebar buttons

### ISSUE THREAD

**Issue by SandTechStuff** [Maplespe/DWMBlurGlass#316]
**Describe the bug**
> A clear and concise description of what the bug is:

The maximize titlebar button on Windows 11 is deformed/incorrectly shaped.

**To Reproduce**
> Steps to reproduce the behavior:

Use DWMBlurGlass on Windows 11 with dark mode on and look at titlebar buttons on active windows.

**Screenshots**
> If applicable, add screenshots to help explain your problem:

![Screenshot 2024-05-10 213320](https://github.com/Maplespe/DWMBlurGlass/assets/164842290/a7dac24b-4d01-4817-aab0-ca979f49f1f0)

The correct maximize button size is shown in green, this is shown on inactive windows only.

![Screenshot 2024-05-10 213333](https://github.com/Maplespe/DWMBlurGlass/assets/164842290/02df3251-9d42-427f-a5b3-05f20594d096)

The incorrect maximize button size is shown in red, this is shown on active windows only.

**Additional information (please complete the following information):**
 > OS Version : [e.g. Windows 11 23H2.22631.3085]
 > Software Version : [e.g. 2.0.1]

Windows 11 23H2.22631.3527 (My Desktop)
Windows 11 23H2.22631.3447 (My Laptop)

DWMBG 2.2.0

**What other third-party software do you use:**
 > [e.g. windhawk mods xxx]

StartAllBack 3.7.9

**Additional context**

The only programs I installed that could have caused this is DWMBG and StartAllBack. It is happening on both my desktop and laptop computers. It seems to only happen with dark mode enabled in Windows settings and only on active windows.

Uninstalling DWMBG and StartAllBack did not fix the problem, so it might be a bug in Windows. I thought DWMBG was the most likely culprit since it messes with DWM and the titlebar buttons.

**Comment by Maplespe** [comment]
If you don't enable the “Restore Win7 style title bar button size” option DWMBlurGlass will not modify the button size anyway.
DWMBlurGlass is a memory injection, which is disabled after uninstallation and reboot, and cannot modify any system files.
So this is most likely a Windows bug and my system version does not have this problem (22631.3447).
I suggest you update your system version.

**Comment by SandTechStuff** [comment]
It does not occur using the default Windows 11 light theme, but occurs when using the default Windows 11 dark theme. The theme doesn't seem to matter, just if the system is in dark mode or not.

**Comment by Maplespe** [comment]
I'm pretty sure it's a system issue, even though a brand new system should be.
If you insist that DWMBlurGlass is the cause, we suggest you try a whole new system.

**Comment by SandTechStuff** [comment]
@Maplespe Does this mean you were able to reproduce the issue without DWMBG on a fresh VM? I do not have access to another machine and have no VM software set up to test myself.

Seems like my issue caused a whole rewrite of the issue rules, whoops. 😅

**Comment by Maplespe** [comment]
Yes, I'm sure this is happening on brand new Windows.
I got other people to test it, and they just bought new computers with new systems not too long ago, and they also have this problem. It's a Windows bug.
