### ISSUE TITLE
Left border of maximized open/save dialogs

### ISSUE THREAD

**Issue by aubymori** [Maplespe/DWMBlurGlass#320]
**Describe the bug**
The left border of maximized open/save dialogs does not have the glass effect applied and is entirely see-through. This happens due to the weird pseudo-maximized state\* these windows are in.

**To Reproduce**
1. Make sure DWMBlurGlass is enabled and you are using a theme which has visually thick borders (e.g. Aero Lite, any Windows 7 theme)
2. Open any open/save dialog (e.g. File > Open in Notepad)
3. If it isn't already, maximize the window by double clicking the titlebar
4. You will see that the effect does not apply on the left border of the window

**Screenshots**
![image](https://github.com/Maplespe/DWMBlurGlass/assets/44238627/f1c15664-5c42-4089-a269-9c82ec1b3797)

**Additional information (please complete the following information):**
 > OS Version : Windows 10 21H2 (19044.4291)
 > Software Version : 2.2.0

**What other third-party software do you use:**
None

**Additional context**
I have confirmed that this does *not* happen without DWMBlurGlass.

\*This weird pseudo-maximized state has some attributes of maximized windows (e.g. caption icon and text offset being reduced) and doesn't have others (titlebar height reduction, borders off screen)

**Comment by aubymori** [comment]
Looks like this just happens to any window with the `WS_MAXIMIZE` style. This HTML help bug with hiding the sidebar is definitely the easiest to reproduce though.
![image](https://github.com/Maplespe/DWMBlurGlass/assets/44238627/5dbe9f8e-e099-40cf-994f-42824fe1c797)
Notepad with `WS_MAXIMIZE` manually added:
![image](https://github.com/Maplespe/DWMBlurGlass/assets/44238627/1dd653b0-cadd-4fe2-a956-c731b58afae4)

**Comment by ALTaleX531** [comment]
That's a good indication of the flaws in the current framework, but fortunately the new framework for the upstream project is perfectly fine. 
Anyway, thanks for the feedback.
![image](https://github.com/Maplespe/DWMBlurGlass/assets/105535231/46d55af8-9851-4983-867a-a376c87fa4f8)
