### ISSUE TITLE
Aero glass no longer installs and the symbol files cannot be downloaded on the latest update.

### ISSUE THREAD

**Issue by OleExploder** [Maplespe/DWMBlurGlass#324]
Bug:

When Windows 10 updated again, aero glass stopped working and I cannot get it to work again nor can I download the symbol files needed via the program.

Screenshot:
![Capture 1](https://github.com/Maplespe/DWMBlurGlass/assets/113773450/57dcefc6-735d-4b66-b48c-5a3bc0affae1)

OS Version: Windows 10 22H2 (OS Build 19045.4412)
Software Version: 2.2.0

Windhawk mods: 
Aerexplorer, Control Panel Reborn, Remove UWP titlebars, Arero Flyout Fix, Aero Tray, Eradicate Immersive Menus, Force thick frames, Legacy File Copy, Message Box Fix

**Comment by Kenst1092** [comment]
Concur that this is occurring after updating my Windows 11 to build 22631.3593.

Because I'm nosy, inputting the link into the browser says "You have reached this page because either you or an application that you are running has tried to retrieve debugging data from Microsoft. The requested data is either not available or needs to be retrieved by using the latest Microsoft Symbol Server technology. The data at this site is not accessed from a web browser. Instead, it is accessed by the symbol server technology that ships as part of the Debugging Tools for Windows and Visual Studio."

OS Version: Windows 11 23H2 build 22631.3593
Software version: 2.2.0

Windhawk mods: None

![image](https://github.com/Maplespe/DWMBlurGlass/assets/20787137/24ed1723-542a-4df9-be50-a037e3a55cdb)

**Comment by Dhyfer1** [comment]
>![image](https://github.com/Maplespe/DWMBlurGlass/assets/20787137/24ed1723-542a-4df9-be50-a037e3a55cdb)

What did you use to make the About Windows window have a dark theme?

**Comment by Dhyfer1** [comment]
>![image](https://github.com/Maplespe/DWMBlurGlass/assets/20787137/24ed1723-542a-4df9-be50-a037e3a55cdb)

What did you use to make the About Windows window have a dark theme?

**Comment by DiRG3** [comment]
Having the same issue here, same build: 22631.3593. Downloading symbols fails

**Comment by Maplespe** [comment]
This is not a DWMBlurGlass issue or bug.
Microsoft does not provide symbols for this version, but usually does after a week after the update.

**Comment by Dhyfer1** [comment]
> This is not a DWMBlurGlass issue or bug.
> Microsoft does not provide symbols for this version, but usually does after a week after the update.

If I had known that before I would have made a backup. Is it possible to download the symbols manually?

**Comment by Dhyfer1** [comment]
> This is not a DWMBlurGlass issue or bug.
> Microsoft does not provide symbols for this version, but usually does after a week after the update.

If I had known that before I would have made a backup. Is it possible to download the symbols manually?

**Comment by Maplespe** [comment]
Manual or automatic downloads are the same, because Microsoft servers don't provide symbols for this version at all.
It's just that with manual downloads you get an additional error message “This file could not be found”.

If you insist on trying it, download and unzip this script, copy your uDWM.dll and dwmcore.dll to the script directory, then run “download.cmd” and wait a while and you should get some information.
[symchk.zip](https://github.com/Maplespe/DWMBlurGlass/files/15315979/symchk.zip)

**Comment by Dhyfer1** [comment]
I understand, well someone do it for me. I won't be able to use my PC for another 10 hours, so i just be patient and wait for Microsoft to make the new symbols available, I hope it's soon.

**Comment by Dhyfer1** [comment]
I understand, well someone do it for me. I won't be able to use my PC for another 10 hours, so i just be patient and wait for Microsoft to make the new symbols available, I hope it's soon.

**Comment by SandTechStuff** [comment]
Just updated to the new Windows 11 build and the symbol download seems to have worked for me. Maybe try now?

![Untitled](https://github.com/Maplespe/DWMBlurGlass/assets/164842290/9e9cd5c5-51f3-4d1c-9264-21f3a55c33cd)

**Comment by OleExploder** [comment]
I just tested it and it works now. I also want to apologize for this not being an issue with the actual program so I am sorry for not thinking about that first.

**Comment by Kenst1092** [comment]
Yup, it is working. Just had to give Microsoft some time to put the symbols up for the new version

![image](https://github.com/Maplespe/DWMBlurGlass/assets/20787137/9300d4d0-2538-47f3-9fb4-14e1afa50073)

**Comment by Skyyblaze** [comment]
> Yup, it is working. Just had to give Microsoft some time to put the symbols up for the new version
> 
> ![image](https://private-user-images.githubusercontent.com/20787137/330855490-9300d4d0-2538-47f3-9fb4-14e1afa50073.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU3ODgwODksIm5iZiI6MTcxNTc4Nzc4OSwicGF0aCI6Ii8yMDc4NzEzNy8zMzA4NTU0OTAtOTMwMGQ0ZDAtMjUzOC00N2YzLTlmYjQtMTRlMWFmYTUwMDczLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE1VDE1NDMwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY4MTRiZGU0YWJhNDk3OWU0MmMyYTA2MDVjODQ1NWUxNmU0MzBhMmRlODk4M2NiOWYzMjk0YjFjYWIyOWQwZWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.yJqwHbCmDuPhIC6OwfTuvlZr4uJgVmBt6Kgt5gx4Qbs)

@Kenst1092 My apologies for the off-topic but how did you get the "About" windows transparent?

**Comment by Skyyblaze** [comment]
> @Kenst1092 Apart from what @Skyyblaze said, I also want to know what you did to make the explorer transparent?

@Dhyfer1 that's possible with ExplorerBlurMica: https://github.com/Maplespe/ExplorerBlurMica

**Comment by Dhyfer1** [comment]
> > @Kenst1092 Apart from what @Skyyblaze said, I also want to know what you did to make the explorer transparent?
> 
> @Dhyfer1 that's possible with ExplorerBlurMica: https://github.com/Maplespe/ExplorerBlurMica

Thanks. Now I also want to know what you want to know

**Comment by Kenst1092** [comment]
@Dhyfer1 @Skyyblaze I use ExplorerBlurMica, from Maplespe, as previously mentioned.

Moreover, I use Mica For Everyone to extend blur to other windows that aren't Explorer (and aren't UWP/WinUI/whatever), then use DWMBG to define the type of blurring I want.

**Comment by Dhyfer1** [comment]
@Kenst1092 ok, thx. By the way, what did you use to make the About Windows window have a dark theme as you can see in the first image you uploaded? DWMBlurGlass doesn't do that, I don't know if you did it with MicaForEveryone or are you using a third party theme?

**Comment by Dhyfer1** [comment]
@Kenst1092 ok, thx. By the way, what did you use to make the About Windows window have a dark theme as you can see in the first image you uploaded? DWMBlurGlass doesn't do that, I don't know if you did it with MicaForEveryone or are you using a third party theme?

**Comment by Kenst1092** [comment]
> @Kenst1092 ok, thx. By the way, what did you use to make the About Windows window have a dark theme as you can see in the first image you uploaded? DWMBlurGlass doesn't do that, I don't know if you did it with MicaForEveryone or are you using a third party theme?

@Dhyfer1 I'm using a third party customization pack, called Rectify11. Upon installation it comes with light, partial dark, and "dark with Mica" (which is essentially black). I'm using the "dark with Mica" theme out of that pack.

**Comment by Skyyblaze** [comment]
> @Dhyfer1 @Skyyblaze I use ExplorerBlurMica, from Maplespe, as previously mentioned.
> 
> Moreover, I use Mica For Everyone to extend blur to other windows that aren't Explorer (and aren't UWP/WinUI/whatever), then use DWMBG to define the type of blurring I want.

Interesting, thanks for the explanation about Rectify11 too, that explains why it doesn't work for me.

**Comment by Kenst1092** [comment]
I've made some edits to my previous comment about Rectify11 for clarity.

**Comment by Dhyfer1** [comment]
@Kenst1092 Looks great, I thought I'm going to use Rectify11 too. Ok, that's all and thank you

**Comment by Dhyfer1** [comment]
@Kenst1092 Great, thanks for sharing, now everything is clear. I didn't know Rectify11 could achieve that

**Comment by xuan06zyx** [comment]
> 刚刚更新到新的 Windows 11 版本，符号下载似乎对我有用。也许现在就试试？
> 
> ![无标题](https://private-user-images.githubusercontent.com/164842290/330669372-9e9cd5c5-51f3-4d1c-9264-21f3a55c33cd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYwMTQwMjAsIm5iZiI6MTcxNjAxMzcyMCwicGF0aCI6Ii8xNjQ4NDIyOTAvMzMwNjY5MzcyLTllOWNkNWM1LTUxZjMtNGQxYy05MjY0LTIxZjNhNTVjMzNjZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxOFQwNjI4NDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02NzRjZWU0MzQyYWQxYTM4N2JjYWI3ZGUzMTQyNzNiYmFmOWE1ODYxODM3NjIzMTUzMzg2MzFkOTEyMjg0MDY4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.jtWbxxNzWmlW-Qw9YCXK7AkcSsjQhntfy3wJtDjx51E)
![image](https://github.com/Maplespe/DWMBlurGlass/assets/126635659/238213d8-c81e-449d-9cbd-da44e1ba480c)
Until now, I still can't do it
