### ISSUE TITLE
Add an option to replace ExplorerBlur (OldBlur) system-wide with the new shader.

### ISSUE THREAD

**Issue by ImSwordQueen** [Maplespe/DWMBlurGlass#326]
**Describe the solution you'd like**
Have an option that replaces explorerblur (OldBlur) with the new shader. some stuff (Example: SIB taskbar thumbnails/jumplists) have hardcoded ExplorerBlur which doesn't quite follow the settings of the new shader exactly.

**Your reason (tell us why we need it)**
ExplorerBlur can be quite laggy sometimes so having a way to use CustomBlur as a total replacement would be quite useful.

**Describe alternatives you've considered**
SIB has an option to use acrylic in the taskbar but it will always use ExplorerBlur for jumplists/taskbar thumbnails no matter what.

**Additional context**
This feature could be added to "Override AccentBlur".

**Comment by Maplespe** [comment]
As long as you check “Override AccentBlur” it will override OldBlur.
If it is not overridden, then it is not OldBlur(AccentBlur).
I'm sure the taskbar taskbar jump list has been overwritten and you can see the aero reflection from CustomBlur on it.

**Comment by ImSwordQueen** [comment]
> As long as you check “Override AccentBlur” it will override OldBlur. If it is not overridden, then it is not OldBlur(AccentBlur). I'm sure the taskbar taskbar jump list has been overwritten and you can see the aero reflection from CustomBlur on it.

Weird because this section here has the same issues as OldBlur (having the mouse cursor lag and other oddities that oldblur has) even with “Override AccentBlur” enabled.
![image](https://github.com/Maplespe/DWMBlurGlass/assets/52015098/58487ca0-bf6c-472e-9f50-22f412248352)

**Comment by Maplespe** [comment]
Changing the effect of StartIsBack to “Blur” and restarting the explorer process will ensure that it is overwritten.
If there are any other problems, this should have nothing to do with DWMBlurGlass.

**Comment by ImSwordQueen** [comment]
> Changing the effect of StartIsBack to “Blur” and restarting the explorer process will ensure that it is overwritten. If there are any other problems, this should have nothing to do with DWMBlurGlass.

I tried enabling blur in StartIsBack and the cursor still lags behind

**Comment by TheInsane101** [comment]
It's such a shame how many issues Startisback has with DWMBG, probably bc it was never designed with it in mind since DWMBG is so new.
