### ISSUE TITLE
AccentBlur override on SIB++ doesn't render all layers before applying

### ISSUE THREAD

**Issue by catneptune** [Maplespe/DWMBlurGlass#329]
Title pretty much explains it all, some screenshots
![image](https://github.com/Maplespe/DWMBlurGlass/assets/144282272/895a5d17-56d4-4c5c-a901-d45be0cfac74)
I've heard that a fix is coming out soon but it hasn't arrived to the test branch yet, is there any ETA for this?

To reproduce (atleast these are things I have done), I am pretty sure you just have to enable accent override, and then most of the time it'll happen, a way to "fix" it is by restarting explorer, but that's pretty annoying to do every boot.

**Comment by SandTechStuff** [comment]
Pretty sure this happens on Windows 11 with StartAllBack aswell. (Color should be Windows 7 Sky.)

> ![Screenshot 2024-05-16 212343](https://github.com/Maplespe/DWMBlurGlass/assets/164842290/b29dd8a5-716d-41bc-bdc0-b0f58ff7131b)
With Bug

> ![Screenshot 2024-05-16 212354](https://github.com/Maplespe/DWMBlurGlass/assets/164842290/9f8f2a7a-90c2-4fce-a274-aeb6e8cc1e2c)
Without Bug
