### ISSUE TITLE
Change Office default Mica effect

### ISSUE THREAD

**Issue by FlyFireF** [Maplespe/DWMBlurGlass#330]
**Solution I'd like**
> Can or Will this software apply to Office softwares?

**Reason**
> The effects cannot be applied to Office softwares, and they just keep default Mica effect.

**Comment by Maplespe** [comment]
If you check the “`Override DWMAPI effect`” box and still can't override it, the application may not be a Win32 application or it doesn't use dwmapi directly.
This is beyond the scope of this project.
This project can only manipulate DWM processes, any other processes are out of the scope of this project.
