### ISSUE TITLE
The changes in Start menu & Taskbar effects & blur is very low & imperceptible on Windows 11

### ISSUE THREAD

**Issue by h-balani** [Maplespe/DWMBlurGlass#331]
**Describe the bug**
> The changes applied In windows 11 to Titlebar are not applied in the same way to the Windows 11 Start menu and Taskbar, and the changes to the Start menu and Taskbar are very small and almost do not change.
Please watch the uploaded video:
https://drive.google.com/file/d/1ecQ0Hyzj5hsKIgqQD-7zkwDqMaXCxP0n/view?usp=drive_link

Description ....

**To Reproduce**
> Steps to reproduce the behavior:

Description ....

**Screenshots**
> If applicable, add screenshots to help explain your problem:

**Additional information (please complete the following information):**
 > OS Version : [e.g. Windows 11 23H2.22631.3085]
 > Software Version : [e.g. 2.0.1]

**What other third-party software do you use:**
 > [e.g. windhawk mods xxx]

None

**Additional context**

**Comment by Maplespe** [comment]
DWMBlurGlas can only modify the global blur, not its effect, nor can it replace its effect unless the process actively calls dwmapi.
I've explained this before.
Obviously the global blur feature of DWMBlurGlas is in effect and working fine in your video.
The reason it's hard to notice is that the taskbar has a secondary coloring and it's an Acrylic effect, not a regular Blur.

**Comment by Maplespe** [comment]
What you need to know is that File Explorer's title bar is actively calling dwmapi, so DWMBlurGlass can replace its Mica effect completely with DWMBlurGlass's custom effect.

While the taskbar is an Acrylic effect, using win2D's AcrylicBrush, and not calling dwmapi. so DWMBlurGlass can't directly replace it, we can only modify the Gaussian Blur part of DWM that was last executed to modify its blurring degree, but not replace it That's the point and the reason for this difference.
win2D is a toolkit for winUI, which contains the package of UI effects.
These operations are done entirely in dcomp and user process, nothing to do with DWM, only the last Gaussian blur is done in DWM.

**Comment by h-balani** [comment]
Thank you for your reply.
Your app is the best app to change transparency and blur in Windows 11 & Windows 10.
 Before your program there was another program called AeroGlass8 which changed transparency and blur only for windows 8 and 10 and was written by a software developer. for every new Build of Windows every year, an update came for AeroGlass8 to be executable in new Version of windows.
As far as I remember After the release of Windows 10 Build 1909, this program was no longer updated and thus could no longer be used.
After that, I tried many programs to change the transparency and opacity of Windows such as TransculentBT & Stardock Windows Blinds & Stardock Start11, but these programs had limited features and possibilities to change the transparency and opacity.
Until I met your program a few days ago. fantastic. It has many possibilities to change transparency and blur.
thank you so much.
You are great.

**Comment by sebastianmatvievschi** [comment]
can help me get download
