### ISSUE TITLE
Symbol files download fails

### ISSUE THREAD

**Issue by Brawg** [Maplespe/DWMBlurGlass#336]
> **Download failed! Unable to download symbol files from "msdl.microsoft.com".** <

This is now since I had a little Windows update. Just not sure if there's anything I can do to fix that. 

![DWMsymbol](https://github.com/Maplespe/DWMBlurGlass/assets/124517510/74778dc2-0ae9-4d12-a6ad-7d9240c231d9)

I am on W11 23H2 22631

**Comment by Starstrike** [comment]
This is going to happen with just about every update. Have to just keep trying until it downloads them. It simply means that the symbols for our version aren't uploaded to the symbol server yet.

Nothing the dev can do about this.
