### ISSUE TITLE
Incompatibility with ExplorerBlurMica causing Explorer windows to become fully transparent

### ISSUE THREAD

**Issue by SKCro** [Maplespe/DWMBlurGlass#338]
**Describe the bug**
> A clear and concise description of what the bug is:

For some reason, recent versions of DWMBlurGlass seem to have some sort of incompatibility with ExplorerBlurMica, causing Explorer windows to become completely transparent. This is temporarily fixed by restarting Explorer, but comes back when an Explorer window is unfocused and refocused. I have also filed a bug report under ExplorerBlurMica (because I'm not sure which is causing the bug), available [here](https://github.com/Maplespe/ExplorerBlurMica/issues/147).

**To Reproduce**
> Steps to reproduce the behavior:

1) Install DWMBlurGlass and change some settings.
2) Install ExplorerBlurMica while DWMBlurGlass is enabled.
3) Explorer windows will become completely transparent with no blur, no matter what settings are used. Disabling DWMBlurGlass seems to fix this problem.

**Screenshots**
> If applicable, add screenshots to help explain your problem:

Screenshots aren't really enough to describe the problem, so here's a screen recording showing off the bug:

https://github.com/Maplespe/ExplorerBlurMica/assets/55817746/5eaadfca-72cf-472a-a553-f43d13adadcd

**Additional information (please complete the following information):**
 > OS Version : [e.g. Windows 11 23H2.22631.3085]
 > Software Version : [e.g. 2.0.1]

Windows 10 IoT LTSC 2021 - 21H2, Build 19044.4412
DWMBlurGlass 2.2.0 (Latest)
ExplorerBlurMica 2.0.1 (Latest release, apparently)

**What other third-party software do you use:**
 > [e.g. windhawk mods xxx]

ExplorerBlurMica :P

**Additional context**
Other versions of ExplorerBlurMica still cause the bug, so it might be an incompatibility within DWMBlurGlass. Other users have reported the same issue in the other bug report.

**Comment by yungoxigen** [comment]
I am having the same issue. Have you been able to fix it?

**Comment by SKCro** [comment]
> I am having the same issue. Have you been able to fix it?

I have found that sometimes I can get it to work if I disable DWMBlurGlass, enable ExplorerBlurMica, then re-enable DWMBlurGlass. However, the bug comes back if I change any settings within DWMBlurGlass and save.

**Comment by tails101** [comment]
yea doesn't work on windows 10 but work on windows 11 with effect 2 from my tests.

**Comment by enoversum** [comment]
I can confirm, it makes it not suitable for using it together with ExplorerBlurMica.

**Comment by SKCro** [comment]
> I can confirm, it makes it not suitable for using it together with ExplorerBlurMica. Windows 11 here. .

The developer marked this as "solved in upstream project" months ago, yet there has been no further communication about a release that solves this issue. I understand that it might be taking a while since, from what I can gather, it's a big backend rewrite that aims to solve several issues and improve performance, but there hasn't really been much communication on progress lately.

**Comment by enoversum** [comment]
> One of the developers marked this issue as "solved in upstream project" months ago, yet there has been no further communication about a release that solves this issue. I understand that it might be taking a while since, from what I can gather, it's a big backend rewrite that aims to solve several issues and improve performance, but there hasn't really been much communication on progress lately.

Yeah, I've seen. I guess it's sitting in some kind of update that needs more work. Apart from that, they don't owe us anything. And you can use another blur mode in DWMBlurGlass to circumvent the behaviour for the time being, so all's not lost.

**Comment by SKCro** [comment]
> > One of the developers marked this issue as "solved in upstream project" months ago, yet there has been no further communication about a release that solves this issue. I understand that it might be taking a while since, from what I can gather, it's a big backend rewrite that aims to solve several issues and improve performance, but there hasn't really been much communication on progress lately.
> 
> Yeah, I've seen. I guess it's sitting in some kind of update that needs more work. Apart from that, they don't owe us anything. And you can use another blur mode in DWMBlurGlass to circumvent the behaviour for the time being, so all's not lost.

That's fair enough, the devs can take as long as they want because, as you said, they don't owe us anything. I just thought maybe a quick status update from them would be kinda nice, but it isn't required. Anyway, I didn't know changing the blur method could fix the issue, actually. Might try that out later - thanks for the tip!

**Comment by enoversum** [comment]
> > > One of the developers marked this issue as "solved in upstream project" months ago, yet there has been no further communication about a release that solves this issue. I understand that it might be taking a while since, from what I can gather, it's a big backend rewrite that aims to solve several issues and improve performance, but there hasn't really been much communication on progress lately.
> > 
> > 
> > Yeah, I've seen. I guess it's sitting in some kind of update that needs more work. Apart from that, they don't owe us anything. And you can use another blur mode in DWMBlurGlass to circumvent the behaviour for the time being, so all's not lost.
> 
> That's fair enough, the devs can take as long as they want because, as you said, they don't owe us anything. I just thought maybe a quick status update from them would be kinda nice, but it isn't required. Anyway, I didn't know changing the blur method could fix the issue, actually. Might try that out later - thanks for the tip!

Totally understood. It would be very lovely to get to know if there is an actual fix in the works, absolutely. They'll reveal at some point :) . And yes, I believe the two other blurring modes should be compatible with ExplorerBlurMica. Working on my machine, that is.

**Comment by altico58-stack** [comment]
No issue or incompatibility here, I use both for some time now without any problems. Probably the incompatibility is not between the two programs, but it arises from the global SW configuration and continuous Windows updates, which I disabled long ago.
