### ISSUE TITLE
DWM Blur Glass still not working after restarting.

### ISSUE THREAD

**Issue by Latek11** [Maplespe/DWMBlurGlass#339]
Hi, I've been having an issue with DWM Blur Glass not working after restarting my pc. I downloaded the newest version and it still won't work. I dont know if its a issue with my computer or what. I was trying to fix the problem like downloading the new version again, or making a task in the task scheduler. But I still got nothing.

**Comment by Starstrike** [comment]
What version of Windows are you on? Look in winver. This app broke when 24H2 came out, it's not just the symbols. Going to need an update to get it working again.

**Comment by HuskyHacker25** [comment]
using 24H2 as well, DWMBlurGlass opens, but doesn't apply the transparency effect.

**Comment by Latek11** [comment]
(Btw im on windows 10 22H2)

**Comment by Starstrike** [comment]
Can you post a screenshot of what error you're getting when trying to run it? Or a screen recording?

**Comment by morrysillusion** [comment]
i am also having this issue, i am on win 10 22h2. thing is, there is no error message. all i do is restart my pc and the effect isnt on the windows. when i start the exe manually, the effect is back but only after checking and unchecking an option and saving again (doesnt seem to matter what option it is for me, its just saving it again)

**Comment by tamr** [comment]
@morrysillusion  have you tried to redownload the symbol files on the Symbols tab? This fixed the issue after KB5041580 update for me.

**Comment by morrysillusion** [comment]
i did when i first installed it, and it shows that it is valid
![image](https://github.com/user-attachments/assets/d0c1f212-11dd-432e-9c13-1a31b8426e81)

in the folder for the program there is a "symbols" folder that has files in it as well

![image](https://github.com/user-attachments/assets/948cd729-35c2-462e-a8fb-4a3a573ea576)

i installed this all on 8/16 and it looks like the KB5041580 update came out on 8/13 so i believe it should work in that case

**Comment by LittleFox2024** [comment]
I just figured out that there is an issue with the scheduled task. If you are not using the account that you installed DWMBlurGlass, it will not open.
![Capture (2)](https://github.com/user-attachments/assets/8528ea70-72af-41ef-9539-5268c0a03a59)

You have to manually change it to when **ALL** users are logged in, not just the one used to create it.

**Comment by Latek11** [comment]
Thanks for the response! It works!  
     
      
       
        Dnia 09 października 2024 19:42 LittleFox2024 ***@***.***&gt; napisał(a):
       
    
       
         
 I just figured out that there is an issue with the scheduled task. If you are not using the account that you installed DWMBlurGlass, it will not open.  
 github.com Capture.2.PNG (view on web) 
 You have to manually change it to when  ALL  users are logged in, not just the one used to create it.
