### ISSUE TITLE
Startisback became opaque black color when I turn on my computer from shutdown (even restart) until I toggle off then on the override accentblur effect.

### ISSUE THREAD

**Issue by ZyrusplaysAnimations** [Maplespe/DWMBlurGlass#340]
**Describe the bug**

The title explains it. That bug will happen if I use the Override AccentColor. The taskbar is normal on startup if I didn't toggle the Override AccentColor Option.

**To Reproduce**

1. Shut down the pc, power on, and sign in.
2. Taskbar is opaque, black color but retained the glass texture and color

**Screenshots**
![image](https://github.com/Maplespe/DWMBlurGlass/assets/70579850/4cf51f3e-ece8-48d7-b8ab-ab606f50b7ae)

**Additional information (please complete the following information):**
 OS Version : Windows 10 22H2 19045.4474
 Software Version : DWMBlurGlass v2.2.0

**What other third-party software do you use:**
Startisback++
OldNewExplorer
7+ Taskbar Tweaker

**Comment by nullgato** [comment]
Adding in that this also happens to me too, but also happens to the SiB start menu. The taskbar color settings can be reset upon login, the start menu sometimes can't.

**Additional information (please complete the following information)**
OS Version: Windows 10 22H2 19045.4412
Software Version: DWMBlurGlass v2.2.0

**What other third-party software do you use:**
Startisback++
OldNewExplorer
WinaeroTweaker
Windhawk

**Comment by ZyrusplaysAnimations** [comment]
Looks like the devs ignored this, also someone already reported this issue ( #329 ) Closing this issue.

**Comment by nullgato** [comment]
@ZyrusplaysAnimations have you double checked to make sure Windows isn’t in Dark Mode? Maybe I just got lucky, but as of last night that ended up being the problem for me. Seemed like SiB wasn’t respecting my custom choices when dark mode was on.

**Comment by ZyrusplaysAnimations** [comment]
> @ZyrusplaysAnimations have you double checked to make sure Windows isn’t in Dark/Light Mode (depending on what you’re trying to accomplish)? Maybe I just got lucky, but as of last night that ended up being the problem for me. Seemed like SiB wasn’t respecting my custom choices when dark mode was on.

I use Windows on light mode.
