### ISSUE TITLE
DWMBlurGlass installation fail-succeeds due OpenProcess failure

### ISSUE THREAD

**Issue by SigmaTel71** [Maplespe/DWMBlurGlass#341]
**Describe the bug**
DWMBlurGlass fails installing, claiming that OpenProcess failed, but reports itself installed. No visible effects on windows or their captions either.

**To Reproduce**
1. Get the last release of DWMBlurGlass from 'Releases' page here
2. Unpack it to a folder that does not require administrative privileges to do anything
3. Launch the app, click 'Install'

**Screenshots**
![image](https://github.com/Maplespe/DWMBlurGlass/assets/17989678/e97696de-a562-4d18-ac7e-0c1776c08237)

**Additional information:**
> OS Version : Windows 11 23H2.22631.3593
> Software Version : 2.2.0

**What other third-party software do you use:**
> ExplorerPatcher DWM Service to enable squared window corners

**Additional context**
User Account Control settings are enabled with the highest setting + enforced group policy to require credentials on secure desktop.
Used antivirus software is not Microsoft Defender, but disabling it does not make any changes.
Disabling ExplorerPatcher DWM service does not give any positive effect.

**Comment by tilsgee** [comment]
same here. but not due to OpenProcess

<img width="305" alt="image" src="https://github.com/Maplespe/DWMBlurGlass/assets/62179071/475150d2-0489-4e16-8ba7-7a47c814afe3">

**Comment by ALTaleX531** [comment]
@SigmaTel71 It seems like you're not granting enough permissions to DwmBlurGlass, which is obvious.

**Comment by SigmaTel71** [comment]
> @SigmaTel71 It seems like you're not granting enough permissions to DwmBlurGlass, which is obvious.

Want me to try disabling UAC prompts at all? I think it's unrelated, as elevation is usually inherited. It would be also useful to check in OpenProcess error prompt which process it failed opening.

**Comment by SigmaTel71** [comment]
> DwmBlurGlass needs access to the DWM process in order to inject the component.

Hm... I think I remember why full-fledged ExplorerPatcher failed to enable square corners on its own but unpacked ep_dwm executable flawlessly worked.
But why I get two error messages on OpenProcess? Does DWMBlurGlass attempt to patch it at least two times?

**Comment by ALTaleX531** [comment]
DwmBlurGlass works by patching memory after injecting into the DWM process. Two error messages do not represent OpenProcess twice, and the other error message represents nothing to do with OpenProcess. You should think for yourself what special settings you have made for Windows, there is nothing more I can do to help you.

**Comment by SigmaTel71** [comment]
> You should think for yourself what special settings you have made for Windows, there is nothing more I can do to help you.

Got it, will try to find a spare minute to investigate.

**Comment by SigmaTel71** [comment]
Research in progress... I tried stopping DWM via commonly used way of suspending winlogon and killing DWM process, but no luck there. DWMBlurGlass freezes when installed if winlogon is suspended. Is DWM always a descendant to winlogon in cases of successfull DWMBlurGlass installations?

**Comment by shikulja** [comment]
I got this error after updating w11 24h2

**Comment by SigmaTel71** [comment]
The problem went away when I reinstalled Windows 11 from scratch and went for 24H2. Nothing else to say there...
