### ISSUE TITLE
Acrylic transparancy makes the cursor lag after a random amount of time

### ISSUE THREAD

**Issue by ImSwordQueen** [Maplespe/DWMBlurGlass#343]
**Describe the bug**
A feature that i described in the issue #326 for the weird problems with the mouse cursor and oldblur were caused by a different issue in DwmBlurGlass related to acrylic. For some reason, acrylic surfaces (as an example action center is one that causes big lag) would cause stutters and sometimes crashes. Disabling acrylic (ForceEffectMode 1) makes the lag disappear entirely.

**To Reproduce**
> Steps to reproduce the behavior:
1. Install DWMBlurGlass.
2. Wait a few minutes with a few windows open
3. Open action center
4. the mouse cursor should be slower than usual

**Screenshots**
> If applicable, add screenshots to help explain your problem:

**Additional information (please complete the following information):**
OS Version : Windows 10 21H2 Build 19044.4291
Software Version : 2.2.0 (From the releases page)

**What other third-party software do you use:**
 > [e.g. windhawk mods xxx]

StartIsBack++ 2.9.20
Windhawk is installed but the bug still occurred with it closed. 

**Additional context**
Even with "Override blur" and "Override AccentBlur effect" the bug would still occur. 

This bug isn't present in OpenGlass

I'm using a RTX 3060 ti on Version 552.44 of the official NVIDIA drivers.

**Comment by ALTaleX531** [comment]
The problem is actually quite simple, the action center itself uses both accent and acrylic, and DwmBlurGlass doesn't remove accent completely, which means that three surfaces have to be rendered at the same time, which surely has a significant negative influence on performance.

**Comment by ALTaleX531** [comment]
OpenGlass completely removes accent, which greatly reduces the performance impact, but is very experimental and other issues may occur.
