### ISSUE TITLE
DWMBlurGlass crashes randomly when opening File Explorer/programs, causing Win7 title bar fix to not work

### ISSUE THREAD

**Issue by ghost** [Maplespe/DWMBlurGlass#346]
**Describe the bug**
> A clear and concise description of what the bug is:

DWMBlurGlass is consistently and randomly crashing whenever opening a program (any and all) and/or opening File Explorer window, causing the title bar to revert back to old default size.

**To Reproduce**
> Steps to reproduce the behavior:

Restarting PC; DWMBlurGlass will crash again after some minutes _(opening File Explorer window or any program)_ and will keep happening randomly, regardless. **Title bar is always broken when DWMGBlurGlass crashes.**
After DWM crashes, I try to untick and re-tick **_Restore Win7 style title bar size_** and hit save and it does nothing; the title bar is still default fat-sized)

**Screenshots**
> If applicable, add screenshots to help explain your problem:
![Untitled](https://github.com/Maplespe/DWMBlurGlass/assets/172628964/ea93cf61-41a5-4100-9d4c-61b1d8f8c298)
**_Windows title bar going back to default size (fat) after DWMBlurGlass crashes_**

**Additional information (please complete the following information):**
 > OS Version : **Windows 10 22H2 Build 19045.4529**
 > Software Version : [2.2.0]

**What other third-party software do you use:**
 > [e.g. windhawk mods xxx]

**StartIsBack and DWMBlurGlass** **_(for Windows 7 title bar height)_**

**Additional context**
Restart PC again; **_Restore Win7 style title bar size_** is OK, **_but_**, DWMBlurGlass **will** inevitably crash again when opening any program after some minutes (~2-5 minutes after logon) and when it crashes it always reverts the title bar back to default (fat) size as shown in the screenshot attached.

**Comment by SIX10** [comment]
I'm using some windhawk stuff plus Aero10 from DeviantART and clicking the titlebar fix makes my screen go black and computer unbootable! Had to go into safemode and manually disable DWMBlurGlass to fix
