### ISSUE TITLE
DWMBlurGlass stoped working after windows 10 update

### ISSUE THREAD

**Issue by MichaelPro999** [Maplespe/DWMBlurGlass#347]
getting this errors at startup and DWMBlurGlass does not work anymore.

![Capture](https://github.com/Maplespe/DWMBlurGlass/assets/156245690/ef483297-8147-435b-ac8d-0476b7fd4f91)
![Capture  2PNG](https://github.com/Maplespe/DWMBlurGlass/assets/156245690/be1a0710-e31a-48dc-b808-905e9cacfd48)
![Capture 3](https://github.com/Maplespe/DWMBlurGlass/assets/156245690/442f7f97-7ae1-4cb1-88b9-e82a8f06c709)

**Comment by Bungeetaco** [comment]
If you open the DWMBlurGlass GUI and go to the Symbols tab, do you have the option to re-download the symbols?

**Comment by MichaelPro999** [comment]
> If you open the DWMBlurGlass GUI and go to the Symbols tab, do you have the option to re-download the symbols?

okay now it is seems to be working, i re-download the symbols in the Symbols tab and it is works, thanks
