### ISSUE TITLE
Windows LTSC 64bit 24H2 (iot) Erro... 

### ISSUE THREAD

**Issue by edivanbaptista** [Maplespe/DWMBlurGlass#349]
Windows LTSC 64bit  (iot) Erro... 

![Untitled](https://github.com/Maplespe/DWMBlurGlass/assets/40346205/51cba26d-c9cc-4382-9dd5-ca00162c5bb3)

**Describe the bug**
> A clear and concise description of what the bug is:

Description ....

**To Reproduce**
> Steps to reproduce the behavior:

Description ....

**Screenshots**
> If applicable, add screenshots to help explain your problem:

**Additional information (please complete the following information):**
 > OS Version : [e.g. Windows 11 23H2.22631.3085]
 > Software Version : [e.g. 2.0.1]

**What other third-party software do you use:**
 > [e.g. windhawk mods xxx]

None

**Additional context**

**Comment by edivanbaptista** [comment]
Wnver Windows LTSC 64bit Eterprise (IoT) Erro...

**Comment by Maplespe** [comment]
Quoted in ReadMe: 
> ## Compatibility
> Supported as low as Windows 10 2004 and as high as the latest version of Windows 11 (Some blurring methods are **not supported in Windows Insider versions**).
