### ISSUE TITLE
Image of reflection ends at laptop size

### ISSUE THREAD

**Issue by Baakun** [Maplespe/DWMBlurGlass#35]
![NVIDIA_Share_z6KJNfLpUu](https://github.com/Maplespe/DWMBlurGlass/assets/51994675/e2ad2880-67cb-4b6e-a832-8d4fd00bef9b)
Reflection can't be applied properly on 2560x1440 resolution. Maybe using this with WindowBlinds causes it?
I'm making ja-JP lang file. Really appreciate for your creation.

**Comment by Maplespe** [comment]
This could be caused by WindowBlinds, I tested at both 2k and 1080p but everything is fine.

**Comment by Baakun** [comment]
> This could be caused by WindowBlinds, I tested at both 2k and 1080p but everything is fine.

I understood. Thank you for responding!
