### ISSUE TITLE
Are missing 17 `.cpp` files in the project, why are they not included with this Project?

### ISSUE THREAD

**Issue by Special-Niewbie** [Maplespe/DWMBlurGlass#350]
Hi,

I recently cloned the repository and attempted to compile the project to test around the code, but I encountered an issue where 17 .cpp files. Despite these files, appearing in the project structure within the IDE (Visual Studio), they are not physically present in the project directory. Why?

**Comment by TorutheRedFox** [comment]
according to readme.md,
"Since the GUI program uses private libraries, only insiders can compile the GUI, which does not affect the compilation of the libraries."
