### ISSUE TITLE
在Windoes11 24H2上CustomBlur模糊方式无法使用，其他正常

### ISSUE THREAD

**Issue by iatri** [Maplespe/DWMBlurGlass#351]
**Describe the bug**
> A clear and concise description of what the bug is:
如题，在24H2上CustomBlur模糊方法无法使用，其他模糊方法正常

**Screenshots**
> If applicable, add screenshots to help explain your problem:
![屏幕截图-DWMBlurGlass Error_2024-06-23_17-37-36](https://github.com/Maplespe/DWMBlurGlass/assets/141122842/d04d6b70-85a7-4611-a9cf-b0fe2d4c80f8)
![屏幕截图-设置_2024-06-23_17-55-54](https://github.com/Maplespe/DWMBlurGlass/assets/141122842/1a315c1a-dc2a-4249-a7d4-71de313836f5)

**Additional information (please complete the following information):**
 > OS Version : Windows 11专业版 24H2 26100.863
 > Windows Feature Experience Pack 1000.26100.6.0
 > Software Version : 2.2.0

**Comment by bfgxp** [comment]
同样26100.863，所有模糊方法都用不了

**Comment by Maplespe** [comment]
ReadMe里已经写了 不支持预览版系统

**Comment by kennylee60** [comment]
24H2已经是RTM了，还是有出错
