### ISSUE TITLE
Full Aero Glass Covered on the borderless windowed Games

### ISSUE THREAD

**Issue by 2013Windows81** [Maplespe/DWMBlurGlass#354]
While launching the Cyberpunk 2077 with borderless windows it showed me like this below, which is annoying. Please add an exclude option for the games otherwise it could be awful for me.

![image](https://github.com/Maplespe/DWMBlurGlass/assets/88513270/127532a8-db27-4ee6-9594-7dfcc054dfb4)

**Comment by pixel-creature** [comment]
I've had the same issue, it happens to me when I accidentally enable the Discord Overlay. if you have that or anything else that draws over applications like it does, try disabling and see if the issue persists or not.

**Comment by 2013Windows81** [comment]
yes fixed. that's the reason "Discord Overlay" was messed up. thanks!
