### ISSUE TITLE
启动程序时异常

### ISSUE THREAD

**Issue by hengxiaopi** [Maplespe/DWMBlurGlass#357]
**描述错误**
> 每一次开机或重新安装后会重启资源管理器、关闭夜间模式，同时弹窗报错

**截图**
> ![Clip_2024-06-30_10-56-28](https://github.com/Maplespe/DWMBlurGlass/assets/152491291/d57949ec-7ccf-40cd-9847-3b1e8546264a)

**其他信息**
 > 系统版本：
版本	Windows 11 家庭中文版
版本号	24H2
安装日期	‎2024/‎6/‎18
操作系统版本	26100.994
体验	Windows Feature Experience Pack 1000.26100.6.0
 > 软件版本：v2.2.

**Comment by BingLee1994** [comment]
我也是升级后不能用了

**Comment by Maplespe** [comment]
readme已经写了 不支持预览版系统 这不是bug

**Comment by hengxiaopi** [comment]
很喜欢这个软件，正在退出预览体验计划
![Clip_2024-07-14_14-24-34](https://github.com/user-attachments/assets/55299070-8936-4d07-8117-7942174a7a8c)
