### ISSUE TITLE
Blur behind text on titlebar like Windows 7 to make the text legible when opening stuff with dark backgrounds

### ISSUE THREAD

**Issue by GBX-GitHub** [Maplespe/DWMBlurGlass#359]
**Describe the solution you'd like**
> In Windows 7, the titlebar text is always black. The same is done here on DWMBlurGlass, but not the same as 7. Win7 adds a slight white blur behind the text in the titlebar to make it legible regardless of where or what's behind the thing you are opening. As an example, if you have a dark wallpaper, the blur will reflect that. Opening 'Run' on said wallpaper will cause the 'Run' text to not be seen at all as the black text blends into the wallpaper. On 7, a white blur is added to make the black text readable. 
**Your reason (tell us why we need it)**
> Massively improves readablility and makes DWMBlurGlass 1:1 with Windows 7 Aero

**Describe alternatives you've considered**
> Alternatives? I tried to make the text white, but then on white background you can't see the text. 

**Additional context**
![image](https://github.com/Maplespe/DWMBlurGlass/assets/103683824/19a1caef-dfd7-48e8-80ef-b2db54b36062) - Windows 7's Run box, notice the white blur effect behind the text to make it readable

![image](https://github.com/Maplespe/DWMBlurGlass/assets/103683824/3657647d-caec-4b24-b57d-898925fed838) - Windows 11's Run box using DWMBlurGlass. Notice how the text can't even be seen because of my wallpaper. Windows 7 under the same wallpaper does not have this issue.

**Comment by Maplespe** [comment]
Duplicates with https://github.com/Maplespe/DWMBlurGlass/issues/181, https://github.com/Maplespe/DWMBlurGlass/discussions/172.
DWMBlurGlass itself has text glowing support, but it depends on your theme, DWMBlurGlass will enable glowing if your theme properties require it.
