### ISSUE TITLE
Cant download Symbol file.

### ISSUE THREAD

**Issue by Shy-Doge** [Maplespe/DWMBlurGlass#36]
Every time I try to download it from the Symbol tab it gives me the following errors:

![image](https://github.com/Maplespe/DWMBlurGlass/assets/64466191/e5655b85-5bbf-4ffe-9922-1aa4eb4fc71b)
![image](https://github.com/Maplespe/DWMBlurGlass/assets/64466191/df1de77a-d35f-49c9-869c-66bb45771ace)

I am running Windows 11 23H2 (22631.3078)

**Comment by Maplespe** [comment]
Please check if you can access https://msdl.microsoft.com/
If you can't you may need a proxy server or to change your DNS.

**Comment by Shy-Doge** [comment]
I get this when I open it on a browser:

![image](https://github.com/Maplespe/DWMBlurGlass/assets/64466191/e4b23e67-086b-45f3-8aee-feda4548afc3)

**Comment by Maplespe** [comment]
1. Check if your files are complete, you need to include dbghelp.dll, symsrv.dll.
2. Check that the folder where your program is located has write permissions and has more than 20MB of space remaining.
3. Check your firewall settings to make sure that this program can access the Internet, and make sure that you don't have any other software or antivirus programs blocking the operation.

If none of the above methods work, please upload your `udwm.dll` and `dwmcore.dll` files
They are located at "`%windir%\System32`".
We can download them for you, but if you can't solve the problem, you'll need to download them again after the system is updated.

**Comment by Shy-Doge** [comment]
1. Both are there yes but I also re-downloaded the latest release just to make sure.
2. The program is in `C:\Program Files\DWMBlurGlass`, has full access and the folder is not write protected. I also have 56gb free on that drive.
3. Ive added rules on the firewall to allow the program to access the internet and still no luck.

[Files.zip](https://github.com/Maplespe/DWMBlurGlass/files/14025184/Files.zip)

Here are both of the files you requested, I've tried using a VPN to France, maybe its just my country or something but I had no luck as well :/

**Comment by Maplespe** [comment]
Well, it's not your problem and it's not my problem.
What version of Windows are you using?
I can't believe there are no symbols for that version on the Microsoft servers.
I'm sorry, there's nothing I can do.

**Comment by Shy-Doge** [comment]
Running x64 Windows 11 Home, though I think I have the Release Preview builds, its still strange there are no symbols files.
![image](https://github.com/Maplespe/DWMBlurGlass/assets/64466191/fe0c8650-4df4-402f-8659-812dfc3c0001)
![image](https://github.com/Maplespe/DWMBlurGlass/assets/64466191/631cfef1-ee93-4070-90e3-09b42482be27)

Well thank you for your help still.

**Comment by Maplespe** [comment]
Well, if you're on the preview version, Microsoft usually makes symbols available 2 weeks after releasing its updates.

**Comment by Shy-Doge** [comment]
Then I guess I will have to wait, Thank you for the info!
