### ISSUE TITLE
German translation not working due to typo mistake

### ISSUE THREAD

**Issue by leonhardw** [Maplespe/DWMBlurGlass#363]
**Describe the bug**
> A clear and concise description of what the bug is:

The german language file can't be loaded because the language code in line 2 in de-de.xml is ```da-DE``` instead of ```de-DE```. This causes the program to display everything in english.

old:
```<lang local="da-DE" author="Akey.Dev">```
new:
```<lang local="de-DE" author="Akey.Dev">```

**To Reproduce**
> Steps to reproduce the behavior:

Set system language to german and open DWMBlurGlass.

**Screenshots**
> If applicable, add screenshots to help explain your problem:

**Additional information (please complete the following information):**
 OS Version: Windows 10 22H2.19045.4651
 Software Version: 2.2.0

**What other third-party software do you use:**
 > [e.g. windhawk mods xxx]

None

**Additional context**

**Comment by SandTechStuff** [comment]
I think this was fixed in #361

**Comment by leonhardw** [comment]
Sorry, didn't see this.
