### ISSUE TITLE
CustomBlur 在 Windows 11 24H2 下失效

### ISSUE THREAD

**Issue by imloat** [Maplespe/DWMBlurGlass#364]
**Bug描述**
> 在点击“安装”按钮之后，系统突然黑屏，恢复正常之后弹出错误弹窗像是这样↓:
![捕获](https://github.com/user-attachments/assets/1eb2f28e-05ba-4f01-b878-22aed9523cb4)

**Additional information (please complete the following information):**
 > OS Version : [e.g. Windows 11 24H2 26100.1000
 > Software Version : 2.2.0

**其它第三方软件**
 > 无

**Comment by Maplespe** [comment]
不支持预览版
