### ISSUE TITLE
效果无法生效

### ISSUE THREAD

**Issue by YYl04** [Maplespe/DWMBlurGlass#366]
Windows版本：22635.3930 (23H2)
符号文件失效重新下载符号文件后出现错误提示，效果不生效
卸载后重新安装依然会弹出错误提示
![屏幕截图 2024-07-18 005055](https://github.com/user-attachments/assets/66199552-b226-4982-ac98-bcae3cdd0a67)

**Comment by LoveJessyChen** [comment]
还有24H2 也没有效果

**Comment by Maplespe** [comment]
请勿放在用户文件夹
推荐放在C:\Program Files

**Comment by YYl04** [comment]
很可惜，这并不能解决此问题
