### ISSUE TITLE
Insert theme atlas image and Glass reflection imgae

### ISSUE THREAD

**Issue by DraganVictor14** [Maplespe/DWMBlurGlass#367]
On Aero Glass for Windows 8.1 (which is unsupported on Windows 10 (20H1+) and Windows 11)  exists two features which you can insert theme atlas image and Glass reflection image.

On DWMBlurGlass this feature doesn't exist!
Can you bring feature?

![IMG_20240719_084203](https://github.com/user-attachments/assets/06d22738-1e35-4413-b859-f838c674fb17)

**Comment by Maplespe** [comment]
Regarding the reflection image, you can currently change it by replacing data\aeropeek.png, as for the other features, DWMBlurGlass is not meant to mimic glass8.
If you want the same as glass8, I recommend [OpenGlass](https://github.com/ALTaleX531/OpenGlass).
