### ISSUE TITLE
DwmBlurGlass is Incompatible with WinCentreTitle(?) - Windows 10 1809 Dwm keeps crashing

### ISSUE THREAD

**Issue by kenzieshaneGD** [Maplespe/DWMBlurGlass#370]
**Describe the bug**
> A clear and concise description of what the bug is:
DWM Keeps crashing after downloading symbols files, then pressing the install button. Note that I also used an older version of Windows 10 and I've used valinet's wincentretitle project on my computer.

**To Reproduce**
> Download Symbols File
> Adjust preferences on the main tab
> Press Install
> Screen goes black and then back to normal again

Description ....

**Screenshots**
> If applicable, add screenshots to help explain your problem:
![image](https://github.com/user-attachments/assets/549e4a4a-330b-424f-a882-05ef0c5ffe41)
![image](https://github.com/user-attachments/assets/e93c1600-9eb0-469b-a90a-e9d1452e8012)

**Additional information (please complete the following information):**
 > OS Version : Windows 10 1809 Build 17763.1
 > Software Version : 2.2.0

**What other third-party software do you use:**
 > Vailnet's WinCentreTitle, Rainmeter, Open-Shell

**Additional context**

**Comment by ALTaleX531** [comment]
Windows 10 1809 is not supported.

**Comment by kenzieshaneGD** [comment]
Ok, thanks for the info 🙏
