### ISSUE TITLE
Not working in win 11 iot ltsc

### ISSUE THREAD

**Issue by rushb133** [Maplespe/DWMBlurGlass#371]
**Describe the bug**
> dwm will crash after installing dwmblurglass (debug symbols are installed)

**To Reproduce**
> open dwmblurglass in win 11 iot ltsc 2024 click on symbol click on download them go to general them click on install

**Additional information (please complete the following information):**
 > OS Version : [Windows 11 24H2.26100.1150]
 > Software Version : [2.2.0]

**What other third-party software do you use:**
 > [startallback] will work on clean install

**Comment by RibShark** [comment]
Important to note (since other 24H2 issues were closed), that this *is not a preview build*, it was [officially released in May](https://techcommunity.microsoft.com/t5/internet-of-things-blog/announcing-windows-11-iot-enterprise-ltsc-2024-empowering-edge/ba-p/4148329).

**Comment by ALTaleX531** [comment]
https://github.com/Maplespe/DWMBlurGlass/issues/159#issuecomment-2105611343
![image](https://github.com/user-attachments/assets/4e00969f-1750-4706-879c-4e9b54cd4d06)
