### ISSUE TITLE
A portion of the header buttons remain black in night mode

### ISSUE THREAD

**Issue by C-neon** [Maplespe/DWMBlurGlass#372]
**Describe the bug**
> A clear and concise description of what the bug is:
The Close, Maximize, and Minimize buttons on the top right of windows can be displayed normally as white on black in most system windows. But in some other windows, the buttons will be black. These buttons will be difficult to use with a solid black background. In day mode there is no such bug, and the buttons in all windows are displayed in black. Perhaps some types of windows are not adapted for night mode.

**To Reproduce**
> Steps to reproduce the behavior:
Turn on night mode and open some windows
  - normals : file explorer, paint, OBS
  - blacks : device manager, chrome

**Screenshots**
> If applicable, add screenshots to help explain your problem:
![PixPin_2024-07-28_22-55-14](https://github.com/user-attachments/assets/f75ad0f6-26ce-4cff-9a34-569c2fed24ac)

**Additional information (please complete the following information):**
 > OS Version : Windows 11 23H2.22631.3810
 > Software Version : 2.2.0

**What other third-party software do you use:**
None

**Additional context**
None

**Comment by ALTaleX531** [comment]
The functionality of DwmBlurGlass does not include changing the colors of the title bar buttons. These colors depend on whether the window is in dark mode or not. Even if you uninstall DwmBlurGlass, these behaviors are still there aren't they?
In conclusion, this is not a bug.
