### ISSUE TITLE
[Bug] DWMBlurGlass sometimes not installing (with symbolic files)

### ISSUE THREAD

**Issue by Dylanstas** [Maplespe/DWMBlurGlass#373]
**Describe the bug**
> The software wont do anything, but only sometimes, other times it works fine! , but not sometimes, sometimes no errors, no nothing, it just wont want to apply the blurred glass theme

Description ....

**To Reproduce**
> Download latest version from github, bilibili or the other sorce
> Extract it in C:\Program Files\DWMBlurGlass\
> Run it
> Click install (after getting the corect sybolic files)

Description ....

**Screenshots**
> Clearly not installed
![image](https://github.com/user-attachments/assets/ab8df7dc-7822-496f-a3f1-4f1ad9def7a8)

**Additional information (please complete the following information):**
 > OS Version : Windows 11 23H2.22631.3880 (sadly)
 > Software Version : 2.2.0

**What other third-party software do you use:**
 > ExplorerPatcher, Lively Wallpaper and FancyWM.

**Additional context**
> There is nothing else

**Comment by Maplespe** [comment]
Please try uninstalling ExplorerPatcher completely and try again.
Make sure the user you are currently using has administrator level privileges.
Make sure that DWMBlurGlass is not blocked by any security software.
Make sure you enable "Transparent Effect" in System Settings - Personalization - Colors.
Make sure your computer is not in power saving mode.

**Comment by Dylanstas** [comment]
It still isn't working, i've tried uninstalling and reinstalling DWMBG, and explorerpatcher, ive tried different bluring metheds, the trasparency effect is on, idk what's cousing this issue

**Comment by Dylanstas** [comment]
or no, i just had to restart my pc for the fact that i deleted explorerPatcher to sink in for DWMBG
