### ISSUE TITLE
Cannot uninstall in any way

### ISSUE THREAD

**Issue by Djablo4wow** [Maplespe/DWMBlurGlass#376]
**Describe the bug**
I can't remove DWMBG files in any way, after the program doesn't even work properly.

**To Reproduce**
I installed DWMBG and changed the settings to my liking, with everything working like it should.
Then I restarted Windows; after the restart DWMBG didn't start working by itself (no visible change to window bars), and the GUI buttons for installing/uninstalling didn't help any, had no effect at all (also defaulting, importing, changing any of the settings didn't make a difference).
With that I decided I'll try to reinstall manually by leaving the GUI with "uninstall" pressed, closing the exe and removing the whole DWMBG folder I placed in Program Files. Windows is certain at least two files are constantly in use (the .exe and .pbp), and Task Scheduler had the _extend thing setup correctly (as I said it didn't work anyways) before I removed it from there.
I honestly do not see any reason as to why  1. DWMBG stopped injecting properly after one restart (GUI was left on "installed")  2. It's files are being said to be working, but nothing is working, even though the GUI says otherwise without fail

**Screenshots**
![image](https://github.com/user-attachments/assets/b9582bb4-b71f-4821-a5d6-a68ac0d65c21)
![image](https://github.com/user-attachments/assets/98a8f696-d6ca-4cb1-a752-47485d7175a9)
![image](https://github.com/user-attachments/assets/32231f6f-368e-4fcb-8bcf-1d096703d8f2)

**Additional information (please complete the following information):**
 > OS Version : Windows 10 22H2.19045.2364
 > Software Version : 2.1.1

**What other third-party software do you use:**
> Openshell, Winaerotweaker

**Additional context**
I am sure DWMBG isn't interrupted by any other program I use. After the first restart post-setup of DWMBG, I gave it a lot of time to get itself up and running, and didn't notice any signs of it 'waking up'.

**Comment by Maplespe** [comment]
If you are unable to uninstall Please manually delete the scheduled tasks, end the DWMBlurGlass.exe process and the dwm.exe process, and then delete the files.

Also, please use the latest version (2.2.0).

**Comment by Djablo4wow** [comment]
dwm.exe restarts instantly though 😭  I will try again as you suggest.

**Comment by Maplespe** [comment]
The dwm.exe is a system process, it will start automatically, otherwise you will always have a black screen.
As soon as you uninstall DWMBlurGlass and end dwm once, the file occupancy should be released.

**Comment by Djablo4wow** [comment]
That doesn't happen, the files remain chained... It's like DWMBG is baked into it now :/

**Comment by Maplespe** [comment]
That's odd, 2.1.1 doesn't load automatically, it only loads once on a restart of the computer, so after uninstalling and restarting dwm.exe once it should be able to remove the files.
Also, please delete DWMBlurGlass.exe and DWMBlurGlassExt.dll manually instead of deleting the whole folder so the system will tell you who is using it.

**Comment by Djablo4wow** [comment]
I understand, I don't get it either. OK i made the files complete again (like the 7th or 8th time, since I tried this before) by repasting the install folder, and NOW the gui and visuals take effect! Why the hell wouldn't it work all those previous times, I swear nothing has changed to affect this 😭 The uninstall button also works correctly. Let me try to uninstall and delete everything, then switch to release 2.2.0....
also, to answer your instruction, explorer was showing both files you mention were in use by dwm.exe (which wouldn't let go)

**Comment by Djablo4wow** [comment]
OK now it let me delete all the files without a tug of war. I was starting to get paranoid. I'll try 2.2.0 and leave a comment to confirm if it goes without issues.

**Comment by Djablo4wow** [comment]
Installed 2.2.0, imported settings from file, restarted pc, all still working perfectly. Thank you for responding quickly and for making such a cool customizer. Cheers!
