### ISSUE TITLE
和24H2存在严重兼容性问题，无法正常使用

### ISSUE THREAD

**Issue by Alpa7000** [Maplespe/DWMBlurGlass#377]
**Describe the bug**
点安装之后dwm崩溃直接报错

Description ....

**To Reproduce**
点安装就可以复现

Description ....

**Screenshots**
> If applicable, add screenshots to help explain your problem:

**Additional information (please complete the following information):**
 > OS Version : 26100.1301
 > Software Version : 2.2.0

**What other third-party software do you use:**
无

None

**Additional context**

**Comment by jonm58** [comment]
[#159 (comment)](https://github.com/Maplespe/DWMBlurGlass/issues/159#issuecomment-2105611343) ![image](https://private-user-images.githubusercontent.com/105535231/351838966-4e00969f-1750-4706-879c-4e9b54cd4d06.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMzNjQ0NjIsIm5iZiI6MTcyMzM2NDE2MiwicGF0aCI6Ii8xMDU1MzUyMzEvMzUxODM4OTY2LTRlMDA5NjlmLTE3NTAtNDcwNi04NzljLTRlOWI1NGNkNGQwNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgxMVQwODE2MDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00ZWVjMzEwYWY0ZGFkZWIyZWRjNGFmNTI1ZDZlMmY4MmU2M2QxMDRhODNjZDFlY2IwMDc3N2VhYjVmYjcyYmE0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.mYjgaV1A2aGuSdv-VC0QmMu0mQ7dQXOxSbF0UmsjzzU)
