### ISSUE TITLE
非活动状态文本颜色似乎不起作用

### ISSUE THREAD

**Issue by PIndividual** [Maplespe/DWMBlurGlass#378]
**Describe the bug**
> A clear and concise description of what the bug is:

我为了能在软件失焦的时候也能看清标题栏上的字，我把非活动状态的文本颜色也设置成了白色，但是这个设置似乎不起作用，

**To Reproduce**
> Steps to reproduce the behavior:

重新卸载安装配置文件后软件在失焦的时候文字还是灰色的

**Screenshots**
<img width="666" alt="image" src="https://github.com/user-attachments/assets/7188c834-3145-41cd-8b6d-73abf99f3612">

**Additional information (please complete the following information):**
 > OS Version : Windows 10 22H2 19045.4717
 > Software Version : 2.2.0

**What other third-party software do you use:**
 >MacType
None

**Additional context**

**Comment by ALTaleX531** [comment]
你翻翻前面的issue，已经说了文件管理器的标题栏文字是自己画的，不受DWM控制
