### ISSUE TITLE
Weird behavior of the aero reflection ?

### ISSUE THREAD

**Issue by nopahc4** [Maplespe/DWMBlurGlass#38]
So I have noticed it's like less visible when you use color blending, and when setting the opacity to 100% the reflection completely dissapears, meaning it's not on top of the blend color, but instead on the bottom and gets covered by the blend color, I don't think it should be like that, correct me if I'm wrong

**Comment by Eevee-Gaming** [comment]
You aren't wrong, happens to me too.

**Comment by nopahc4** [comment]
> Contributor

hello drawn market place

**Comment by Unbloated** [comment]
> hello drawn market place

![1137844809080516668](https://github.com/Maplespe/DWMBlurGlass/assets/106253650/e2c093bf-a387-4d6d-98c2-7b6c4f37ee9d)

**Comment by craftnut** [comment]
additionally, aero reflection effect would seem as if it doesn't work at all on my machine.

**Comment by nopahc4** [comment]
> additionally, aero reflection effect would seem as if it doesn't work at all on my machine.

check if you have the aeropeek.png in the data folder

**Comment by craftnut** [comment]
> check if you have the aeropeek.png in the data folder

The file is there, I saw a video talking about this software that also mentioned having issues with this feature.

**Comment by Maplespe** [comment]
Resolved in the new version.
