### ISSUE TITLE
Error while installing

### ISSUE THREAD

**Issue by trlef19** [Maplespe/DWMBlurGlass#381]
**Screenshots**
![Στιγμιότυπο οθόνης (2)](https://github.com/user-attachments/assets/31a93dbe-0104-42bc-9f07-95a2d088ed75)

**Additional information (please complete the following information):**

 > OS Version : Windows 11 Pro 23H2.22631.4037
 > Software Version : 2.0.1

**Comment by Maplespe** [comment]
You are missing the relevant files, please download and fully unzip the program from the [Release ](https://github.com/Maplespe/DWMBlurGlass/releases)page.
