### ISSUE TITLE
同时使用DWMBlurGlass与火绒安全软件时出现问题

### ISSUE THREAD

**Issue by xiaopangxie123** [Maplespe/DWMBlurGlass#383]
**Describe the bug**
> A clear and concise description of what the bug is:

同时使用DWMBlurGlass与火绒安全软件，重启后DWMBlurGlass报错VirtualAllocEx failed

**To Reproduce**
> Steps to reproduce the behavior:

下载火绒安全软件并启用，重启后即可

**Screenshots**
> If applicable, add screenshots to help explain your problem:

![e676d434b0ae1490eb9fe75daac7e4b6](https://github.com/user-attachments/assets/5cb5e68c-41ea-424a-9764-9cff9fe26dc1)
![74ff277143ede4edfb248a311d20f1b8](https://github.com/user-attachments/assets/b57cdea6-3348-478b-94e1-f0834683c712)

**Additional information (please complete the following information):**
 > OS Version : Windows 11 23H2.22631.4037
 > Software Version : 2.2.0

**What other third-party software do you use:**
 > 火绒安全软件

**Additional context**

**Comment by Maplespe** [comment]
我这边一直用的火绒没出现过问题，建议排查下别的软件 即使是安全软件拦截的任何问题 我们也无法解决 只能你添加白名单

**Comment by xiaopangxie123** [comment]
> 我这边一直用的火绒没出现过问题，建议排查下别的软件 即使是安全软件拦截的任何问题 我们也无法解决 只能你添加白名单

我这里已经把整个分区添加白名单了还是不行，关掉火绒以后就可以了，谢谢回复，我将会在火绒那边提交反馈

**Comment by dojustme** [comment]
@xiaopangxie123 应该是火绒系统防护-系统加固导致的
<img width="1145" height="768" alt="Image" src="https://github.com/user-attachments/assets/6e07fbc0-f921-4a89-8f09-fc6b79e91066" />
