### ISSUE TITLE
Hi i updated on 24H2 1457 and DwmBlurGlass not work... 

### ISSUE THREAD

**Issue by Mojas84** [Maplespe/DWMBlurGlass#385]
Hi i updated on 24H2 1457 and DwmBlurGlass not work... We can someone help? Scr = https://screenshotx.com/i/fy6uwc

**Comment by Kenst1092** [comment]
Yeah... 24H2 when? It doesn't work at all on this major update. I'm also on build 26100.1457

**Comment by Maplespe** [comment]
Please read the “[Issues rules](https://github.com/Maplespe/DWMBlurGlass/issues/159)”.

> You should not and do not need to open an issue in the following cases.
> 
> You are using a version of Windows that is not available in the general availability channel, you can check if your version of Windows is supported here ( Windows 11) or here (Windows 10).
> e.g.
> Windows Server Build 20348
> Windows 11 Build 24200
> !!! DO NOT REPORT THIS BECAUSE THIS IS NOT A BUG !!!!
