### ISSUE TITLE
DWMBlurGlass crashes after saving and choosing other options

### ISSUE THREAD

**Issue by KlothoTheDev** [Maplespe/DWMBlurGlass#389]
So i booted up my pc and when i open explorer i didn't saw the aero glass on my windows 10. When i opened DWMBlurGlass i saw it was already installed and then when i saved the options is crashed

https://github.com/user-attachments/assets/ac28f0aa-0754-4384-bdb5-f7b8508ba76b

**Comment by ALTaleX531** [comment]
Closed for not following issue template.
