### ISSUE TITLE
DWMBlurGlass Not Working

### ISSUE THREAD

**Issue by Bmore2012** [Maplespe/DWMBlurGlass#391]
Hello, I am running the latest build on **Windows 11 23H2** and this application is not working. Upon startup it tells me it was **unable to download the required symbols**, and when saving any of my settings does not visually change anything even after multiple restarts.

Is this version just bugged for the version of Windows 11 I am running or have I done something wrong when booting up / downloading the application? It is not in a Users directory as per the applications request.

Thanks!

**Comment by Doofus-Mc-Goofus** [comment]
It should probably work now. It takes a few days for symbols to catch up to the latest build.

**Comment by Maplespe** [comment]
Whenever a new system version is released, if you update it first, it usually takes a week later to download the symbols, it depends on Microsoft and has nothing to do with this program We can't fix it either.
