### ISSUE TITLE
Crashing Frequently

### ISSUE THREAD

**Issue by SJL64** [Maplespe/DWMBlurGlass#393]

**Comment by SJL64** [comment]
Happening every 2-3 MNinutes under mild-High system load. Win 10 Fresh install. Running Open shell no other majour tweeks to system should be clean install happens consistantly as soon as a few tasks are running simultaniously...Last system this programme ran beautifully, please ask what info you will need to diagnose of will be of help.

Thank you.


[DiagnosticInfo.txt](https://github.com/user-attachments/files/17008316/DiagnosticInfo.txt)

**Comment by Maplespe** [comment]
This error is usually caused by the graphics card driver, try updating the driver.

**Comment by SJL64** [comment]
I have tried and it is still doing the same. Have there been any other
instances of this where the settings might have been an issue? It won't
just crash on it's own, you have to be doing an action say the start menu
and it always happens when you use it quickly then i get a message saying
its not autoloading...

Graphics card is Intel UHD Graphics 600

I only need this to enable manuglass on win 10 is there an older more
stable version. I have menu blur the other all but it makes whole explorer
window clear and im only wanting title bars and boarders clear.

Please let me know if any further information from my system might help to
diagnose the issue. Thankyou

**Comment by LunatiK-ExpiX** [comment]
Same issue, I have confirmed that my drivers are on the latest version. I have an AMD APU with Radeon R6 Graphics

**Comment by SJL64** [comment]
I had this running fine on windows 11 same system same graphics drivers.

After some investigation I can confirm most of these occurrences happing
from windows10 OS. I have also rolled mine back to win10. Hope this might
help as issue is widespread.

No issues running on win11 on which I have run both this and
ExplorerBlurMica. So no worries there your product is good.

Is it possible to adapt ExplorerBlurMica, to do same job it works fine on
my win10 but I wanting no opacity in icon area of explorer window. Can I
add something to config to have similar effect.

Good luck 🙏 we await further developments.
