### ISSUE TITLE
Win11 Extend Border Effect Broken since 2.1.0

### ISSUE THREAD

**Issue by BiatuAutMiahn** [Maplespe/DWMBlurGlass#396]
**Describe the bug**
> A clear and concise description of what the bug is:

On windows 11, the Extend effects to borders is broken since 2.1.0.

**To Reproduce**
> Steps to reproduce the behavior:

Download & Install either 2.2.0, 2.1.1, or 2.1.0. Apply Bring Back the Borders! (w11-dwm-fix) via Windhawk.

**Screenshots**
> If applicable, add screenshots to help explain your problem:

**Additional information (please complete the following information):**
 > OS Version : [e.g. Windows 11 23H2.22631.3085]
 > Software Version : [e.g. 2.0.1]

Win11 v10.0.22631.2428

**What other third-party software do you use:**
 > [e.g. windhawk mods xxx]

Apply Bring Back the Borders! (w11-dwm-fix) via Windhawk.

**Additional context**
I was initially working with 2.0.1. Realized that there were upgrades avail. I downloaded all versions to get the best result. I would taskkill dwm.exe before attempting to use different versions. Rebooting didn't help the issue either. Kill dwm.exe instances and wait for the process to respawn, the run DWMBlurGlass loaddll for <2.2.0. Every version after 2.0.1 does not render the effect at all, the region extending beyond the border is transparent.

Screen caps:
2.2.0
![image](https://github.com/user-attachments/assets/8a4f3b3b-0e5d-4e19-ba63-90ffb670d381)

2.1.1
![image](https://github.com/user-attachments/assets/f2173355-4789-4cc7-aee6-e88a60763f96)

2.1.0
![image](https://github.com/user-attachments/assets/13b8fda6-569b-4351-b8bf-7f574ed86cea)

2.0.1
![image](https://github.com/user-attachments/assets/29d45427-263e-4559-a364-a35b6076a8ec)

**Comment by MeowcaTheoRange** [comment]
Happens to me as well on Windows 10 22H2.

**Comment by BiatuAutMiahn** [comment]
Btw I was using "Microsoft Basic Display Driver", on a different machine with iGPU is renders fine one latest version.
