### ISSUE TITLE
DWMBlurGlass not downloading PDBs and not applying

### ISSUE THREAD

**Issue by HelloTech2** [Maplespe/DWMBlurGlass#398]
**Describe the bug**
> A clear and concise description of what the bug is:

DBG not downloading all the necessary symbol files and shows an error
And also when installing dbg it does not apply

**To Reproduce**
> Steps to reproduce the behavior:

Try to download the symbol files
Try to install dbg

**Screenshots**
> If applicable, add screenshots to help explain your problem:

![PDBError](https://github.com/user-attachments/assets/10a57ba6-16d6-4bb7-a63c-7add76c2ad73)
![DBGInstallError](https://github.com/user-attachments/assets/934c1559-84f0-476b-92cf-149541bb8068)
![MSDLError](https://github.com/user-attachments/assets/f69445a1-89c9-4378-ace4-cc7f4603bfc1)

**Additional information (please complete the following information):**
 > OS Version : [e.g. Windows 11 23H2.22631.3085]
 > Software Version : [e.g. 2.0.1]

Windows 11 23h2 22631.3371
DBG v2.2.0

**What other third-party software do you use:**
 > [e.g. windhawk mods xxx]

Rectify11 v3.0 (MicaForEveryone 1.3.1.2, SecureUxTheme 2.2.0)
MalwareBytes 5.1.11.133

**Additional context**
Added Exception to DWMBlurGlass in MB
Tried to open https://msdl.microsoft.com/ and appears error

**Comment by Doofus-Mc-Goofus** [comment]
[Read this.](https://github.com/Maplespe/DWMBlurGlass/issues/391#issuecomment-2356413768)

**Comment by HelloTech2** [comment]
Ok
