### ISSUE TITLE
Weird effect on edges of a window

### ISSUE THREAD

**Issue by windowsxp3790** [Maplespe/DWMBlurGlass#4]
![edges](https://github.com/Maplespe/DWMBlurGlass/assets/149018134/20b778db-9bb0-4a0d-94d3-65e80e2f8336)
Is it possible to fix the weird effect the appears on the edges of windows ?

**Comment by windowsxp3790** [comment]
By edges I mean this 
![296771264-20b778db-9bb0-4a0d-94d3-65e80e2f8336](https://github.com/Maplespe/DWMBlurGlass/assets/149018134/bf07ebb7-46a3-4d3c-8feb-b9adce99fb94)

**Comment by CallyHam** [comment]
A temporary fix would be to set the background blend color's opacity to 0 but it would be nice to see this fixed
![image](https://github.com/Maplespe/DWMBlurGlass/assets/87724457/d1c30856-1eb4-44f5-9e1f-2afbc28aa861)
![image](https://github.com/Maplespe/DWMBlurGlass/assets/87724457/2709dbc3-de26-4849-a173-66608d50b431)

**Comment by emeraldongithub** [comment]
![image](https://github.com/Maplespe/DWMBlurGlass/assets/99167692/ba1f5f50-666a-4d86-852f-92f4b0c1b8f1)
lmao

**Comment by Maplespe** [comment]
The new version has been updated to add the option "`Extend effects to borders`" for compatibility with third-party themes.
