### ISSUE TITLE
Auto re injection feature

### ISSUE THREAD

**Issue by windowsxp3790** [Maplespe/DWMBlurGlass#40]
Every once in a while DWM crashes causing the transparency/blur to get disabled which the only way to fix is by logging off then back on again or uninstall/reinstalling
Can you make an option to auto re inject into dwm in case it crashes?

**Comment by Maplespe** [comment]
Our goal is to achieve stable results, and we're trying to fix the crashing issue as best we can, it only seems to occur in win10.
It will only be used as a last resort if it's just not fixable.

**Comment by Maplespe** [comment]
It should have been stabilized since version 1.0.4 and has not crashed again so far.

**Comment by windowsxp3790** [comment]
> It should have been stabilized since version 1.0.4 and has not crashed again so far.

Yep :)

**Comment by TorutheRedFox** [comment]
this should still be a feature as there are situations where you may want to restart DWM manually, such as when setting a DWM-related group policy (such as no window anims) without having to log out and back in like Microsoft expects you to

**Comment by windowsxp3790** [comment]
> this should still be a feature as there are situations where you may want to restart DWM manually, such as when setting a DWM-related group policy (such as no window anims) without having to log out and back in like Microsoft expects you to

True
