### ISSUE TITLE
There is pink everywhere

### ISSUE THREAD

**Issue by N0VA-The-Git-User** [Maplespe/DWMBlurGlass#401]
**Describe the bug**
> A clear and concise description of what the bug is:

Everything is pink

Description ....

**To Reproduce**
> Steps to reproduce the behavior:

I don't know

Description ....

**Screenshots**
> If applicable, add screenshots to help explain your problem:

![image](https://github.com/user-attachments/assets/23f1d38a-b44b-4e5a-8319-c17a8c0c6b79)

![image](https://github.com/user-attachments/assets/ed2e74a4-6583-44c3-a536-6d81853723e3)

**Additional information (please complete the following information):**
 > OS Version : 
![image](https://github.com/user-attachments/assets/18dba70f-376c-4542-8fa4-c542927055da)

 > Software Version : [e.g. 2.0.1]

**What other third-party software do you use:**
windhawk mods

**Comment by SandTechStuff** [comment]
Did you mistakenly change the blend color? Check what it says under titlebar blend color (active) and titlebar blend color (inactive) for both light and dark mode.

**Comment by N0VA-The-Git-User** [comment]
> Did you mistakenly change the blend color? Check what it says under titlebar blend color (active) and titlebar blend color (inactive) for both light and dark mode.

No, I think it's a texture issue or something. It goes on and off every time I turn on my computer.
