### ISSUE TITLE
在Win11 24H2上出现错误 | Not work on win11 24H2

### ISSUE THREAD

**Issue by WorkingML** [Maplespe/DWMBlurGlass#402]
**Describe the bug**
> A clear and concise description of what the bug is: 在开机进入账户后系统卡死，然后黑屏（左上角出现无内容的Windows Basic窗口，估计是显示兼容方面的问题？），然后就出现了一个错误弹窗（用的是iris xe核显，i7-12700h）
![image](https://github.com/user-attachments/assets/eed9e5da-6835-4e6d-a3e5-90ca6eab347d)

Description ....

**To Reproduce**
> Steps to reproduce the behavior:在Win11 24H2 开机进入账户

Description ....

**Screenshots**
> If applicable, add screenshots to help explain your problem:
![image](https://github.com/user-attachments/assets/f7f26802-623c-4afb-ba41-89c547268cda)

**Additional information (please complete the following information):**
 > OS Version :Windows 11 24H2.26100.1742
 > Software Version : 2.2.0

**What other third-party software do you use:**
 > translucentTB
 > [ExplorerBlurMica](https://github.com/Maplespe/ExplorerBlurMica)

None

**Additional context**

**Comment by WorkingML** [comment]
![image](https://github.com/user-attachments/assets/db1783d8-28f6-4fcc-964d-6c3a7fffb397)
you'tan又弹出一个东西

**Comment by ZiLeYunk** [comment]
还没适配吧

**Comment by RTFTR** [comment]
The current version of DWMBG is not supported for 24H2. You have to wait for Maplespe to release the one with it.

**Comment by PigeonP** [comment]
我跟你一样的问题，自从下载更新到Win11 23H2 09月更新后也会报错上述两个错误。现在卸载了09月更新之后问题也解决不了了

**Comment by ALTaleX531** [comment]
还没有适配，我本人和maple基本上没多少时间，软件依赖某些DWM内部的数据结构和函数，因此只要大版本更新都需要重新逆向，用不了很正常，提醒那些想一直安安稳稳用下去的最好别更系统

**Comment by PigeonP** [comment]
> 还没有适配，我本人和maple基本上没多少时间，软件依赖某些DWM内部的数据结构和函数，因此只要大版本更新都需要重新逆向，用不了很正常，提醒那些想一直安安稳稳用下去的最好别更系统

好的，了解了
