### ISSUE TITLE
Install ERROR Windows 11 24H2

### ISSUE THREAD

**Issue by SangalDigital** [Maplespe/DWMBlurGlass#405]
Describe the bug:
Hello. I have reinstalled Windows 11 because of some issues. 
So i wanted to reinstall DWMBlurGlass, first the symbols, they download okay and they are valid but then after pressing the install button. The screen flashes and i get this error.

Pressing the install button.

What other third-party software do you use:
StartAllBack

Screenshots
![dwmblurglass error](https://github.com/user-attachments/assets/ec33a47c-eb02-46fb-8e8d-7ffb9f8f9962)
![win](https://github.com/user-attachments/assets/b764d0c3-a8a0-4a18-b162-ce56a4f9a7cc)

Please help me i really enjoy this software it's the closest thing to Win 7 theme i can get right now!

Sorry for my bad english.

**Comment by Sub2Ninah** [comment]
dwmblurglass is proven to not work on 24h2. in the meantime, u can use micaforeveryone or wait for the next release

**Comment by CtrlasAltas** [comment]
Does not work with latest Windows 11 24H2

**Comment by SaiyajinK** [comment]
Same here (24h2 build 26100.2161). 

![image](https://github.com/user-attachments/assets/5e22a66a-de2d-40c6-ba9c-48bcdffe9271)

> dwmblurglass is proven to not work on 24h2. in the meantime, u can use micaforeveryone or wait for the next release

MicaForEveryone don't work with 24h2 ([check here](https://github.com/MicaForEveryone/MicaForEveryone/issues))

Moreover the software has been abandoned for over a year now.

**Comment by Sub2Ninah** [comment]
openglass just got a 24h2 update. i recommend using it. :3

**Comment by SaiyajinK** [comment]
> openglass just got a 24h2 update. i recommend using it. :3

I'll see how it goes, thanks.

**Comment by hellojo011** [comment]
In Windows 1124H2, DWMBlurGlass will display the same error message you posted if the Blur Method is "CustomBlur" and will not work.

Simply switch Blur Method to "DWMAPI" in the Advanced tab, and then install it, it will not cause any errors.

**Comment by CtrlasAltas** [comment]
Hello! I apologize if this is a repeated question. Will there be an update to DWMBlurGlass for Windows 11 24H2? I installed OpenGlass and am running it on default settings, which makes the title bar for windows/apps transparent. However, I can't find any information on adjusting its opacity or other settings, and I also can't locate a FAQ for configuring OpenGlass. I love that DWMBlurGlass has a GUI.

**Comment by Undisputed00x** [comment]
>However, I can't find any information on adjusting its opacity or other settings, and I also can't locate a FAQ for configuring OpenGlass.

Make some effort and read the repo's page as its neither a launch and ready-to-go software nor is intended for beginner audience, here is what you need: https://github.com/ALTaleX531/OpenGlass?tab=readme-ov-file#documentation-migrate-from-glass8-to-openglass

**Comment by Exyzos** [comment]
For OpenGlass you need to go into the registry directory that they specify, then manually create DWORD values for the parameters you want to change. They tell you which DWORD value controls what in that table that the person above me linked. There's no GUI or anything, it's entirely DIY. It's not that bad though, and once it's working its pretty much flawless.
