### ISSUE TITLE
Effects replaced by system accent color after black screen

### ISSUE THREAD

**Issue by okamitime** [Maplespe/DWMBlurGlass#41]
DWMBlurGlass works perfectly on startup but after anywhere from a few seconds to several minutes the screen temporarily goes black and when it turns back on, all of the effects that were enabled through DWMBlurGlass are turned off and replaced by my custom W10 accent color with no transparency. The caption buttons become larger as well.

![blurglass-on](https://github.com/Maplespe/DWMBlurGlass/assets/77937632/e3728daf-3ec3-47e8-b7c3-4b55c3a0c368)
![blurglass-off](https://github.com/Maplespe/DWMBlurGlass/assets/77937632/58f72c3e-1a5f-4368-98cf-e57234abaeb0)

**Comment by nopahc4** [comment]
that's because the process crashes and you gotta reinstall it

**Comment by windowsxp3790** [comment]
> DWMBlurGlass works perfectly on startup but after anywhere from a few seconds to several minutes the screen temporarily goes black and when it turns back on, all of the effects that were enabled through DWMBlurGlass are turned off and replaced by my custom W10 accent color with no transparency. The caption buttons become larger as well.
> 
> ![blurglass-on](https://private-user-images.githubusercontent.com/77937632/299103820-e3728daf-3ec3-47e8-b7c3-4b55c3a0c368.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYwNTAxNDksIm5iZiI6MTcwNjA0OTg0OSwicGF0aCI6Ii83NzkzNzYzMi8yOTkxMDM4MjAtZTM3MjhkYWYtM2VjMy00N2U4LWI3YzMtNGI1NWMzYTBjMzY4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTIzVDIyNDQwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIzYzQ3OGFhYjMzOGE3ZDJiZWQ2M2YzNTVjOTQzOWM1MmE0NmI4NmYxYmU5N2M5MzMzMDMyNTg4NmM5ZGU4NzMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.rKm8WGQ1GgqqObRQdc2iy6-OE5mDcB1tcYmjCNE3wps) ![blurglass-off](https://private-user-images.githubusercontent.com/77937632/299103818-58f72c3e-1a5f-4368-98cf-e57234abaeb0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYwNTAxNDksIm5iZiI6MTcwNjA0OTg0OSwicGF0aCI6Ii83NzkzNzYzMi8yOTkxMDM4MTgtNThmNzJjM2UtMWE1Zi00MzY4LTk4Y2YtZTU3MjM0YWJhZWIwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTIzVDIyNDQwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk3N2I0ZDEyZDc0OGZhM2ExZDgzM2E4NTJhOTk5MWUyZmRiYmNjOTBkZWJmZWU0ZDQ3YmFhMjY4OTA1N2Q0MDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.QPjXxbhWRJcO6pF8i3kYV6Bp6o48A29QTexaRi9ueHs)

Auto re inject feature would be nice 🙌

**Comment by Maplespe** [comment]
Yes, this is actually due to a dwm crash and we will continue to improve and focus on this issue in #10.

**Comment by nopahc4** [comment]
> > DWMBlurGlass works perfectly on startup but after anywhere from a few seconds to several minutes the screen temporarily goes black and when it turns back on, all of the effects that were enabled through DWMBlurGlass are turned off and replaced by my custom W10 accent color with no transparency. The caption buttons become larger as well.
> > ![blurglass-on](https://private-user-images.githubusercontent.com/77937632/299103820-e3728daf-3ec3-47e8-b7c3-4b55c3a0c368.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYwNTAxNDksIm5iZiI6MTcwNjA0OTg0OSwicGF0aCI6Ii83NzkzNzYzMi8yOTkxMDM4MjAtZTM3MjhkYWYtM2VjMy00N2U4LWI3YzMtNGI1NWMzYTBjMzY4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTIzVDIyNDQwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIzYzQ3OGFhYjMzOGE3ZDJiZWQ2M2YzNTVjOTQzOWM1MmE0NmI4NmYxYmU5N2M5MzMzMDMyNTg4NmM5ZGU4NzMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.rKm8WGQ1GgqqObRQdc2iy6-OE5mDcB1tcYmjCNE3wps) ![blurglass-off](https://private-user-images.githubusercontent.com/77937632/299103818-58f72c3e-1a5f-4368-98cf-e57234abaeb0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYwNTAxNDksIm5iZiI6MTcwNjA0OTg0OSwicGF0aCI6Ii83NzkzNzYzMi8yOTkxMDM4MTgtNThmNzJjM2UtMWE1Zi00MzY4LTk4Y2YtZTU3MjM0YWJhZWIwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTIzVDIyNDQwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk3N2I0ZDEyZDc0OGZhM2ExZDgzM2E4NTJhOTk5MWUyZmRiYmNjOTBkZWJmZWU0ZDQ3YmFhMjY4OTA1N2Q0MDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.QPjXxbhWRJcO6pF8i3kYV6Bp6o48A29QTexaRi9ueHs)
> 
> Auto re inject feature would be nice 🙌

you can create a shortcut to immediately reinject, that's what i do and with just 2 clicks i get it back
