### ISSUE TITLE
安装之后没有任何效果 

### ISSUE THREAD

**Issue by Super1Windcloud** [Maplespe/DWMBlurGlass#415]
**Describe the bug**
> A clear and concise description of what the bug is:
 ##  通过`scoop install  DWMBlurGlass`  安装之后打开, 点击应用不起作用  
![图片](https://github.com/user-attachments/assets/d516300d-1aae-4139-a27c-4968ff538021)

   

**Screenshots**
 
![图片](https://github.com/user-attachments/assets/46d2ab48-360c-47bb-8618-e217080610f8)

--- 
![图片](https://github.com/user-attachments/assets/ee62a8cb-dc83-41d6-accf-1d73a354ce1f)

---
![图片](https://github.com/user-attachments/assets/ab61e03c-67db-4d5a-ac08-7103916af080)

**Additional information (please complete the following information):**
 > OS Version :  Windows 11 23H2 
 > Software Version :  2.0.1

**Comment by Maplespe** [comment]
首先 我们只对本储存库负责 不对任何第三方软件或者其他安装方式负责 你需要安装本储存库的安装方式 打开GUI手动点击安装
其次 你选择的是Mica效果 Windows11本身标题栏就是云母效果 所以没有什么区别
最后 你没有勾选"覆盖使用DWMAPI设置的云母效果"这个选项 只有勾上之后才能覆盖文件资源管理器的标题栏云母效果
