### ISSUE TITLE
Offset Win7-styled buttons

### ISSUE THREAD

**Issue by Za9-118** [Maplespe/DWMBlurGlass#417]
**Describe the solution you'd like**
Make the offset titlebars a settings if the user has no thick frames. 

**Your reason (tell us why we need it)**
I want the win7-styled titlebar buttons to be offset slightly to support thick borders, right now, checking the Windows 7 styled buttons option makes it at the very topright instead of like Aero.

**Describe alternatives you've considered**
Using a theme with smaller buttons, but the maximized button is too small.

**Additional context**
This is what they should look like if the option is on
![Offset buttons](https://github.com/user-attachments/assets/d5ca482c-9198-4041-ad1f-d112fe58328f)

What checking the Windows 7 styled buttons option looks like currently (My issue):
![Screenshot 2024-11-24 120648](https://github.com/user-attachments/assets/f7cee933-ae7f-4ec2-b0ba-e0f846fcf0af)

Sorry if i suck at explaining

**Comment by Maplespe** [comment]
Look at the last line: https://github.com/Maplespe/DWMBlurGlass/releases/tag/2.2.0
`titlebtnOffsetX` is what you want.

**Comment by Za9-118** [comment]
Thanks, what value should i set it to?

**Comment by Maplespe** [comment]
> Thanks, what value should i set it to?

It is measured in pixels and is the width of the border, usually between 6 and 8.
But usually DWMBlurGlass calculates it automatically unless your theme is modified otherwise.
Your problem is probably similar to #413, I would recommend you to use the [Aero10 ](https://www.deviantart.com/vaporvance/art/Aero10-for-Windows-10-1903-22H2-909711949)theme, it is fine.

**Comment by Za9-118** [comment]
I'm using a theme called Aero7-11 because... Aero10 doesnt work on Windows 11 (the theme is found [here](https://github.com/LittleFox2024/Aero7-11/) ), There is a version with smaller titlebar buttons to make the offset not needed, but the buttons get tiny if the window is maximized

**Comment by Maplespe** [comment]
Since this feature already exists, I will close this issue.
