### ISSUE TITLE
win7 Style title bar button height reduction option affecting the smaller tool windows

### ISSUE THREAD

**Issue by wiktorwiktor12** [Maplespe/DWMBlurGlass#42]
![image](https://github.com/Maplespe/DWMBlurGlass/assets/68821018/27daeeb8-35df-4501-b254-ed7fff4b0447)
how it looks with it on

how it looks with it off
![image](https://github.com/Maplespe/DWMBlurGlass/assets/68821018/74f8390a-56db-4a4f-9f73-26dca242d036)

hopefully not hard to fix

**Comment by Maplespe** [comment]
Already mentioned in #16.
