### ISSUE TITLE
Cannot Set Background Color of Explorer Toolbar UI

### ISSUE THREAD

**Issue by SnowRainySkr** [Maplespe/DWMBlurGlass#426]
**Describe the bug**

The background color of windows explorer toolbar UI is always pure white.

**To Reproduce**

Import the DWM [config](https://github.com/user-attachments/files/17987203/config.zip) file, install, and open windows explorer.

**Screenshots**

Notice: The black rectangle is a mosaic and has nothing to do with the problem.
![image](https://github.com/user-attachments/assets/a5308ea6-cbf7-4aa9-94a8-48d0b95b5659)

**Additional information (please complete the following information):**
- OS Version : Windows 11 23H2.22631.4460
- Software Version : 2.3.0 (also available in 2.2.0)

**What other third-party software do you use:**
- MToolBox_v2.0.2

**Additional context**
Click the "..." button pointed by the arrow on the left, and the background color in the red box will be transparent as expected.

**Comment by Maplespe** [comment]
这和dwm无关 也不在本项目的范围内。
