### ISSUE TITLE
Transparency in Windows Mobility Center (Windows 11) doesn't work in version 1.0.3.

### ISSUE THREAD

**Issue by zul-fkr** [Maplespe/DWMBlurGlass#43]
Hello @Maplespe, After I upgraded from version 1.0.2 to 1.0.3, there a bug in Windows Mobility Center, the transparency isn't working/just showing solid color. Here the screenshot:

![Screenshot (6)](https://github.com/Maplespe/DWMBlurGlass/assets/130078252/7595f090-2a1f-4983-856f-785e11342129)
(I'm using Windows 11 23H2 (22631.3007)).

In version 1.0.2, it work fine. Hopefully you fix it in next version. Thank you.

**Comment by Maplespe** [comment]
Resolved in the new version.

**Comment by zul-fkr** [comment]
![Screenshot (9)](https://github.com/Maplespe/DWMBlurGlass/assets/130078252/f8193f8e-e83f-4528-bc62-42c680c40bd4)
Oh wow! It fixed now. Thank you for your hardwork dude👍
