### ISSUE TITLE
Win10系统程序直接无法正常启动

### ISSUE THREAD

**Issue by shigend** [Maplespe/DWMBlurGlass#430]
软件可以运行起来，但是在点安装后，系统闪烁一下，然后弹出一个运行错误对话框。(截图总是传输错误，只能文字描述一下了。)
错误弹窗:
DWMBlurGlass Error
    Checked that the process is suspected to have crashed abnormally and has stopped autoloading.

软件运行版本 : 2.3.0

win10系统版本 : Windows 10专业版 1909 18363.1500

**Comment by Maplespe** [comment]
> 兼容性
> 最低支持 Windows 10 2004 最高支持到 Windows 11 最新版(部分模糊方法不支持预览版)

麻烦提之前看一下ReadMe

**Comment by shigend** [comment]
好的，多谢，我找到你说的ReadMe文件了，Release一起的ReadMe.txt文件里确实没有写，我会把问题名更新下，方便以后的小白了解下。
