### ISSUE TITLE
DWMBlurGlass keeps on crashing DWM.

### ISSUE THREAD

**Issue by Milicent-Heeler** [Maplespe/DWMBlurGlass#431]
**Describe the bug**
> A clear and concise description of what the bug does is: it places the x button on top of the maximize button, it moves the maximize button to the middle of the titlebar, then it moves the minimize button, then you cannot close the current app you are in, then it crashes DWM and then shows an error message.

Description ....

**To Reproduce**
> Enable the small titlebar buttons, enable the glow effect for the titlebar buttons, make sure in advanced you have aero instead of blur.

**Additional information:**
 > OS Version : [Windows 11 23H2]
 > Software Version : [DWMBlurGlass 2.3.0]

**What other third-party software do you use:**
 > [ExplorerPatcher]

**Comment by Milicent-Heeler** [comment]
It would be really helpful if someone finds a solution.

**Comment by Milicent-Heeler** [comment]
Also, this only seems to happen with DWMBlurGlass 2.3.0. I have never had it happen in DWMBlurGlass 2.2.0, so I will be using DWMBlurGlass 2.2.0 for now.

**Comment by Maplespe** [comment]
2.3.0 will generate a dmp on crash.
Check the `data\dumps` directory and provide us with the error dump dmp file if it was generated.

**Comment by Milicent-Heeler** [comment]
> 2.3.0 will generate a dmp on crash. Check the `data\dumps` directory and provide us with the error dump dmp file if it was generated.

There is no dump folder and I don't want to check again because I have just downloaded DWMBlurGLass 2.2.0. Also, it only happens on DWMBlurGlass 2.3.0.

**Comment by Milicent-Heeler** [comment]
I would love to get this issue fixed since I would like the glow effect when you hover over the maximize, minimize and x button.

**Comment by Maplespe** [comment]
If there is no dump file, this issue may not be fixed soon and we need to reproduce and find the cause.
You can also try the beta glow effect from 2.2.0, but it may also have issues.
https://github.com/Maplespe/DWMBlurGlass/discussions/282#discussioncomment-9245189

**Comment by Milicent-Heeler** [comment]
> If there is no dump file, this issue may not be fixed soon and we need to reproduce and find the cause. You can also try the beta glow effect from 2.2.0, but it may also have issues. [#282 (comment)](https://github.com/Maplespe/DWMBlurGlass/discussions/282#discussioncomment-9245189)

To Reproduce it: Make sure you have win1123H2.

Enable the small titlebar buttons, enable the glow effect for the titlebar buttons, make sure in advanced you have aero instead of blur.

**Comment by Milicent-Heeler** [comment]
> > If there is no dump file, this issue may not be fixed soon and we need to reproduce and find the cause. You can also try the beta glow effect from 2.2.0, but it may also have issues. [#282 (comment)](https://github.com/Maplespe/DWMBlurGlass/discussions/282#discussioncomment-9245189)
> 
> To Reproduce it: Make sure you have win1123H2.
> 
> Enable the small titlebar buttons, enable the glow effect for the titlebar buttons, make sure in advanced you have aero instead of blur.

It may not reproduce the DWM crashing, but for me it did crash.

**Comment by Milicent-Heeler** [comment]
> If there is no dump file, this issue may not be fixed soon and we need to reproduce and find the cause. You can also try the beta glow effect from 2.2.0, but it may also have issues. [#282 (comment)](https://github.com/Maplespe/DWMBlurGlass/discussions/282#discussioncomment-9245189)

Also, how did you get the always red X button?

**Comment by Milicent-Heeler** [comment]
Maybe its because you refactors most of the code in 2.3.0?

**Comment by XiaoTDM** [comment]
Well, could I provide my own dump file?
Or open a new issue?
[OneDrive | minidump-2024-12-07-11-15-38.dmp](https://1drv.ms/u/c/391cbfaf16df05b8/EYPLR5OE8Z9MrVAl-mJ5U5ABjzmIEVISnxxuZ_QVR-yb8A?e=pfJbbn)

**Comment by Milicent-Heeler** [comment]
> If there is no dump file, this issue may not be fixed soon and we need to reproduce and find the cause. You can also try the beta glow effect from 2.2.0, but it may also have issues. [#282 (comment)](https://github.com/Maplespe/DWMBlurGlass/discussions/282#discussioncomment-9245189)

Thanks, it worked!

**Comment by Dragodraki** [comment]
I can reproduce the error. It exists.
I have 23H2 and DWMBlurGlass 2.3.0 crashes everytime. When I reinstall it loads the transprency theme for as long as I don't move/click my mouse and when I do it crashes and the error box apppears.

Unfortunately, there is ow dump file created too on my system

But here is the application event from eventvwr.exe (sorry the language, its a german computer):

Name der fehlerhaften Anwendung: dwm.exe, Version: 10.0.22621.4830, Zeitstempel: 0xddad0e5a
Name des fehlerhaften Moduls: ucrtbase.dll, Version: 10.0.22621.3593, Zeitstempel: 0x10c46e71
Ausnahmecode: 0xc0000409
Fehleroffset: 0x000000000007f6fe
ID des fehlerhaften Prozesses: 0x0x5A0
Startzeit der fehlerhaften Anwendung: 0x0x1DB798EDF0CD904
Pfad der fehlerhaften Anwendung: C:\Windows\system32\dwm.exe
Pfad des fehlerhaften Moduls: C:\Windows\System32\ucrtbase.dll
Berichtskennung: 0c21e7e2-3e35-48ac-aebb-59eebe3da8e4
Vollständiger Name des fehlerhaften Pakets:

**Comment by Dragodraki** [comment]
Maybe you can re-open the ticket?

**Comment by Milicent-Heeler** [comment]
> Maybe you can re-open the issue?

If you want, I can.

**Comment by Milicent-Heeler** [comment]
> I can reproduce the error. It exists. I have 23H2 and DWMBlurGlass 2.3.0 crashes everytime. When I reinstall it loads the transprency theme for as long as I don't move/click my mouse and when I do it crashes and the error box apppears.
> 
> Unfortunately, there is no dump file created too on my system
> 
> But here is the application event from eventvwr.exe (sorry the language, its a german computer):
> 
> Name der fehlerhaften Anwendung: dwm.exe, Version: 10.0.22621.4830, Zeitstempel: 0xddad0e5a Name des fehlerhaften Moduls: ucrtbase.dll, Version: 10.0.22621.3593, Zeitstempel: 0x10c46e71 Ausnahmecode: 0xc0000409 Fehleroffset: 0x000000000007f6fe ID des fehlerhaften Prozesses: 0x0x5A0 Startzeit der fehlerhaften Anwendung: 0x0x1DB798EDF0CD904 Pfad der fehlerhaften Anwendung: C:\Windows\system32\dwm.exe Pfad des fehlerhaften Moduls: C:\Windows\System32\ucrtbase.dll Berichtskennung: 0c21e7e2-3e35-48ac-aebb-59eebe3da8e4 Vollständiger Name des fehlerhaften Pakets:

I dont know how to read germany.

**Comment by Milicent-Heeler** [comment]
> I can reproduce the error. It exists. I have 23H2 and DWMBlurGlass 2.3.0 crashes everytime. When I reinstall it loads the transprency theme for as long as I don't move/click my mouse and when I do it crashes and the error box apppears.
> 
> Unfortunately, there is no dump file created too on my system
> 
> But here is the application event from eventvwr.exe 
> 
>Faulting application name: dwm.exe, version: 10.0.22621.4830, time stamp: 0xddad0e5a
Faulting module name: ucrtbase.dll, version: 10.0.22621.3593, time stamp: 0x10c46e71
Exception code: 0xc0000409
Error offset: 0x000000000007f6fe
Faulting process ID: 0x0x5A0
Faulting application start time: 0x0x1DB798EDF0CD904
Faulting application path: C:\Windows\system32\dwm.exe
Faulting module path: C:\Windows\System32\ucrtbase.dll
Report identifier: 0c21e7e2-3e35-48ac-aebb-59eebe3da8e4
Full name of the faulty package:


> I can reproduce the error. It exists. I have 23H2 and DWMBlurGlass 2.3.0 crashes everytime. When I reinstall it loads the transprency theme for as long as I don't move/click my mouse and when I do it crashes and the error box apppears.
> 
> Unfortunately, there is no dump file created too on my system
> 
> But here is the application event from eventvwr.exe):
> 
>Faulting application name: dwm.exe, version: 10.0.22621.4830, time stamp: 0xddad0e5a
Faulting module name: ucrtbase.dll, version: 10.0.22621.3593, time stamp: 0x10c46e71
Exception code: 0xc0000409
Error offset: 0x000000000007f6fe
Faulting process ID: 0x0x5A0
Faulting application start time: 0x0x1DB798EDF0CD904
Faulting application path: C:\Windows\system32\dwm.exe
Faulting module path: C:\Windows\System32\ucrtbase.dll
Report identifier: 0c21e7e2-3e35-48ac-aebb-59eebe3da8e4
Full name of the faulty package:



There you go, english
