### ISSUE TITLE
这几个界面也可以支持弄透明吗？

### ISSUE THREAD

**Issue by mikuQ** [Maplespe/DWMBlurGlass#432]
好像目前只有文件管理器控制面板是透明效果。
![QQ截图20241205171411](https://github.com/user-attachments/assets/93f64fd3-a1da-4b62-9130-c7696f9cf1f4)
![QQ截图20241205171429](https://github.com/user-attachments/assets/00bbe391-37e8-49b3-b691-d64923e0344c)

**Comment by Maplespe** [comment]
这不在本项目的范围内
