### ISSUE TITLE
Maximum blur (50) eats your CPU

### ISSUE THREAD

**Issue by Unbloated** [Maplespe/DWMBlurGlass#44]
When putting the blur at the maximum and moving a window, it will literally take all your CPU.

![rZ31Jp3](https://github.com/Maplespe/DWMBlurGlass/assets/106253650/5441606e-28b4-4a82-b483-9798aa798c2f)

It does too with less blur, but not that much.

**Comment by Maplespe** [comment]
As we explained in #7, we use dwm's internal Blur class, which is an undisclosed method that Microsoft has not removed, but its implementation is very inefficient, and we're writing custom methods to try to fix this.

**Comment by Unbloated** [comment]
> As we explained in #7, we use dwm's internal Blur class, which is an undisclosed method that Microsoft has not removed, but its implementation is very inefficient, and we're writing custom methods to try to fix this.

Thanks for explaining.

**Comment by Maplespe** [comment]
Resolved in the new version.
