### ISSUE TITLE
Latest 2.3.0 is buggy (unusable)!

### ISSUE THREAD

**Issue by Arin-426** [Maplespe/DWMBlurGlass#440]
**Describe the bug**
> It is choke full of bugs! I can't even enable it, it crashes half the time. It is very infuriating, I updated just to find out everything is absolutely messed. Nothing works, random crashes. I even re-downloaded symbols.

**To Reproduce**
> Just open it then click on Install and it will crash after a while, say if you try to change settings.
Description ....

**Additional information (please complete the following information):**
 > OS Version : Windows 10 22H2
 > Software Version : e.g. 2.3.0

**What other third-party software do you use:**
 > Lively, TranslucentSM by ctrlk, TranslucentTB, TranslucentFlyouts

**Comment by Maplespe** [comment]
First of all, I sincerely apologize for your bad experience.
Prior to release We tested all (Windows 2004-Windows 11 24H2) all major versions. Nevertheless, we can't guarantee that it will work correctly on all computers.
In 2.3.0, a minidump file is generated in `data\dumps` after a crash, so if you would like to send us the last-dated file to find out why this problem occurs, please do so.

BTW we have never removed any old [Release](https://github.com/Maplespe/DWMBlurGlass/releases) versions. It is there. You can just download them and use them as if they were new.
Make sure you visit the [Release page](https://github.com/Maplespe/DWMBlurGlass/releases) without filtering.
