### ISSUE TITLE
Taskbar/start menu blur slider

### ISSUE THREAD

**Issue by windowsxp3790** [Maplespe/DWMBlurGlass#46]
Can you implement a blur slider for the taskbar/start menu
The startisback blur options do not work nicely nicely with this program

**Comment by Maplespe** [comment]
If you mean blur radius, doesn't the program itself set the global blurr adius?

**Comment by NotJorrd** [comment]
when changing the blur radius on dwmblurglass, it also changes the blur radius on the taskbar+start menu when using startisback

**Comment by Maplespe** [comment]
I've already written in the readme
>Please note that the blur radius will affect the global, which also includes locations such as the start menu, notification center, etc....

This is true even for glass8.
Unless a custom blur is used, which we are looking into.

**Comment by windowsxp3790** [comment]
> If you mean blur radius, doesn't the program itself set the global blurr adius?

Yeah it does but the SIB blur slider conflicts with the global slider I think
Even when the SIB slider is set to 0

**Comment by windowsxp3790** [comment]
> I've already written in the readme
> 
> > Please note that the blur radius will affect the global, which also includes locations such as the start menu, notification center, etc....
> 
> This is true even for glass8. Unless a custom blur is used, which we are looking into.

Also about this
SIB was also kinda broken with Glass8 however there was a windhawk mod someone made  to fix the issue and apply glass8 blur to the taskbar and start without sib conflicting

**Comment by not-nullptr** [comment]
@windowsxp3790 this is a non-issue since, on windows 7 (which i assume you're trying to re-create), both windows and the taskbar used a blur radius of 3px.
