### ISSUE TITLE
Bottom window frame uses the blend color while it shouldn't (without having extend effect to borders on)

### ISSUE THREAD

**Issue by nopahc4** [Maplespe/DWMBlurGlass#47]
![image](https://github.com/Maplespe/DWMBlurGlass/assets/152728509/b040ff2c-2c2b-4ec3-b892-a87537757f9b)

I don't think it should be happening with the extend option off

**Comment by nopahc4** [comment]
![image](https://github.com/Maplespe/DWMBlurGlass/assets/152728509/b8f24157-d95f-401b-85bc-1ca00fb03c03)

better screenshot of dark explorer, it's more visible here, but it happens on all apps

**Comment by Maplespe** [comment]
This issue should have been fixed in the latest release.

**Comment by nopahc4** [comment]
> This issue should have been fixed in the latest release.

Fixed
