### ISSUE TITLE
Glass only showing on one monitor

### ISSUE THREAD

**Issue by twixhood** [Maplespe/DWMBlurGlass#53]
Glass doesn't work on both monitors unless I make my second monitor the main display. I love this program so far and would like to know if this could be fixed 👍 

Video
https://cdn.discordapp.com/attachments/1177051310894358581/1200228401596878978/2024-01-25_17-41-32.mp4?ex=65c56ace&is=65b2f5ce&hm=0a321005f90edf236b5aa1c194abe026415cc97f94fd9b1d186ed8f92c553d03&

**Comment by Maplespe** [comment]
Resolved in the new version.
