### ISSUE TITLE
File Explorer does not respect active window text color

### ISSUE THREAD

**Issue by craftnut** [Maplespe/DWMBlurGlass#55]
File Explorer will always have black text while focused in light app mode or white text while focused in dark app mode, regardless of the color set by DWMBlurGlass
![file](https://github.com/Maplespe/DWMBlurGlass/assets/61483322/a4933096-9c08-4d14-bae0-75bc0177791d)

**Comment by Maplespe** [comment]
Ribbon's text is self-drawn by the application (explorer) and has nothing to do with dwm, we can't change its color. Only applications that use the system default style title bar can be modified.
