### ISSUE TITLE
Sometimes, the program's GUI isn't appearing until a Windows restart

### ISSUE THREAD

**Issue by ghost** [Maplespe/DWMBlurGlass#57]
I just don't have many things to say, but if you wanna try to repeat the process yourself, try to do the following:

1. Start and close the app (3 times)
2. Unninstall the App and reinstall it again
3. Close the app and try to open it again

I'm currently on Windows 10 22H2 Core/Home Single Language x64 [Build: 19045.3930]

**Comment by Maplespe** [comment]
The temporary solution is to find the DWMBlurGlass process in Task Manager and end it.

**Comment by Maplespe** [comment]
Fixed, try the latest version
