### ISSUE TITLE
crashes on Windows 11 21H2 (Build 22000.2538)

### ISSUE THREAD

**Issue by SunshinePonyUwU** [Maplespe/DWMBlurGlass#59]
Unable to run on Windows 11 21H2 (Build 22000.2538),
dwm crashes and there is no blur effect after downloading the symbol file and installing DWMBlurGlass
![screenshot](https://github.com/Maplespe/DWMBlurGlass/assets/150380769/bc703d70-d946-4b2d-8429-b3ce26d88e2b)

**Comment by NicoBR333** [comment]
Not the owner here, but which steps have you made so far to try to fix the issue?

**Comment by SunshinePonyUwU** [comment]
> Not the owner here (it's like 4AM there), but which steps have you made so far to try to fix the issue?

I tried uninstalling and reinstalling
Close other programs that inject dwm (explorerpatcher)
Try an older version
When trying version 1.0.0, the window title bar has a fully transparent blur effect, but DWM will still crash.

**Comment by SunshinePonyUwU** [comment]
![image](https://github.com/Maplespe/DWMBlurGlass/assets/150380769/71c02e2e-241c-4955-9de5-0a508e7dffd5)

**Comment by Achille-Grs** [comment]
Same here in Windows 11 21H2 (Build 22000.2713).  
In version 23Η2 it works perfectly but I don't like the file explorer.
So, I prefer the 21H2 edition. 
Thank you for this amazing support of Aeroglass! 
(How I can donate to you?)

**Comment by Maplespe** [comment]
Resolved in the new version.
