### ISSUE TITLE
Win7 buttons broken without extend effect to borders, and a question

### ISSUE THREAD

**Issue by nopahc4** [Maplespe/DWMBlurGlass#64]
The windows 7 buttons are broken with extend effect to borders disabled, 
![image](https://github.com/Maplespe/DWMBlurGlass/assets/152728509/e7037d62-6041-4384-8e12-32d4082edd2b)
I noticed it doesn't happen if the theme used has borders in it, so only with the 10 theme and it is kinda annoying, btw could you make a toggle for the extended borders? By default enabling the option enables the borders, but they're rounded which I don't like since I'm not doing a 7 look, but it would be nice to have a toggle that changes it from rounded to sharp (like windows 8)

![image](https://github.com/Maplespe/DWMBlurGlass/assets/152728509/b0cda580-ed0c-46f1-842f-55102b606e6a)
looks like it's also broken when maximized, no matter if the extend option is on or off

![image](https://github.com/Maplespe/DWMBlurGlass/assets/152728509/ca816c27-0190-40bc-b86e-8cc3f76c4b91)
this is how it should look (btw i mean the empty space next to the close button

**Comment by nopahc4** [comment]
The new update has fixed the buttons on maximized windows, the issue of them being spaced so far away from the title bar still persists tho (extend borders off)

**Comment by Maplespe** [comment]
Resolved in the new version.

**Comment by nopahc4** [comment]
confirming, it's fixed
