### ISSUE TITLE
Doesn't work at all

### ISSUE THREAD

**Issue by cooolgamer** [Maplespe/DWMBlurGlass#65]
![image](https://github.com/Maplespe/DWMBlurGlass/assets/64099608/797bc91a-8133-4ac7-942d-947a95fda312)
Here is a picture of how it looks, I installed it, I got the popup that says it installed successfully, but nothing changed, I tried restarting my PC and no luck, still the same...
Even after a restart, it still says it's installed and yet nothing changed...
I tried to enable high contrast themes (even aero lite) and it still doesn't work. Any idea of what to do?

**Comment by nopahc4** [comment]
Check if symbol is valid

**Comment by cooolgamer** [comment]
Symbol is valid, I think it's because the account I'm in doesn't have administrator permissions and I used the administrator account to make changes, and they didn't apply to my main user

**Comment by cooolgamer** [comment]
okay it worked, it was because I didn't put the program in program files directory, now it works 👍
