### ISSUE TITLE
Exception

### ISSUE THREAD

**Issue by n-marcelino** [Maplespe/DWMBlurGlass#66]
Works great, except there are some windows that go fully blurred with this on. An example is the Huion Tablet app as seen below. Is there any way to add exceptions from the blur effect?

![unknown](https://github.com/Maplespe/DWMBlurGlass/assets/89496722/f7437aea-a90f-492d-80d5-577a28a3ef94)

![unknown](https://github.com/Maplespe/DWMBlurGlass/assets/89496722/4359d372-2a09-4bb7-80b6-aa82e3b627c6)

**Comment by Maplespe** [comment]
Resolved in the new version.
