### ISSUE TITLE
软件在启用时，任务管理器和控制面板等程序拖动时有异常延迟

### ISSUE THREAD

**Issue by AuroraePrime** [Maplespe/DWMBlurGlass#74]
系统版本是Windows 10 22H2 软件版本是1.0.4，此问题在之前的版本中也存在
当软件打开时，拖动任务管理器或控制面板等软件的窗口时，会明显感觉到延迟，也可以形容为拖动时不跟手，不知道是什么原因导致的，有知道原因的朋友可以告诉我一下，也希望开发者大佬们在后续的版本中修复

**Comment by AuroraePrime** [comment]
Uploading 2024-02-01 21-15-18.mp4…

**Comment by AuroraePrime** [comment]
https://github.com/Maplespe/DWMBlurGlass/assets/149229427/e32a0401-989b-4741-9e7b-40087b569974

**Comment by Maplespe** [comment]
已在新版本中解决
