### ISSUE TITLE
Multi-monitor reflections

### ISSUE THREAD

**Issue by CallyHam** [Maplespe/DWMBlurGlass#76]
I have mentioned this before in [another issue](https://github.com/Maplespe/DWMBlurGlass/issues/12#issuecomment-1900893144) but since i have 2 monitors, the reflection only displays on one of them (the one furthest to the left), i know it would possibly cause performance issues to stretch the reflection texture across 2 whole monitors but would it be possible to either:
Draw a seperate reflection texture for each monitor seperately (not sure if this would perform any better), or be able choose which single monitor displays the reflections?

**Comment by Maplespe** [comment]
In fact it has always been the case that reflections are drawn separately for each monitor. However, it's not clear why the reflections are only shown on one monitor; this has been fixed a couple times, but probably not completely.
Please wait for the new version to use custom blur effects,dwm has too many problems with internal blurring.

**Comment by ALTaleX531** [comment]
It's not ready yet, please wait for v2.0.0 release.
