### ISSUE TITLE
Can you please backport DWMBlurGlass for versions prior to Windows 10 2004?

### ISSUE THREAD

**Issue by Luximoz** [Maplespe/DWMBlurGlass#79]
I'm using LTSC 2019 (1809) and I don't want to use a newer version of Windows 10 for multiple reasons and this program has caught my attention lately, because it looks very promising and it seems just as good as Big Muscle's AeroGlass 8 program, which is abandonware at this point and is gonna end up being less accurate than this.

**Comment by inkballpro** [comment]
Probably wrong but this depends on APIs only in 2004 or later. Honestly, you should just use the older version of aeroglass here: http://web.archive.org/web/20220219100003/http://www.glass8.eu/files/setup-wrs-1.5.13.exe (1703-1909)

**Comment by ALTaleX531** [comment]
Theoretically, the lowest system version we can backport to is Windows 10 1607, but it takes a lot of effort and isn't worth it, I would recommend upgrading your system or using Glass 8.
