### ISSUE TITLE
Resizing being laggy in Windows 11 latest Beta

### ISSUE THREAD

**Issue by jimkoutso2008** [Maplespe/DWMBlurGlass#8]
First of all i wanna thank you sooo much for making this program.
This really feels "Glass8 if it were still alive" and im all for it.

So my issue is that resizing a window results in laggy resizing

OBS didnt want to work today so yea
https://cdn.discordapp.com/attachments/566265967932342272/1196905303325822976/VID_20240116_215231.mp4?ex=65b953ed&is=65a6deed&hm=885bb6c94a46fc166710fc9c9018bcc667b157120a7eacce0564d4a0ebf89b0d&

Moving windows around though don't cause anything wrong.

**Comment by s3ichii** [comment]
Same for me, but I'm using the stable version (22631.3007)

**Comment by Maplespe** [comment]
I mentioned the reasons in #7 and there may not be a solution in the short term.

**Comment by Maplespe** [comment]
Resolved in the new version.
