### ISSUE TITLE
Silent Intsall Parameter

### ISSUE THREAD

**Issue by oxy2ray** [Maplespe/DWMBlurGlass#82]
Will this program support silent install? I tried integrating it with my os image, but it doesn't seem to support the silent install parameter.

**Comment by ALTaleX531** [comment]
Duplicate of #24.

**Comment by oxy2ray** [comment]
closed

**Comment by teknixstuff** [comment]
@oxy2ray You can easily silent install it. Just create a scheduled task to run `DWMBlurGlass.exe loaddll` as admin during login.
