### ISSUE TITLE
[Bug] Installing SecureUXTheme broke DWMBlurGlass

### ISSUE THREAD

**Issue by TheInsane101** [Maplespe/DWMBlurGlass#83]
![Screenshot (868)](https://github.com/Maplespe/DWMBlurGlass/assets/104862146/3fc4142b-c08d-43b0-863c-5cb120f4f6a7)
I installed SecureUXTheme and it broke DWMBG after the reboot. It now gives me this error. I uninstalled SecureUXTheme and I still get this error even after another reboot. Did SUXT break it?

**Comment by Maplespe** [comment]
This is usually due to being blocked by other software (possibly an antivirus program), or insufficient permissions.

**Comment by TheInsane101** [comment]
Wow thanks for the quick reply! Do I just give DWMBG full permissions or put it in the exclusion list in Windows Defender?

**Comment by Maplespe** [comment]
It looks like your problem should be solved.

**Comment by TheInsane101** [comment]
I just used system restore. Never touching SUXT again. You can close this thread.
