### ISSUE TITLE
[Requests] Add option for titlebars to use system colour and add the text glow to the native unthemed UI

### ISSUE THREAD

**Issue by TheInsane101** [Maplespe/DWMBlurGlass#86]
The program would be even better than it already is if there was an option for the elements to use the chosen system colour that the rest of the UI uses, so that I don't have to change DWMBG's colour settings every time I change the OS's colours, which is tedious. Is this possible?

Also, it would be nice to have the text glow effect as an option for those who don't use msstyle themes, because without it, the text can be illegible when hovering over a part of a background with the same colour as the text.

These would be great additions, but ofc I udnerstand if it's not possible or too hard. I can wait! Thank you for giving us this program at all!

**Comment by Maplespe** [comment]
As I explained, system colors are opaque and there is no light/dark mode distinction, if you use system colors it will be boring opaque solid colors.
As for text glowing, this is not an official feature of this software, as I explained in #75, it depends on the 3rd party theme, if the 3rd party theme supports text glowing, we will draw it, if not, we can't draw it.
So we won't consider doing extra work at the moment, we've been doing too much work lately.

**Comment by nopahc4** [comment]
> The program would be even better than it already is if there was an option for the elements to use the chosen system colour that the rest of the UI uses, so that I don't have to change DWMBG's colour settings every time I change the OS's colours, which is tedious. Is this possible?
> 
> Also, it would be nice to have the text glow effect as an option for those who don't use msstyle themes, because without it, the text can be illegible when hovering over a part of a background with the same colour as the text.
> 
> These would be great additions, but ofc I udnerstand if it's not possible or too hard. I can wait! Thank you for giving us this program at all!

you can always modify stock 10 theme with like msstyle editor and add glow yourself

**Comment by DanTheGuy720** [comment]
> As I explained, system colors are opaque and there is no light/dark mode distinction, if you use system colors it will be boring opaque solid colors. As for text glowing, this is not an official feature of this software, as I explained in #75, it depends on the 3rd party theme, if the 3rd party theme supports text glowing, we will draw it, if not, we can't draw it. So we won't consider doing extra work at the moment, we've been doing too much work lately.

Is there no way to programmatically grab the current system personalization color values from the registry or something and just copy it into DWMBlurGlass config? That way, it's still using the application's coloring system over Windows. Though I suppose that would require CONSTANTLY checking the registry... unless you just did it once at initial logon or something.

**Comment by TheInsane101** [comment]
> As I explained, system colors are opaque and there is no light/dark mode distinction, if you use system colors it will be boring opaque solid colors. 

I don't mind resetting the opacity every time. In fact, it is better to reset the opacity than it is to constantly update the colours. Firstly, I usually have one opacity value that I always keep the same no matter which colours I choose. However, with colours, I have to open the RGB settings in DWMBG and match the values with those in the Startisback properties window, since I've set that to use the system colours.

Also, I don't understand how the system colours would make everything opaque. In Startisback, you can set the taskbar and start menu to use the same blur that DWMBG uses, and when the program uses the system colour, it doesn't become opaque. Is it different for the titlebars etc?


https://github.com/Maplespe/DWMBlurGlass/assets/104862146/b2526184-1f18-421b-80f5-aae85674ed00

**Comment by AquaHarp** [comment]
https://superuser.com/questions/1245923/registry-keys-to-change-personalization-settings
通过软件的GUI手动设置不透明度,只从注册表中取RGB颜色值(在`HKEY_CURRENT_USER\Software\Microsoft\Windows\DWM`的`AccentColor`这一项,数据格式是ABGR,Alpha值总是FF),保持已经设置的不透明度不变。
就算想跟随主题的变换而改变不透明度,这个数据在`HKEY_CURRENT_USER\Software\Microsoft\Windows\DWM`的`ColorizationColor`这一项,数据格式是ARGB。而且主题文件(例如aero.theme文件)里也有ColorizationColor这一项,数据格式是ARGB,而A的值对应着win7个性化设置的"颜色浓度"。可以给几个选项让用户决定是否让颜色或不透明度设置跟随系统注册表变化。

Set opacity values through DWMBlurGlass GUI.
Take the RGB values from Registry and ignore opacity values, I think. 

![image](https://github.com/Maplespe/DWMBlurGlass/assets/25244319/a61aae37-5916-433a-89ea-e238168baa95)

![image](https://github.com/Maplespe/DWMBlurGlass/assets/25244319/1c63e868-7033-4bb8-bf5b-75adb0b3d0b1)

**Comment by NotJorrd** [comment]
it's something glass8 does, which is why i guess i think it might be possible, i get that this isn't glass8 but it would be a cool feature to see, especially for people with these themes such as myself:

![image](https://github.com/Maplespe/DWMBlurGlass/assets/156122285/8e2b0681-f647-4a94-800a-69d17b734145)

**Comment by NotJorrd** [comment]
> > if you use system colors it will be boring opaque solid colors.
> 
> https://superuser.com/questions/1245923/registry-keys-to-change-personalization-settings 通过软件的GUI手动设置不透明度,只从注册表中读取RGB颜色值(在`HKEY_CURRENT_USER\Software\Microsoft\Windows\DWM`的`AccentColor`这一项,数据格式是ABGR,Alpha值总是FF),保持已经设置的不透明度不变。 就算想跟随主题的变换而改变不透明度,这个数据在`HKEY_CURRENT_USER\Software\Microsoft\Windows\DWM`的`ColorizationColor`这一项,数据格式是ARGB。而且主题文件(例如aero.theme文件)里也有`ColorizationColor`这一项,数据格式是ARGB,而A的值对应着win7个性化设置的"颜色浓度"。可以给几个选项让用户决定是否让颜色或不透明度设置跟随系统注册表变化。
> 
> Set opacity values through DWMBlurGlass GUI. Read RGB values from Registry and ignore opacity values, I think.
> 
> ![image](https://private-user-images.githubusercontent.com/25244319/302098056-a61aae37-5916-433a-89ea-e238168baa95.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcwNzAxNzgsIm5iZiI6MTcwNzA2OTg3OCwicGF0aCI6Ii8yNTI0NDMxOS8zMDIwOTgwNTYtYTYxYWFlMzctNTkxNi00MzNhLTg5ZWEtZTIzODE2OGJhYTk1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjA0VDE4MDQzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIxODFiMDNlZjNjMjMwMTkwNWUwMzFiZjI4ZDA4OWM3ZjE1ZTA2ZTM1M2QxOTYyNjU1ZmY5MjM1NDkzYWQxNmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.c78QxGSf-Rvj8_b8cD9PgVKcEG3uGPWdgUzN3c-IQgg)
> 
> ![image](https://private-user-images.githubusercontent.com/25244319/302098176-1c63e868-7033-4bb8-bf5b-75adb0b3d0b1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcwNzAxNzgsIm5iZiI6MTcwNzA2OTg3OCwicGF0aCI6Ii8yNTI0NDMxOS8zMDIwOTgxNzYtMWM2M2U4NjgtNzAzMy00YmI4LWJmNWItNzVhZGIwYjNkMGIxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjA0VDE4MDQzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJjZjI4YmU1YjE0ZWQ3OWQyNWM3YTgzOWIyZGJjNDYzMjAzYzdjZmExOTQyZTRmMDIzZWRlNWJmYmY2MDU3MWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.N5NVp3r98BfPEO9K43_agNb5w7xYUBe8LBieAKDzFYM)

my startisback doesn't change the color based on the system color, is there a way you did this?

**Comment by NotJorrd** [comment]
> > As I explained, system colors are opaque and there is no light/dark mode distinction, if you use system colors it will be boring opaque solid colors.
> 
> I don't mind resetting the opacity every time. In fact, it is better to reset the opacity than it is to constantly update the colours. Firstly, I usually have one opacity value that I always keep the same no matter which colours I choose. However, with colours, I have to open the RGB settings in DWMBG and match the values with those in the Startisback properties window, since I've set that to use the system colours every time I change them. This takes much more time to do.
> 
> Also, I don't understand how the system colours would make everything opaque. In Startisback, you can set the taskbar and start menu to use the same blur that DWMBG uses, and when the program uses the system colour, it doesn't become opaque. Is it different for the titlebars etc?
> 2024-02-04.11-26-49.-.Trim.mp4

my startisback doesn't change to my system colors, is there a way you made it adapt?

**Comment by ALTaleX531** [comment]
Actually we know how to read the color of the theme color, but can you tell me how to properly handle active/inactive window colors in light/dark mode? After all there is only one theme color, do they all have to use the same color? 😕
The availability of more configurations means that more effort is spent, and we'd like to spend our time implementing more valuable features such as custom blur methods. So I personally don't feel that this is a feature that should be prioritized for implementation, unless you guys can tell me more specifically why you're changing theme colors so often... 🤔

**Comment by NotJorrd** [comment]
> Actually we know how to read the color of the theme color, but can you tell me how to properly handle active/inactive window colors in light/dark mode? After all there is only one theme color, do they all have to use the same color? 😕 The availability of more configurations means that more effort is spent, and we'd like to spend our time implementing more valuable features such as custom blur methods. So I personally don't feel that this is a feature that should be prioritized for implementation, unless you guys can tell me more specifically why you're changing theme colors so often... 🤔


i get where you're coming from about focusing on custom blur and such, but this could make a big difference if you think about it, you're not only staying consistent with windows, but you'd be making our lives a lot easier and giving people that extra touch of customization

a lot of people use this software to recreate the look and feel of windows 7, and being able to change our theme in control panel to one of these, while having the color adapt accordingly would be awesome
![image](https://github.com/Maplespe/DWMBlurGlass/assets/156122285/d1402b1f-4f2e-4ad1-8778-e3508d323d06)

thank you for hearing us out

**Comment by TheInsane101** [comment]
Perfectly said. The ability to change the colour instantly is one of the charms of the Aero style of Vista and 7. Brining that back would add to the immersion. 

Also, I'm one of those people who can never make up their mind on a theme. I'm constantly changing mine all the time and experimenting with the infinite combinations between backgrounds and colours. Also, I have multiple Aero-based themes installed, including multiple Longhorn versions, Vista and 7, **and** their beta counterparts, all together, so being able to explore all of them is part of the fun!

I appreciate your ambition to work on the blur options! Sounds like powerful amazing stuff! You do what you want with your prioritise. I just hope this request can still fit in the list, at least AFTER the blur update is done?

**Comment by TheInsane101** [comment]
> my startisback doesn't change to my system colors, is there a way you made it adapt?
I'm sorry, I don't know what the issue might be. Maybe a SIB bug?

**Comment by NotJorrd** [comment]
> > my startisback doesn't change to my system colors, is there a way you made it adapt?
> 
> I'm sorry, I don't know what the issue might be. Maybe a SIB bug?

curious, what version are you using?

**Comment by TheInsane101** [comment]
> curious, what version are you using?

version 2.9.19. Idk if it's the latest. 

A workaround I used when I had the bug (I don't know how it got fixed) was to turn the "use custom colouring" options on and off, but then the opacity resets and you have to readjust it to how you had set it before.

**Comment by NotJorrd** [comment]
> > curious, what version are you using?
> 
> version 2.9.19. Idk if it's the latest.
> 
> A workaround I used when I had the bug (I don't know how it got fixed) was to turn the "use custom colouring" options on and off, but then the opacity resets and you have to readjust it to how you had set it before.

the issue was a setting in windows, fixed it

**Comment by Bungeetaco** [comment]
I second this request, and would like to see this implemented.

**Comment by TorutheRedFox** [comment]
the difference between active and inactive colors in aero afaik is that the inactive color is the same as the active color, just has the alpha multiplied by 0.4

**Comment by windowsxp3790** [comment]
> the difference between active and inactive colors in aero afaik is that the inactive color is the same as the active color, just has the alpha multiplied by 0.4

Oh really?
Interesting

**Comment by TheInsane101** [comment]
> > > curious, what version are you using?
> > 
> > 
> > version 2.9.19. Idk if it's the latest.
> > A workaround I used when I had the bug (I don't know how it got fixed) was to turn the "use custom colouring" options on and off, but then the opacity resets and you have to readjust it to how you had set it before.
> 
> the issue was a setting in windows, fixed it

For some reason my SIB no longer adapts the colour anymore; could you please tell me how you fixed it?
