### ISSUE TITLE
请帮忙

### ISSUE THREAD

**Issue by shamodeyu** [Maplespe/DWMBlurGlass#87]
目前操作系统教老旧Windows 10 Build 2004 (19041.388)，不能联网。网内另一台可以上网机器为Windows 7。
请问这样的情况如何下载合适该Windows 10的微软符号？ 
希望赐教。

**Comment by Maplespe** [comment]
你可以使用微软官方工具[SymChk](https://learn.microsoft.com/en-us/windows-hardware/drivers/debugger/using-symchk)
将你的uDwm.dll和dwmcore.dll(在C:\Windows\System32)复制到另一台机器
使用Symchk工具:
```cmd
symchk.exe .\uDWM.dll .\symbols
symchk.exe .\dwmcore.dll .\symbols
```
然后将下载好的symbols文件夹覆盖到DWMBlurGlass\data\symbols文件夹 重新打开GUI程序即可

**Comment by Maplespe** [comment]
你可以根据教程自行操作，或者使用以下的脚本:
此文件包含symchk和一个download.cmd脚本
只需解压 并将你的uDWM.dll和dwmcore.dll放到脚本目录下 运行脚本即可下载
[symchk.zip](https://github.com/Maplespe/DWMBlurGlass/files/14155144/symchk.zip)

**Comment by shamodeyu** [comment]
谢谢，我钢材沿着Symchk的路径进去，要Install Debugging Tools for Windows，要Download the Windows Driver Kit (WDK)
Article
[Step 1: Install Visual Studio 2022](https://learn.microsoft.com/en-us/windows-hardware/drivers/download-the-wdk#download-icon-step-1-install-

visual-studio-2022)
[Step 2: Install SDK](https://learn.microsoft.com/en-us/windows-hardware/drivers/download-the-wdk#download-icon-step-2-install-sdk)
[Step 3: Install WDK](https://learn.microsoft.com/en-us/windows-hardware/drivers/download-the-wdk#download-icon-step-3-install-wdk)

已超出我的能力及WIndows 7系统权限。

**Comment by shamodeyu** [comment]
谢谢！

已使用您的脚本下载到了symbols了。

**Comment by shamodeyu** [comment]
但是操作系统界面无变化

尝试上传截图，但总是消失

请问您有无能够接受图片的其他方式？

**Comment by Maplespe** [comment]
可以b站私信我或者加群(b站个人签名)

**Comment by Maplespe** [comment]
另外说一下，符号页面显示"有效"才行

**Comment by shamodeyu** [comment]
符号已显示有效了。

另，已在b站向您发送信息，系统限制在您回复之前我只能发送一条文字信息。

**Comment by shamodeyu** [comment]
![P40204-113016](https://github.com/Maplespe/DWMBlurGlass/assets/123850195/353623bf-c68f-462a-9c43-57c155de9a3e)
![P40204-113021](https://github.com/Maplespe/DWMBlurGlass/assets/123850195/61030974-3a42-4cc8-83e5-a34fe4c2a78d)
![P40204-113037](https://github.com/Maplespe/DWMBlurGlass/assets/123850195/5ad7f13d-5fdd-405f-9b48-762e0e1941af)
