### ISSUE TITLE
[Minor bug] Reflection image on Windows 10 snipping tool

### ISSUE THREAD

**Issue by TheInsane101** [Maplespe/DWMBlurGlass#88]
When a window is fullscreen, the modern snipping tool includes the reflection image, and it's cropped out. **The image does not end up in the image taken, only when in the process of selecting the area to snip.**

This is more amusing than problematic, and I think it should be low priority on the fixing list; after all, it's still possible to use the legacy win32 version of the tool instead, which does not have the same issue. Just reporting it so it's on the list.

https://github.com/Maplespe/DWMBlurGlass/assets/104862146/b33256ff-74e5-46ee-b0f7-c148268c042e

**Comment by ALTaleX531** [comment]
Congratulations, you've successfully proved that #26 still exists.😉

**Comment by Maplespe** [comment]
@ALTaleX531 😅

**Comment by Maplespe** [comment]
That's okay, we'll be updating the custom blur soon and all these problems will be gone.

**Comment by NotJorrd** [comment]
i had a video of this issue ready to post, thank you for proving this issue lol, glad to hear there will be a custom blur soon

**Comment by TheInsane101** [comment]
> Congratulations, you've successfully proved that #26 still exists.😉

I had seen NotJorrd's post, but he had no visual representation, and Maplespe did not understand how to replicate the bug. I wanted to provide the visual explanation.

**Comment by Maplespe** [comment]
Resolved in the new version.
