### ISSUE TITLE
Feature request : Transfer the settings from the config.ini file to the registry

### ISSUE THREAD

**Issue by OrthodoxWindows** [Maplespe/DWMBlurGlass#89]
First of all, thank you for this awesome software!

It is currently difficult to create themes for DWMBlurGlass, because an ini file is difficult to edit without using the GUI. Conversely, it is easy to write to registry keys in a non-graphical way.
When I talk about themes, I think of the possibility of integrating, alongside a Windows .theme file, the possibility of changing the DWMBlurGlass parameters. This is what other software like this does, because the settings are stored in the registry.

Additionally, I have a question: where is the parameter stored that determines whether DWMBlurGlass is installed or uninstalled ?

**Comment by Maplespe** [comment]
I don't think it's necessary, you can totally write to the config file to change the configuration.
To determine the installation path of the program you can access the scheduled task manager and find the task named "`DWMBlurGlass_Extend`" This contains the path where the program is located and you can access it to get the installation path of the program and modify the configuration.

**Comment by aubymori** [comment]
> an ini file is difficult to edit without using the GUI. Conversely, it is easy to write to registry keys in a non-graphical way.

I don't see how this is the case? `.reg` file syntax *is* INI, but more difficult to read for non-technical users since you are reading reg keys directly exported instead of a layout specifically made for the program.

**Comment by Almondatchy** [comment]
> > an ini file is difficult to edit without using the GUI. Conversely, it is easy to write to registry keys in a non-graphical way.
> 
> I don't see how this is the case? `.reg` file syntax _is_ INI, but more difficult to read for non-technical users since you are reading reg keys directly exported instead of a layout specifically made for the program.

I think that `.ini` files should be for exporting configurations and editing them externally while `.reg` registry files should be for internal use

**Comment by aubymori** [comment]
> > > an ini file is difficult to edit without using the GUI. Conversely, it is easy to write to registry keys in a non-graphical way.
> > 
> > 
> > I don't see how this is the case? `.reg` file syntax _is_ INI, but more difficult to read for non-technical users since you are reading reg keys directly exported instead of a layout specifically made for the program.
> 
> I think that `.ini` files should be for exporting configurations and editing them externally while `.reg` registry files should be for internal use

For one, `.reg` registry files are for importing registry keys and are not actually registry keys themselves, and for two, if it's not broken, why fix it?

**Comment by OrthodoxWindows** [comment]
> I don't see how this is the case? `.reg` file syntax _is_ INI, but more difficult to read for non-technical users since you are reading reg keys directly exported instead of a layout specifically made for the program.

I'm not talking about using .reg files, but editing th settings using the command line. For the non-technical user, I think manual editing will always be the software interface.

**Comment by OrthodoxWindows** [comment]
> I don't think it's necessary, you can totally write to the config file to change the configuration. To determine the installation path of the program you can access the scheduled task manager and find the task named "`DWMBlurGlass_Extend`" This contains the path where the program is located and you can access it to get the installation path of the program and modify the configuration.

Thank you for the answers.
You mean it's possible to use the command line/PowerShell to modify the configuration file ?
Concerning the scheduled task, I found it in the task manager; I noticed that the task is completely removed if DWMBlurGlass is uninstalled. Wouldn't it be easier to deactivate it? Finally, what is the parameter which, at the very moment of installation/uninstallation, causes DWMBlurGlass to be running/stopping?

**Comment by Maplespe** [comment]
The run parameter you can see in the command line parameter of the scheduled task.
There is no method to stop immediately using the command line, you have to end the dwm process.
