### ISSUE TITLE
Glass Titlebar does not propery extend on properties windows on some msstyles

### ISSUE THREAD

**Issue by legofanlovessayori** [Maplespe/DWMBlurGlass#90]
As the title says, the titlebar blur doesn't extend fully to the edge on some msstyles (noticeable when using startallback)

![grafik](https://github.com/Maplespe/DWMBlurGlass/assets/94994630/3cccd131-501a-4542-8d7c-56abd933e196)

**Comment by Maplespe** [comment]
Resolved in the new version.
