### ISSUE TITLE
Extend transparency to ribbon/address bar in file explorer in windows 10

### ISSUE THREAD

**Issue by robbely** [Maplespe/DWMBlurGlass#92]
As the titles says, is this already possible, or can this be added? 
This was available in another (now discontinued) app. I can't find any screenshots, but I'll add one if I do.

**Comment by robbely** [comment]
> no

Then this is a feature request :)

**Comment by TheInsane101** [comment]
> Then this is a feature request :)

I'd personally be happy enough that an alternative exists. Why need it added in here when you can already get it there?

**Comment by robbely** [comment]
> > Then this is a feature request :)
> 
> I'd personally be happy enough that an alternative exists. Why need it added in here when you can already get it there?

The older "aeroglass" app which no longer works had an all-in-one feature for this. Also, looking at images of the aerexplorer solution, it looks like this works by changing explorer to look like window 7 rather than keeping the windows 10 look.

**Comment by ALTaleX531** [comment]
Use [ExplorerBlurMica](https://github.com/Maplespe/ExplorerBlurMica) or OldNewExplorer, this is not a feature that can be implemented in dwm side.

**Comment by robbely** [comment]
> Use [ExplorerBlurMica](https://github.com/Maplespe/ExplorerBlurMica) or OldNewExplorer, this is not a feature that can be implemented in dwm side.

ExplorerBlurMica appears to be for the window contents, not the titlebar/ribbon and OldNewExplorer also uses the windows 7 look instead of the windows 10 one.

If it can't be implemented in dwm side, I'm wondering how the aeroglass app managed it.

**Comment by Maplespe** [comment]
You may have misremembered that AeroGlass does not extend to the ribbon, you have to use OldNewExplorer.

**Comment by robbely** [comment]
> You may have misremembered that AeroGlass does not extend to the ribbon, you have to use OldNewExplorer.

That's always possible, it has been a long time since AeroGlass worked. OldNewExplorer doesn't sound familiar though and I would likely have remembered if I had reverted my system to a windows 7 look.

**Comment by Apis035** [comment]
> That's always possible, it has been a long time since AeroGlass worked. OldNewExplorer doesn't sound familiar though and I would likely have remembered if I had reverted my system to a windows 7 look.

AeroGlass never did that.

The glass address bar is possible on Command Bar (Windows 7 style), not on Ribbon Bar (Window 8/10 style) explorer.
You can achieve that with OldNewExplorer > "Use command bar instead of Ribbon" > "Enable glass on navigation bar"

As Maplespe said, you must've been misremembered how AeroGlass works.

**Comment by catneptune** [comment]
> You may have misremembered that AeroGlass does not extend to the ribbon, you have to use OldNewExplorer.

or use windhawk + aerexplorer, it has many more features like fixing padding and adding space between every category like windows 8.x, 7
and also vista stuff
