### ISSUE TITLE
Borders missing on Windows 11

### ISSUE THREAD

**Issue by teknixstuff** [Maplespe/DWMBlurGlass#94]
On Windows 11 borders don't show. Tested on 23H2, used multiple msstyles themes, none have working borders.

**Comment by ALTaleX531** [comment]
This is a Windows 11 thing, nothing to do with DwmBlurGlass.

**Comment by teknixstuff** [comment]
Ah okay. I was just wondering if DWMBlurGlass could implement a workaround to avoid needing a uDWM.dll patch to fix it.
