### ISSUE TITLE
Make the active to inactive window fade transition an option.

### ISSUE THREAD

**Issue by angelbruni** [Maplespe/DWMBlurGlass#96]
Title.
![explorer_lX9JemOsL7](https://github.com/Maplespe/DWMBlurGlass/assets/48385307/ede32b58-195e-4530-a613-596b26bb3d58)

**Comment by Maplespe** [comment]
If you don't like this effect, a temporary solution is to select the "OldBlur(AccentBlurBehind)" method in the "Advanced" page.

**Comment by angelbruni** [comment]
Oh, thank you.

(I've been awake the whole night waiting for this update lol.)

**Comment by aubymori** [comment]
bump bump bump this effect is so annoying
