### ISSUE TITLE
Window border becomes thick during the animation

### ISSUE THREAD

**Issue by funn-hue** [Maplespe/DWMBlurGlass#97]
First of all thank you for fixing the bugs we had before and for the custom blur method, you're doing a really great job and this program had become better than glass8. I have just downloaded the new version and found a bug occuring when an app closes, the window border becomes thick during the animation, i'm attaching a photo of my config and a gif of the issue
![image](https://github.com/Maplespe/DWMBlurGlass/assets/152728509/c20f0838-24ca-4901-8ef1-e51b96ef421b)
![219spHCWJS](https://github.com/Maplespe/DWMBlurGlass/assets/152728509/84903af7-799d-4d2e-8a2e-35cd413e333e)

After taking the gif i switched off the setting for windows 7 sized buttons and yeah it also occurs with the default sizing

**Comment by Maplespe** [comment]
This is a known issue that I forgot to mention.

**Comment by nopahc4** [comment]
> This is a known issue that I forgot to mention. It's not easy to fix right now, but you can always switch back to the OldBlur method on the Advanced page.

alright, ill just attempt to make a theme with borders to hide it for now

**Comment by nopahc4** [comment]
> This is a known issue that I forgot to mention. It's not easy to fix right now, but you can always switch back to the OldBlur method on the Advanced page.

actually there is a temporary fix, disabling window animations in SystemPropertiesAdvanced.exe

**Comment by Maplespe** [comment]
Fixed in new version.

**Comment by nopahc4** [comment]
> Fixed in new version.

it still seems to be happening for me unfortunately, it's just like not the whole border appears, only near the close button and it's faded, with extend effect to borders on the full borders return when the app is closing, and even minimizing. also when closing the title bar becomes pure white (without extend effect to borders on)

**Comment by Maplespe** [comment]
Have you modified the theme? Try the default aero theme, it should be fine.

**Comment by nopahc4** [comment]
> Have you modified the theme? Try the default aero theme, it should be fine.



> Have you modified the theme? Try the default aero theme, it should be fine.

same thing happens on the default theme
