### ISSUE TITLE
Caption buttons glitch

### ISSUE THREAD

**Issue by AxelKelo** [Maplespe/DWMBlurGlass#98]
Version 2.0.0 introduced this visual glitch for me, I use 120 dpi by the way. Also, it seems that the taskbar reflections are missing.
![rgrtthrj47i7k,g](https://github.com/Maplespe/DWMBlurGlass/assets/159111168/00fcf3e8-765f-4637-a2c0-dd9a0b61a18d)

**Comment by Maplespe** [comment]
Are you Windows 11, I tested everything fine in Windows 10, my environment has always been 125% zoom ratio .

**Comment by Maplespe** [comment]
Are you Windows 11, I tested everything fine in Windows 10, my environment has always been 125% zoom ratio.
Have you also modified the registry for window border width?

**Comment by nopahc4** [comment]
not related to the issue youre facing but i also noticed the close button kind of breaks in explorer for me, also happens in mobility center 
![explorer_Z9JcB4n5PQ](https://github.com/Maplespe/DWMBlurGlass/assets/152728509/3be23129-78f7-4ed8-9c15-783c44172a35)

**Comment by nopahc4** [comment]
> Version 2.0.0 introduced this visual glitch for me, I use 120 dpi by the way. Also, it seems that the taskbar reflections are missing. ![rgrtthrj47i7k,g](https://private-user-images.githubusercontent.com/159111168/302526358-00fcf3e8-765f-4637-a2c0-dd9a0b61a18d.PNG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcyMDI3NzQsIm5iZiI6MTcwNzIwMjQ3NCwicGF0aCI6Ii8xNTkxMTExNjgvMzAyNTI2MzU4LTAwZmNmM2U4LTc2NWYtNDYzNy1hMmMwLWRkOWEwYjYxYTE4ZC5QTkc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIwNlQwNjU0MzRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01NzYzNzIwNDIxNGRlMzE4ZWE3NGEzMDU1OTMxMTliNjhlMmMzMjM5M2E2ODQ0YTJlN2ZjMmM1MjQyODYxNDlkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.gWOFf1V-KYF5QPzt1zdnkNUuqKLlEqE9XXoCmI_7GQo)

i applied a theme with borders enabled in it and can confirm i get the same result

**Comment by AxelKelo** [comment]
Hi, I am on Win 10. I use Aero10 msstyles and Aerexplorer Windhawk mod. Didn't touch border width in any way, only decreased titlebar height to 21 in Winaero Tweaker

**Comment by Maplespe** [comment]
@nopahc4 I updated the attachment and re-downloaded it to try and see if I still have the problem.

**Comment by nopahc4** [comment]
> @nopahc4 I updated the attachment and re-downloaded it to try and see if I still have the problem.

yes, the close button escaping the window is fixed, but OP's issue still persists

**Comment by Maplespe** [comment]
It's weird, I'm not sure if it's related to the theme, I'm using the aero10_seven.zip posted in #5
I don't have this problem here though because 2.0.0 calculates based on the actual window borders.
I tried doing a bit of a fallback and if the theme borders are empty back to the 1.0.4 calculation.
[Release_x64.zip](https://github.com/Maplespe/DWMBlurGlass/files/14176213/Release_x64.zip)

**Comment by nopahc4** [comment]
> It's weird, I'm not sure if it's related to the theme, I'm using the aero10_seven.zip posted in #5 I don't have this problem here though because 2.0.0 calculates based on the actual window borders. I tried doing a bit of a fallback and if the theme borders are empty back to the 1.0.4 calculation. [Release_x64.zip](https://github.com/Maplespe/DWMBlurGlass/files/14176213/Release_x64.zip)

![image](https://github.com/Maplespe/DWMBlurGlass/assets/152728509/32a9334d-8af7-439e-9d54-e955989e57d5)
tried the new attachment and same thing, now ill try with the theme youre using

**Comment by nopahc4** [comment]
![image](https://github.com/Maplespe/DWMBlurGlass/assets/152728509/678e73f0-d884-4e7d-8d49-c2723e240917)
alright thats weird, it works with the theme you shared

**Comment by AxelKelo** [comment]
It doesn't change for me, tried both the theme and release you recommended

**Comment by nopahc4** [comment]
I have made a 10 theme with borders, using metrics from a 8.1 theme, and the button spacing is fixed too, so this issue isn't related to the program
