### ISSUE TITLE
Add rounded corner support for new blur method 

### ISSUE THREAD

**Issue by kfh83** [Maplespe/DWMBlurGlass#99]
Such as glass8, allowing you to select a custom radius for the rounded corners, so we don't get this:
![image](https://github.com/Maplespe/DWMBlurGlass/assets/85626296/6e12c3c4-933d-4a6a-a07a-9f88d6044c52)

**Comment by Maplespe** [comment]
In fact this is already included.
You just need to check the "Effects extend to borders" option to enable rounded cropping. Custom blurring automatically extends the borders according to the theme, so this option will only enable rounded corner cropping.
The default is 8px, as most third-party themes have this value.
If you want to change this value, you can manually edit data\config.ini
Under [config] add extendRound
Currently it can't be set in the GUI.
Example
``` ini
[config]
extendRound=10
```
Save the changes, change any property in the GUI and click refresh.
